set(OCTAVE_EXPECTED_VERSION "11.3.0")

function(_pure_octave_require_below_root path description missing_var)
  if (EXISTS "${path}")
    file(REAL_PATH "${path}" normalized_path EXPAND_TILDE)
  else ()
    cmake_path(NORMAL_PATH path OUTPUT_VARIABLE normalized_path)
  endif ()
  cmake_path(IS_PREFIX OCTAVE_ROOT_NORMALIZED "${normalized_path}" NORMALIZE is_below_root)
  if (NOT is_below_root)
    list(APPEND ${missing_var} "${description}: ${path} (outside OCTAVE_ROOT)")
  elseif (NOT EXISTS "${normalized_path}")
    list(APPEND ${missing_var} "${description}: ${path}")
  endif ()
  set(${missing_var} "${${missing_var}}" PARENT_SCOPE)
endfunction ()

function(_pure_octave_find_file output)
  set(candidates "")
  foreach (name IN LISTS ARGN)
    file(GLOB_RECURSE found_files LIST_DIRECTORIES FALSE "${OCTAVE_ROOT_NORMALIZED}/*/${name}")
    list(APPEND candidates ${found_files})
  endforeach ()
  list(REMOVE_DUPLICATES candidates)
  list(SORT candidates)
  if (candidates)
    list(GET candidates 0 selected)
    set(${output} "${selected}" PARENT_SCOPE)
  else ()
    set(${output} "" PARENT_SCOPE)
  endif ()
endfunction ()

function(_pure_octave_find_directory output relative_path)
  file(GLOB_RECURSE candidate_dirs LIST_DIRECTORIES TRUE
    "${OCTAVE_ROOT_NORMALIZED}/*/${relative_path}")
  list(SORT candidate_dirs)
  foreach (candidate IN LISTS candidate_dirs)
    if (IS_DIRECTORY "${candidate}")
      set(${output} "${candidate}" PARENT_SCOPE)
      return ()
    endif ()
  endforeach ()
  set(${output} "${OCTAVE_ROOT_NORMALIZED}/${relative_path}" PARENT_SCOPE)
endfunction ()

function(pure_octave_validate_toolchain)
  if (NOT OCTAVE_ROOT)
    message(FATAL_ERROR "OCTAVE_ROOT is required.")
  endif ()

  file(REAL_PATH "${OCTAVE_ROOT}" OCTAVE_ROOT_NORMALIZED EXPAND_TILDE)
  set(OCTAVE_ROOT_NORMALIZED "${OCTAVE_ROOT_NORMALIZED}" PARENT_SCOPE)
  if (NOT IS_DIRECTORY "${OCTAVE_ROOT_NORMALIZED}")
    message(FATAL_ERROR "OCTAVE_ROOT is not a directory: ${OCTAVE_ROOT}")
  endif ()

  _pure_octave_find_file(OCTAVE_EXECUTABLE_CANDIDATE octave-cli.exe octave-cli)
  if (NOT OCTAVE_EXECUTABLE_CANDIDATE)
    set(OCTAVE_EXECUTABLE_CANDIDATE "${OCTAVE_ROOT_NORMALIZED}/bin/octave-cli.exe")
  endif ()
  _pure_octave_find_file(OCTAVE_MKOCTFILE_CANDIDATE mkoctfile.exe mkoctfile)
  if (NOT OCTAVE_MKOCTFILE_CANDIDATE)
    set(OCTAVE_MKOCTFILE_CANDIDATE "${OCTAVE_ROOT_NORMALIZED}/bin/mkoctfile.exe")
  endif ()
  _pure_octave_find_file(OCTAVE_OCT_H_CANDIDATE oct.h)
  if (NOT OCTAVE_OCT_H_CANDIDATE)
    set(OCTAVE_OCT_H_CANDIDATE "${OCTAVE_ROOT_NORMALIZED}/include/octave-${OCTAVE_EXPECTED_VERSION}/octave/oct.h")
  endif ()
  _pure_octave_find_file(OCTAVE_OCTAVE_H_CANDIDATE octave.h)
  if (NOT OCTAVE_OCTAVE_H_CANDIDATE)
    set(OCTAVE_OCTAVE_H_CANDIDATE "${OCTAVE_ROOT_NORMALIZED}/include/octave-${OCTAVE_EXPECTED_VERSION}/octave/octave.h")
  endif ()
  _pure_octave_find_file(OCTAVE_INTERPRETER_H_CANDIDATE interpreter.h)
  if (NOT OCTAVE_INTERPRETER_H_CANDIDATE)
    set(OCTAVE_INTERPRETER_H_CANDIDATE "${OCTAVE_ROOT_NORMALIZED}/include/octave-${OCTAVE_EXPECTED_VERSION}/octave/interpreter.h")
  endif ()
  _pure_octave_find_file(OCTAVE_OCTINTERP_IMPORT_CANDIDATE liboctinterp.dll.a liboctinterp.lib)
  if (NOT OCTAVE_OCTINTERP_IMPORT_CANDIDATE)
    set(OCTAVE_OCTINTERP_IMPORT_CANDIDATE "${OCTAVE_ROOT_NORMALIZED}/lib/liboctinterp.dll.a")
  endif ()
  _pure_octave_find_file(OCTAVE_OCTAVE_IMPORT_CANDIDATE liboctave.dll.a liboctave.lib)
  if (NOT OCTAVE_OCTAVE_IMPORT_CANDIDATE)
    set(OCTAVE_OCTAVE_IMPORT_CANDIDATE "${OCTAVE_ROOT_NORMALIZED}/lib/liboctave.dll.a")
  endif ()
  get_filename_component(OCTAVE_RUNTIME_DIR_CANDIDATE "${OCTAVE_EXECUTABLE_CANDIDATE}" DIRECTORY)
  file(GLOB_RECURSE octave_runtime_libraries LIST_DIRECTORIES FALSE
    "${OCTAVE_ROOT_NORMALIZED}/*/liboctinterp*.dll")
  list(SORT octave_runtime_libraries)
  if (octave_runtime_libraries)
    list(GET octave_runtime_libraries 0 octave_runtime_library)
    get_filename_component(OCTAVE_RUNTIME_DIR_CANDIDATE "${octave_runtime_library}" DIRECTORY)
  else ()
    set(octave_runtime_library "${OCTAVE_RUNTIME_DIR_CANDIDATE}/liboctinterp.dll")
  endif ()
  _pure_octave_find_directory(OCTAVE_MODULE_DIR_CANDIDATE "lib/octave/${OCTAVE_EXPECTED_VERSION}")
  _pure_octave_find_directory(OCTAVE_SHARE_DIR_CANDIDATE "share/octave/${OCTAVE_EXPECTED_VERSION}")

  set(missing_paths "")
  _pure_octave_require_below_root("${OCTAVE_EXECUTABLE_CANDIDATE}" "octave-cli executable" missing_paths)
  _pure_octave_require_below_root("${OCTAVE_MKOCTFILE_CANDIDATE}" "mkoctfile" missing_paths)
  _pure_octave_require_below_root("${OCTAVE_OCT_H_CANDIDATE}" "public headers (oct.h)" missing_paths)
  _pure_octave_require_below_root("${OCTAVE_OCTAVE_H_CANDIDATE}" "public headers (octave.h)" missing_paths)
  _pure_octave_require_below_root("${OCTAVE_INTERPRETER_H_CANDIDATE}" "public headers (interpreter.h)" missing_paths)
  _pure_octave_require_below_root("${OCTAVE_OCTINTERP_IMPORT_CANDIDATE}" "import libraries (liboctinterp)" missing_paths)
  _pure_octave_require_below_root("${OCTAVE_OCTAVE_IMPORT_CANDIDATE}" "import libraries (liboctave)" missing_paths)
  _pure_octave_require_below_root("${octave_runtime_library}" "runtime directory (liboctinterp runtime)" missing_paths)
  _pure_octave_require_below_root("${OCTAVE_MODULE_DIR_CANDIDATE}" "module directory" missing_paths)
  _pure_octave_require_below_root("${OCTAVE_SHARE_DIR_CANDIDATE}" "share directory" missing_paths)
  if (missing_paths)
    string(REPLACE ";" "\n  - " missing_text "${missing_paths}")
    message(FATAL_ERROR
      "Missing required Octave ${OCTAVE_EXPECTED_VERSION} toolchain paths:\n  - ${missing_text}")
  endif ()

  set(required_outputs
    OCTAVE_EXECUTABLE OCTAVE_MKOCTFILE OCTAVE_RUNTIME_DIR
    OCTAVE_MODULE_DIR OCTAVE_SHARE_DIR)
  set(OCTAVE_EXECUTABLE "${OCTAVE_EXECUTABLE_CANDIDATE}" CACHE FILEPATH "Validated Octave CLI" FORCE)
  set(OCTAVE_MKOCTFILE "${OCTAVE_MKOCTFILE_CANDIDATE}" CACHE FILEPATH "Validated Octave mkoctfile" FORCE)
  set(OCTAVE_RUNTIME_DIR "${OCTAVE_RUNTIME_DIR_CANDIDATE}" CACHE PATH "Validated Octave runtime directory" FORCE)
  set(OCTAVE_MODULE_DIR "${OCTAVE_MODULE_DIR_CANDIDATE}" CACHE PATH "Validated Octave module directory" FORCE)
  set(OCTAVE_SHARE_DIR "${OCTAVE_SHARE_DIR_CANDIDATE}" CACHE PATH "Validated Octave share directory" FORCE)
  set(OCTAVE_VERSION "${OCTAVE_EXPECTED_VERSION}" CACHE STRING "Validated Octave version" FORCE)
endfunction ()
