include_guard(GLOBAL)

find_package(BISON 3.0 REQUIRED)
find_package(FLEX 2.6 REQUIRED)
find_package(Iconv REQUIRED)
find_package(PkgConfig REQUIRED)
find_package(Threads REQUIRED)

pkg_check_modules(GMP REQUIRED IMPORTED_TARGET gmp)
pkg_check_modules(MPFR REQUIRED IMPORTED_TARGET mpfr)
pkg_check_modules(READLINE REQUIRED IMPORTED_TARGET readline)
pkg_check_modules(PCREPOSIX REQUIRED IMPORTED_TARGET libpcreposix)

pkg_check_modules(GSL QUIET IMPORTED_TARGET gsl)
find_program(PURE_FAUST_EXECUTABLE NAMES faust)
find_program(PURE_FLANG_EXECUTABLE NAMES flang-22 flang-new-22)
find_program(PURE_GFORTRAN_EXECUTABLE NAMES gfortran)
find_program(PURE_SPHINX_BUILD NAMES sphinx-build)

message(STATUS "Bison: ${BISON_VERSION} (${BISON_EXECUTABLE})")
message(STATUS "Flex: ${FLEX_VERSION} (${FLEX_EXECUTABLE})")
message(STATUS "GMP: ${GMP_VERSION}")
message(STATUS "MPFR: ${MPFR_VERSION}")
message(STATUS "readline: ${READLINE_VERSION}")
message(STATUS "PCRE POSIX: ${PCREPOSIX_VERSION}")

if(GSL_FOUND)
  message(STATUS "GSL: ${GSL_VERSION}")
else()
  message(STATUS "GSL: not found; bitcode examples requiring GSL will be disabled")
endif()

if(PURE_FAUST_EXECUTABLE)
  message(STATUS "Faust: ${PURE_FAUST_EXECUTABLE}")
else()
  message(STATUS "Faust: not found; Faust integration fixtures will be disabled")
endif()

if(PURE_FLANG_EXECUTABLE)
  message(STATUS "Flang: ${PURE_FLANG_EXECUTABLE}")
else()
  message(STATUS "Flang: not found; Fortran bitcode fixtures will be disabled")
endif()

if(PURE_GFORTRAN_EXECUTABLE)
  message(STATUS "GFortran: ${PURE_GFORTRAN_EXECUTABLE}")
else()
  message(STATUS "GFortran: not found; native Fortran examples will be disabled")
endif()

if(PURE_SPHINX_BUILD)
  message(STATUS "Sphinx: ${PURE_SPHINX_BUILD}")
else()
  message(STATUS "Sphinx: not found; documentation targets will be disabled")
endif()
