function(pure_faust_audit_staged_content stage)
  set(files_to_scan ${ARGN})
  file(GLOB_RECURSE staged_files LIST_DIRECTORIES false "${stage}/*")
  foreach(path IN LISTS staged_files)
    if(path MATCHES "\\.(cmake|ps1|md|txt|sha256|c|ll)$")
      list(APPEND files_to_scan "${path}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES files_to_scan)
  foreach(path IN LISTS files_to_scan)
    file(READ "${path}" content)
    string(REPLACE "\\" "/" content "${content}")
    if(content MATCHES "(^|[^A-Za-z0-9_])[A-Za-z]:/")
      message(FATAL_ERROR "Embedded absolute Windows path in staged text: ${path}")
    endif()
    foreach(forbidden IN LISTS PURE_FAUST_AUDIT_FORBIDDEN_PATHS)
      string(REPLACE "\\" "/" forbidden "${forbidden}")
      string(TOLOWER "${forbidden}" forbidden_lower)
      string(TOLOWER "${content}" content_lower)
      string(FIND "${content_lower}" "${forbidden_lower}" forbidden_match)
      if(NOT forbidden_match EQUAL -1)
        message(FATAL_ERROR
          "Embedded forbidden build path in staged text: ${path}")
      endif()
    endforeach()
  endforeach()
endfunction()
