if(LEGACY)
  # This independently created, exact scratch leaf is safe even when the old
  # implementation wrongly deletes it. The survivor is our behavior oracle.
  set(work "${MODULE_DIR}/cleanup-red-owned")
  file(MAKE_DIRECTORY "${work}/victim")
  file(WRITE "${work}/victim/foreign-sentinel" "must survive\n")
  execute_process(COMMAND "${CMAKE_COMMAND}"
    "-DPURE_EXECUTABLE=${FIXTURE}" "-DPURE_SOURCE_DIR=${PURE_SOURCE_DIR}"
    "-DMODULE_DIR=${MODULE_DIR}" "-DTEST_SCRIPT=${work}/wrong.pure"
    "-DTEST_DIRECTORY=${work}/victim"
    -P "${PURE_SOURCE_DIR}/cmake/RunPureTest.cmake"
    RESULT_VARIABLE rc OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
  if(NOT EXISTS "${work}/victim/foreign-sentinel")
    message(FATAL_ERROR "RED: cleanup removed a leaf without an ownership sentinel")
  endif()
endif()

function(create_leaf out)
  execute_process(COMMAND "${RUNNER}" --create-leaf RESULT_VARIABLE rc
    OUTPUT_VARIABLE leaf OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "create-leaf failed ${rc}")
  endif()
  set(${out} "${leaf}" PARENT_SCOPE)
endfunction()
set(negative 0)
function(reject name path)
  execute_process(COMMAND "${RUNNER}" --cleanup --cwd "${path}"
    RESULT_VARIABLE rc OUTPUT_QUIET ERROR_VARIABLE error TIMEOUT 10)
  if(NOT rc EQUAL 2)
    message(FATAL_ERROR "${name}: expected rejection 2, got ${rc}: ${error}")
  endif()
  math(EXPR count "${negative}+1")
  set(negative "${count}" PARENT_SCOPE)
endfunction()
create_leaf(work)
create_leaf(other)
if(work STREQUAL other)
  message(FATAL_ERROR "parallel-safe leaf names are not unique")
endif()
get_filename_component(root "${work}" DIRECTORY)
file(WRITE "${work}/survivor" "untouched\n")
file(COPY_FILE "${work}/.pure-audio-owner" "${other}/sentinel-backup")
reject(empty "")
reject(volume "C:/")
reject(root "${root}")
reject(outside "${MODULE_DIR}")
reject(noncanonical "${work}/../${other}")
file(REMOVE "${work}/.pure-audio-owner")
reject(missing-sentinel "${work}")
file(WRITE "${work}/.pure-audio-owner" "wrong\n")
reject(wrong-sentinel "${work}")
file(COPY_FILE "${other}/.pure-audio-owner" "${work}/.pure-audio-owner")
reject(other-leaf-sentinel "${work}")
file(REMOVE "${work}/.pure-audio-owner")
file(MAKE_DIRECTORY "${work}/.pure-audio-owner")
reject(directory-sentinel "${work}")
execute_process(COMMAND "$ENV{SystemRoot}/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command "[IO.Directory]::Delete('${work}/.pure-audio-owner')"
  RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "cannot remove exact empty sentinel-directory fixture")
endif()
file(COPY_FILE "${other}/sentinel-backup" "${work}/.pure-audio-owner")
file(MAKE_DIRECTORY "${other}/target")
file(WRITE "${other}/target/survivor" "outside junction survives\n")
execute_process(COMMAND "$ENV{SystemRoot}/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command
  "New-Item -ItemType Junction -Path '${work}/junction' -Target '${other}/target' | Out-Null"
  RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "cannot establish cleanup junction mutation")
endif()
reject(reparse-descendant "${work}")
reject(reparse-leaf "${work}/junction")
reject(reparse-ancestor "${work}/junction/subdirectory")
if(NOT EXISTS "${work}/survivor" OR NOT EXISTS "${other}/target/survivor")
  message(FATAL_ERROR "cleanup changed files before rejecting invalid ownership/tree")
endif()
execute_process(COMMAND "$ENV{SystemRoot}/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command "[IO.Directory]::Delete('${work}/junction')"
  RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "cannot unlink exact cleanup junction")
endif()
execute_process(COMMAND "${FIXTURE}" --start-lock "${work}/.pure-audio-owner" "${other}/lock.ready"
  RESULT_VARIABLE rc OUTPUT_VARIABLE pid TIMEOUT 5)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "could not acquire concurrent ownership lock")
endif()
reject(concurrent-leaf "${work}")
execute_process(COMMAND "${FIXTURE}" --dead "${pid}" RESULT_VARIABLE rc TIMEOUT 6)
if(NOT rc EQUAL 0 OR NOT EXISTS "${work}/survivor")
  message(FATAL_ERROR "concurrent cleanup changed the active leaf")
endif()
foreach(leaf IN ITEMS "${work}" "${other}")
  execute_process(COMMAND "${RUNNER}" --cleanup --cwd "${leaf}"
    RESULT_VARIABLE rc ERROR_VARIABLE error)
  if(NOT rc EQUAL 0 OR EXISTS "${leaf}")
    message(FATAL_ERROR "valid owned leaf was not removed: ${rc}: ${error}")
  endif()
endforeach()
message(STATUS "CLEANUP_CONTRACT_OK negative=${negative} positive=2 unique_leaves=2")
if(DEFINED MAKE_EXECUTABLE AND DEFINED SH_EXECUTABLE)
  create_leaf(makework)
  file(COPY "${PURE_SOURCE_DIR}/Makefile" "${PURE_SOURCE_DIR}/Makefile.common" DESTINATION "${makework}")
  foreach(dir fftw samplerate sndfile realtime)
    file(MAKE_DIRECTORY "${makework}/${dir}")
    file(COPY "${PURE_SOURCE_DIR}/${dir}/Makefile" DESTINATION "${makework}/${dir}")
  endforeach()
  get_filename_component(shell_dir "${SH_EXECUTABLE}" DIRECTORY)
  set(ENV{PATH} "${shell_dir};$ENV{SystemRoot}/System32;$ENV{SystemRoot}")
  foreach(target clean realclean)
    foreach(path audio.dll audio.o fftw/fftw.dll samplerate/srcprocess.dll sndfile/sfinfo.dll realtime/realtime.dll)
      file(WRITE "${makework}/${path}" "owned output\n")
    endforeach()
    file(WRITE "${makework}/unrelated.dll.keep" "must survive\n")
    file(WRITE "${makework}/fftw/unrelated.dll.keep" "must survive\n")
    file(WRITE "${makework}/unrelated.o" "must survive\n")
    execute_process(COMMAND "${MAKE_EXECUTABLE}" "SHELL=${SH_EXECUTABLE}" "DLL=.dll" "${target}"
      WORKING_DIRECTORY "${makework}" RESULT_VARIABLE rc OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT rc EQUAL 0 OR EXISTS "${makework}/audio.dll" OR EXISTS "${makework}/fftw/fftw.dll" OR
       NOT EXISTS "${makework}/unrelated.dll.keep" OR NOT EXISTS "${makework}/fftw/unrelated.dll.keep" OR
       NOT EXISTS "${makework}/unrelated.o")
      message(FATAL_ERROR "Make ${target} violated exact owned outputs: ${rc}\n${output}\n${error}")
    endif()
  endforeach()
  foreach(suffix "" "." ".dll*" ".dll/..")
    execute_process(COMMAND "${MAKE_EXECUTABLE}" "SHELL=${SH_EXECUTABLE}" "DLL=${suffix}" clean
      WORKING_DIRECTORY "${makework}" RESULT_VARIABLE rc OUTPUT_QUIET ERROR_QUIET)
    if(rc EQUAL 0)
      message(FATAL_ERROR "Make clean accepted unsafe suffix '${suffix}'")
    endif()
  endforeach()
  execute_process(COMMAND "${RUNNER}" --cleanup --cwd "${makework}" RESULT_VARIABLE rc)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Make contract cleanup failed")
  endif()
  message(STATUS "MAKE_CLEAN_CONTRACT_OK negative=4 positive=2")
endif()
