# Exercises the launcher's observable behavior, using real Pure for language
# errors and a native child for pipe saturation and surviving descendants.
# Inspect generated commands/properties, not CMake source spelling. The optional
# expected value lets independent normal/ASan runs pin the selected branch.
get_filename_component(cmake_bin "${CMAKE_COMMAND}" DIRECTORY)
execute_process(COMMAND "${cmake_bin}/ctest.exe" --test-dir "${MODULE_DIR}"
  --show-only=json-v1 RESULT_VARIABLE inventory_rc OUTPUT_VARIABLE inventory
  ERROR_VARIABLE inventory_error TIMEOUT 15)
if(NOT inventory_rc EQUAL 0)
  message(FATAL_ERROR "Cannot inspect timeout contract: ${inventory_error}")
endif()
string(JSON test_count LENGTH "${inventory}" tests)
if(test_count LESS 6)
  message(FATAL_ERROR "Timeout contract requires the nonempty six-test core inventory")
endif()
math(EXPR last_test "${test_count}-1")
set(timeout_checks 0)
set(required_timeout_tests pure-audio-fault-bounds pure-audio-load
  pure-audio-processing pure-audio-public-bounds pure-audio-runner-contract
  pure-audio-cleanup-contract)
foreach(index RANGE 0 ${last_test})
  string(JSON name GET "${inventory}" tests ${index} name)
  list(REMOVE_ITEM required_timeout_tests "${name}")
  string(JSON command GET "${inventory}" tests ${index} command)
  string(JSON argc LENGTH "${command}")
  math(EXPR last_arg "${argc}-1")
  unset(inner_argument)
  foreach(arg RANGE 0 ${last_arg})
    string(JSON value GET "${command}" ${arg})
    if(value MATCHES "^-DTEST_TIMEOUT=")
      if(DEFINED inner_argument)
        message(FATAL_ERROR "Duplicate inner timeout for ${name}")
      endif()
      set(inner_argument "${value}")
    endif()
  endforeach()
  string(JSON properties GET "${inventory}" tests ${index} properties)
  string(JSON property_count LENGTH "${properties}")
  math(EXPR last_property "${property_count}-1")
  unset(actual_timeout)
  foreach(property RANGE 0 ${last_property})
    string(JSON property_name GET "${properties}" ${property} name)
    if(property_name STREQUAL "TIMEOUT")
      string(JSON actual_timeout GET "${properties}" ${property} value)
    endif()
  endforeach()
  if(name STREQUAL "pure-audio-public-bounds")
    if(inner_argument STREQUAL "-DTEST_TIMEOUT=90000")
      set(inner 90000)
      set(expected_timeout 105)
    elseif(inner_argument STREQUAL "-DTEST_TIMEOUT=45000")
      set(inner 45000)
      set(expected_timeout 60)
    else()
      message(FATAL_ERROR "Unexpected public bounds inner timeout: ${command}")
    endif()
    if(DEFINED EXPECT_PUBLIC_BOUNDS_TIMEOUT AND
        NOT inner EQUAL EXPECT_PUBLIC_BOUNDS_TIMEOUT)
      message(FATAL_ERROR "Public bounds timeout ${inner}, expected ${EXPECT_PUBLIC_BOUNDS_TIMEOUT}")
    endif()
  else()
    if(DEFINED inner_argument)
      message(FATAL_ERROR "Public bounds timeout leaked to ${name}")
    endif()
    if(name STREQUAL "pure-audio-load")
      set(expected_timeout 45)
    elseif(name STREQUAL "pure-audio-processing")
      set(expected_timeout 60)
    elseif(name MATCHES "^pure-audio-(fault-bounds|runner-contract|cleanup-contract)$")
      set(expected_timeout 90)
    elseif(name STREQUAL "pure-audio-install-contract")
      set(expected_timeout 1800)
    elseif(name STREQUAL "pure-audio-source-dist-contract")
      set(expected_timeout 3600)
    elseif(name MATCHES "^pure-audio-(install-guard|configure|runtime_verifier)-contract$")
      set(expected_timeout 600)
    else()
      message(FATAL_ERROR "Unaccounted test timeout: ${name}")
    endif()
  endif()
  if(NOT DEFINED actual_timeout OR NOT actual_timeout EQUAL expected_timeout)
    message(FATAL_ERROR "${name} timeout ${actual_timeout}, expected ${expected_timeout}")
  endif()
  math(EXPR timeout_checks "${timeout_checks}+1")
endforeach()
if(required_timeout_tests)
  message(FATAL_ERROR "Missing core timeout contracts: ${required_timeout_tests}")
endif()
file(READ "${PURE_SOURCE_DIR}/cmake/RunHardwareTest.cmake" hardware_driver)
if(NOT hardware_driver MATCHES "set\\(TEST_TIMEOUT 15000\\)")
  message(FATAL_ERROR "Hardware timeout must remain 15000 ms")
endif()
message(STATUS "TIMEOUT_CONTRACT_OK generated_tests=${timeout_checks} public_inner=${inner} hardware_ms=15000")
if(TIMEOUT_CONTRACT_ONLY)
  return()
endif()
foreach(required RUNNER FIXTURE PURE_EXECUTABLE PURE_SOURCE_DIR MODULE_DIR)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} required")
  endif()
endforeach()
if(LEGACY)
  set(work "${MODULE_DIR}/runner-red-owned")
  file(MAKE_DIRECTORY "${work}")
  set(failures 0)
  foreach(mode parser exception wrong forged duplicate nonfinal)
    file(WRITE "${work}/${mode}.pure" "// adversarial native child input\n")
    execute_process(COMMAND "${CMAKE_COMMAND}"
      "-DPURE_EXECUTABLE=${FIXTURE}" "-DPURE_SOURCE_DIR=${PURE_SOURCE_DIR}"
      "-DMODULE_DIR=${MODULE_DIR}" "-DTEST_SCRIPT=${work}/${mode}.pure"
      "-DTEST_DIRECTORY=${work}/legacy-leaf"
      -P "${PURE_SOURCE_DIR}/cmake/RunPureTest.cmake"
      RESULT_VARIABLE rc OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(rc EQUAL 0)
      math(EXPR failures "${failures}+1")
      message(STATUS "RED: legacy runner accepted ${mode}")
    endif()
  endforeach()
  message(FATAL_ERROR "${failures}/6 invalid completions were accepted")
endif()

execute_process(COMMAND "${FIXTURE}" --parent-boundaries RESULT_VARIABLE parent_result
  OUTPUT_VARIABLE parent_output ERROR_VARIABLE parent_error TIMEOUT 5)
if(NOT parent_result EQUAL 0)
  message(FATAL_ERROR "Executable-parent boundary contract failed: ${parent_result}\n${parent_error}")
endif()
string(STRIP "${parent_output}" parent_output)
message(STATUS "${parent_output}")

execute_process(COMMAND "${RUNNER}" --create-leaf RESULT_VARIABLE rc
  OUTPUT_VARIABLE work OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "create-leaf failed: ${rc}")
endif()
set(ENV{PATH} "${work}/poison")
set(ENV{PURELIB} "${work}/poison")
set(ENV{PURE_INCLUDE} "${work}/poison")
set(ENV{PURE_LIBRARY} "${work}/poison")
set(ENV{PURE_AUDIO_IN} "ambient poison")
set(ENV{PURE_AUDIO_OUT} "2147483648")
file(MAKE_DIRECTORY "${work}/poison")
file(WRITE "${work}/poison/prelude.pure" "exit 77;\n")
file(WRITE "${work}/poison/audio.pure" "exit 78;\n")
file(WRITE "${work}/poison/audio.dll" "poison module\n")
set(base --token auto --timeout 3000 --cwd "${work}")
foreach(entry IN LISTS RUNTIME_DIRS)
  list(APPEND base --path-entry "${entry}")
endforeach()
set(failures 0)
set(negative 0)
set(positive 0)
function(run_case name expected)
  execute_process(COMMAND "${RUNNER}" ${base} ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 45)
  if(NOT "${result}" STREQUAL "${expected}")
    math(EXPR failures "${failures}+1")
    set(failures "${failures}" PARENT_SCOPE)
    message(STATUS "FAIL ${name}: expected ${expected}, got ${result}\n${output}\n${error}")
  endif()
endfunction()
foreach(mode pristine environment directory-lock parser exception wrong forged duplicate nonfinal exit37 hang inherited)
  file(WRITE "${work}/${mode}.pure" "// native fixture selector\n")
  set(expected 1)
  if(mode STREQUAL pristine OR mode STREQUAL environment OR mode STREQUAL directory-lock)
    set(expected 0)
    math(EXPR positive "${positive}+1")
  else()
    math(EXPR negative "${negative}+1")
  endif()
  if(mode STREQUAL exit37)
    set(expected 37)
  elseif(mode STREQUAL hang)
    set(expected 124)
  endif()
  run_case("${mode}" "${expected}" --pure "${FIXTURE}" --script "${work}/${mode}.pure")
endforeach()
# Selectors are explicit data, never an ambient environment allowlist.
foreach(mode selector-both selector-in selector-out)
  file(WRITE "${work}/${mode}.pure" "// explicit device transport fixture\n")
endforeach()
run_case(selectors-both 0 --pure "${FIXTURE}" --script "${work}/selector-both.pure"
  --hardware-device PURE_AUDIO_IN=7 --hardware-device PURE_AUDIO_OUT=11)
run_case(selectors-in-only 0 --pure "${FIXTURE}" --script "${work}/selector-in.pure"
  --hardware-device PURE_AUDIO_IN=0)
run_case(selectors-out-only 0 --pure "${FIXTURE}" --script "${work}/selector-out.pure"
  --hardware-device PURE_AUDIO_OUT=2147483647)
math(EXPR positive "${positive}+3")
foreach(value "PURELIB=7" "PATH=7" "pure_audio_in=7" "PURE_AUDIO_IN_EXTRA=7"
    "PURE_AUDIO_IN=" "PURE_AUDIO_IN=-1" "PURE_AUDIO_IN=+1" "PURE_AUDIO_IN=01"
    "PURE_AUDIO_IN=2147483648" "PURE_AUDIO_IN=9999999999999999999999999"
    "PURE_AUDIO_IN= 7" "PURE_AUDIO_IN=7 " "PURE_AUDIO_IN=7=8"
    "PURE_AUDIO_OUT=WASAPI:*" "PURE_AUDIO_OUT=7\nPURELIB=poison")
  run_case("bad-selector-${value}" 2 --pure "${FIXTURE}" --script "${work}/pristine.pure"
    --hardware-device "${value}")
  math(EXPR negative "${negative}+1")
endforeach()
run_case(duplicate-selector 2 --pure "${FIXTURE}" --script "${work}/pristine.pure"
  --hardware-device PURE_AUDIO_IN=7 --hardware-device PURE_AUDIO_IN=8)
math(EXPR negative "${negative}+1")
# Public CMake hardware driver transport without touching an audio device.
set(hardware_source "${work}/selector-both-source")
file(MAKE_DIRECTORY "${hardware_source}/tests")
foreach(mode playback capture)
  file(WRITE "${hardware_source}/tests/hardware-${mode}.pure" "// native selector oracle\n")
endforeach()
set(ENV{PURE_AUDIO_IN} 7)
set(ENV{PURE_AUDIO_OUT} 11)
foreach(mode playback capture)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DMODE=${mode}"
    "-DPURE_AUDIO_RUNNER=${RUNNER}" "-DPURE_EXECUTABLE=${FIXTURE}"
    "-DPURE_SOURCE_DIR=${hardware_source}" "-DMODULE_DIR=${MODULE_DIR}"
    "-DRUNTIME_DIRS=${RUNTIME_DIRS}"
    -P "${PURE_SOURCE_DIR}/cmake/RunHardwareTest.cmake"
    RESULT_VARIABLE transport OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(NOT transport EQUAL 0 OR NOT output MATCHES "HARDWARE_SELECTOR_CHILD_ENTERED")
    math(EXPR failures "${failures}+1")
    message(STATUS "FAIL hardware ${mode} explicit selector transport: ${transport}\n${output}\n${error}")
  endif()
  math(EXPR positive "${positive}+1")
endforeach()
foreach(value "-1" "2147483648" "9999999999999999999999999" "01" "7;PURELIB=poison" "7\nPURELIB=poison")
  set(ENV{PURE_AUDIO_IN} "${value}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -DMODE=playback
    "-DPURE_AUDIO_RUNNER=${RUNNER}" "-DPURE_EXECUTABLE=${FIXTURE}"
    "-DPURE_SOURCE_DIR=${hardware_source}" "-DMODULE_DIR=${MODULE_DIR}"
    "-DRUNTIME_DIRS=${RUNTIME_DIRS}"
    -P "${PURE_SOURCE_DIR}/cmake/RunHardwareTest.cmake"
    RESULT_VARIABLE transport OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
  if(transport EQUAL 0 OR "${output}${error}" MATCHES "HARDWARE_SELECTOR_CHILD_ENTERED")
    math(EXPR failures "${failures}+1")
    message(STATUS "FAIL hardware malformed selector must fail before child: ${value}")
  endif()
  math(EXPR negative "${negative}+1")
endforeach()
unset(ENV{PURE_AUDIO_IN})
unset(ENV{PURE_AUDIO_OUT})
set(hardware_absent "${work}/environment-source")
file(MAKE_DIRECTORY "${hardware_absent}/tests")
file(WRITE "${hardware_absent}/tests/hardware-playback.pure" "// absent selector oracle\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -DMODE=playback
  "-DPURE_AUDIO_RUNNER=${RUNNER}" "-DPURE_EXECUTABLE=${FIXTURE}"
  "-DPURE_SOURCE_DIR=${hardware_absent}" "-DMODULE_DIR=${MODULE_DIR}"
  "-DRUNTIME_DIRS=${RUNTIME_DIRS}"
  -P "${PURE_SOURCE_DIR}/cmake/RunHardwareTest.cmake"
  RESULT_VARIABLE transport OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
if(NOT transport EQUAL 0)
  math(EXPR failures "${failures}+1")
  message(STATUS "FAIL hardware unspecified selectors must remain absent: ${transport}\n${output}\n${error}")
endif()
math(EXPR positive "${positive}+1")
set(ENV{PURE_AUDIO_IN} "ambient poison")
set(ENV{PURE_AUDIO_OUT} "2147483648")
if(NOT EXISTS "${work}/descendant.pid")
  message(FATAL_ERROR "inherited-handle fixture did not start its descendant")
endif()
file(READ "${work}/descendant.pid" descendant)
execute_process(COMMAND "${FIXTURE}" --dead "${descendant}" RESULT_VARIABLE dead TIMEOUT 6)
if(NOT dead EQUAL 0)
  message(FATAL_ERROR "runner left a descendant alive")
endif()
foreach(mode notice near-notice)
  file(WRITE "${work}/${mode}.pure" "// native fixture selector\n")
  run_case("${mode}-unlisted" 1 --pure "${FIXTURE}" --script "${work}/${mode}.pure")
  math(EXPR negative "${negative}+1")
  if(mode STREQUAL notice)
    run_case(exact-notice 0 --pure "${FIXTURE}" --script "${work}/${mode}.pure"
      --allow-stderr "expected backend notice")
    math(EXPR positive "${positive}+1")
  else()
    run_case(near-notice 1 --pure "${FIXTURE}" --script "${work}/${mode}.pure"
      --allow-stderr "expected backend notice")
    math(EXPR negative "${negative}+1")
  endif()
endforeach()
# Actual interpreter errors: exit zero alone must never imply success.
set(base ${base} --timeout 30000)
foreach(mode real-parser real-exception real-pristine real-hardware-loader)
  if(mode STREQUAL real-parser)
    file(WRITE "${work}/${mode}.pure" "this is = ;\n")
  elseif(mode STREQUAL real-exception)
    file(WRITE "${work}/${mode}.pure" "throw \"intentional failure\";\n")
  elseif(mode STREQUAL real-hardware-loader)
    file(WRITE "${work}/${mode}.pure" "using system, hardware; puts (last argv);\n")
  else()
    file(WRITE "${work}/${mode}.pure" "using system; puts (last argv);\n")
  endif()
  set(expected 1)
  if(mode STREQUAL real-pristine OR mode STREQUAL real-hardware-loader)
    set(expected 0)
    math(EXPR positive "${positive}+1")
  else()
    math(EXPR negative "${negative}+1")
  endif()
  run_case("${mode}" "${expected}" --pure "${PURE_EXECUTABLE}" --script "${work}/${mode}.pure"
    --include "${PURE_SOURCE_DIR}" --include "${PURE_SOURCE_DIR}/tests"
    --module-dir "${MODULE_DIR}" --path-entry "${MODULE_DIR}")
endforeach()
# Explicit input validation rejects reparse endpoints and ancestors for every
# input class; the junction target contains a runnable copied child.
file(MAKE_DIRECTORY "${work}/actual")
file(COPY "${FIXTURE}" DESTINATION "${work}/actual")
get_filename_component(fixture_name "${FIXTURE}" NAME)
file(WRITE "${work}/actual/pristine.pure" "puts (last argv);\n")
file(MAKE_DIRECTORY "${work}/inputs with spaces")
file(COPY "${FIXTURE}" DESTINATION "${work}/inputs with spaces")
file(WRITE "${work}/inputs with spaces/pristine file.pure" "// native child selector\n")
run_case(paths-with-spaces 0 --pure "${work}/inputs with spaces/${fixture_name}"
  --script "${work}/inputs with spaces/pristine file.pure"
  --include "${work}/inputs with spaces" --module-dir "${work}/inputs with spaces"
  --path-entry "${work}/inputs with spaces")
math(EXPR positive "${positive}+1")
execute_process(COMMAND "$ENV{SystemRoot}/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command
  "New-Item -ItemType Junction -Path '${work}/junction' -Target '${work}/actual' | Out-Null"
  RESULT_VARIABLE junction_result)
if(NOT junction_result EQUAL 0)
  message(FATAL_ERROR "cannot establish junction mutation")
endif()
foreach(kind pure script cwd path-entry include module-dir)
  set(args --pure "${FIXTURE}" --script "${work}/pristine.pure")
  if(kind STREQUAL pure)
    set(args --pure "${work}/junction/${fixture_name}" --script "${work}/pristine.pure")
  elseif(kind STREQUAL script)
    set(args --pure "${FIXTURE}" --script "${work}/junction/pristine.pure")
  else()
    list(APPEND args "--${kind}" "${work}/junction")
  endif()
  run_case("reparse-${kind}" 2 ${args})
  math(EXPR negative "${negative}+1")
endforeach()
run_case(noncanonical 2 --pure "${FIXTURE}" --script "${work}/actual/../pristine.pure")
run_case(relative-path 2 --pure "${FIXTURE}" --script "${work}/pristine.pure" --path-entry .)
run_case(fixed-token 2 --pure "${FIXTURE}" --script "${work}/pristine.pure" --token forged)
math(EXPR negative "${negative}+3")
# Remove exactly this known junction itself, never recursively traverse it.
execute_process(COMMAND "$ENV{SystemRoot}/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command "[IO.Directory]::Delete('${work}/junction')"
  RESULT_VARIABLE unlink_result)
if(NOT unlink_result EQUAL 0)
  message(FATAL_ERROR "cannot unlink contract junction")
endif()
execute_process(COMMAND "${RUNNER}" --cleanup --cwd "${work}" RESULT_VARIABLE cleanup)
if(NOT cleanup EQUAL 0)
  message(FATAL_ERROR "contract cleanup failed")
endif()
if(failures)
  message(FATAL_ERROR "${failures} runner contract failures")
endif()
message(STATUS "RUNNER_CONTRACT_OK negative=${negative} positive=${positive} descendant_checks=1")
