# Exercises the launcher's observable behavior, using real Pure for language
# errors and a native child for pipe saturation and surviving descendants.
foreach(required RUNNER FIXTURE PURE_EXECUTABLE PURE_SOURCE_DIR MODULE_DIR)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} required")
  endif()
endforeach()
if(LEGACY)
  set(work "${MODULE_DIR}/runner-red-owned")
  file(MAKE_DIRECTORY "${work}")
  set(failures 0)
  foreach(mode parser exception wrong forged duplicate nonfinal)
    file(WRITE "${work}/${mode}.pure" "// adversarial native child input\n")
    execute_process(COMMAND "${CMAKE_COMMAND}"
      "-DPURE_EXECUTABLE=${FIXTURE}" "-DPURE_SOURCE_DIR=${PURE_SOURCE_DIR}"
      "-DMODULE_DIR=${MODULE_DIR}" "-DTEST_SCRIPT=${work}/${mode}.pure"
      "-DTEST_DIRECTORY=${work}/legacy-leaf"
      -P "${PURE_SOURCE_DIR}/cmake/RunPureTest.cmake"
      RESULT_VARIABLE rc OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(rc EQUAL 0)
      math(EXPR failures "${failures}+1")
      message(STATUS "RED: legacy runner accepted ${mode}")
    endif()
  endforeach()
  message(FATAL_ERROR "${failures}/6 invalid completions were accepted")
endif()

execute_process(COMMAND "${RUNNER}" --create-leaf RESULT_VARIABLE rc
  OUTPUT_VARIABLE work OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "create-leaf failed: ${rc}")
endif()
set(ENV{PATH} "${work}/poison")
set(ENV{PURELIB} "${work}/poison")
set(ENV{PURE_INCLUDE} "${work}/poison")
set(ENV{PURE_LIBRARY} "${work}/poison")
file(MAKE_DIRECTORY "${work}/poison")
file(WRITE "${work}/poison/prelude.pure" "exit 77;\n")
file(WRITE "${work}/poison/audio.pure" "exit 78;\n")
file(WRITE "${work}/poison/audio.dll" "poison module\n")
set(base --token auto --timeout 3000 --cwd "${work}")
foreach(entry IN LISTS RUNTIME_DIRS)
  list(APPEND base --path-entry "${entry}")
endforeach()
set(failures 0)
set(negative 0)
set(positive 0)
function(run_case name expected)
  execute_process(COMMAND "${RUNNER}" ${base} ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 45)
  if(NOT "${result}" STREQUAL "${expected}")
    math(EXPR failures "${failures}+1")
    set(failures "${failures}" PARENT_SCOPE)
    message(STATUS "FAIL ${name}: expected ${expected}, got ${result}\n${output}\n${error}")
  endif()
endfunction()
foreach(mode pristine environment directory-lock parser exception wrong forged duplicate nonfinal exit37 hang inherited)
  file(WRITE "${work}/${mode}.pure" "// native fixture selector\n")
  set(expected 1)
  if(mode STREQUAL pristine OR mode STREQUAL environment OR mode STREQUAL directory-lock)
    set(expected 0)
    math(EXPR positive "${positive}+1")
  else()
    math(EXPR negative "${negative}+1")
  endif()
  if(mode STREQUAL exit37)
    set(expected 37)
  elseif(mode STREQUAL hang)
    set(expected 124)
  endif()
  run_case("${mode}" "${expected}" --pure "${FIXTURE}" --script "${work}/${mode}.pure")
endforeach()
if(NOT EXISTS "${work}/descendant.pid")
  message(FATAL_ERROR "inherited-handle fixture did not start its descendant")
endif()
file(READ "${work}/descendant.pid" descendant)
execute_process(COMMAND "${FIXTURE}" --dead "${descendant}" RESULT_VARIABLE dead TIMEOUT 6)
if(NOT dead EQUAL 0)
  message(FATAL_ERROR "runner left a descendant alive")
endif()
foreach(mode notice near-notice)
  file(WRITE "${work}/${mode}.pure" "// native fixture selector\n")
  run_case("${mode}-unlisted" 1 --pure "${FIXTURE}" --script "${work}/${mode}.pure")
  math(EXPR negative "${negative}+1")
  if(mode STREQUAL notice)
    run_case(exact-notice 0 --pure "${FIXTURE}" --script "${work}/${mode}.pure"
      --allow-stderr "expected backend notice")
    math(EXPR positive "${positive}+1")
  else()
    run_case(near-notice 1 --pure "${FIXTURE}" --script "${work}/${mode}.pure"
      --allow-stderr "expected backend notice")
    math(EXPR negative "${negative}+1")
  endif()
endforeach()
# Actual interpreter errors: exit zero alone must never imply success.
set(base ${base} --timeout 30000)
foreach(mode real-parser real-exception real-pristine real-hardware-loader)
  if(mode STREQUAL real-parser)
    file(WRITE "${work}/${mode}.pure" "this is = ;\n")
  elseif(mode STREQUAL real-exception)
    file(WRITE "${work}/${mode}.pure" "throw \"intentional failure\";\n")
  elseif(mode STREQUAL real-hardware-loader)
    file(WRITE "${work}/${mode}.pure" "using system, hardware; puts (last argv);\n")
  else()
    file(WRITE "${work}/${mode}.pure" "using system; puts (last argv);\n")
  endif()
  set(expected 1)
  if(mode STREQUAL real-pristine OR mode STREQUAL real-hardware-loader)
    set(expected 0)
    math(EXPR positive "${positive}+1")
  else()
    math(EXPR negative "${negative}+1")
  endif()
  run_case("${mode}" "${expected}" --pure "${PURE_EXECUTABLE}" --script "${work}/${mode}.pure"
    --include "${PURE_SOURCE_DIR}" --include "${PURE_SOURCE_DIR}/tests"
    --module-dir "${MODULE_DIR}" --path-entry "${MODULE_DIR}")
endforeach()
# Explicit input validation rejects reparse endpoints and ancestors for every
# input class; the junction target contains a runnable copied child.
file(MAKE_DIRECTORY "${work}/actual")
file(COPY "${FIXTURE}" DESTINATION "${work}/actual")
get_filename_component(fixture_name "${FIXTURE}" NAME)
file(WRITE "${work}/actual/pristine.pure" "puts (last argv);\n")
file(MAKE_DIRECTORY "${work}/inputs with spaces")
file(COPY "${FIXTURE}" DESTINATION "${work}/inputs with spaces")
file(WRITE "${work}/inputs with spaces/pristine file.pure" "// native child selector\n")
run_case(paths-with-spaces 0 --pure "${work}/inputs with spaces/${fixture_name}"
  --script "${work}/inputs with spaces/pristine file.pure"
  --include "${work}/inputs with spaces" --module-dir "${work}/inputs with spaces"
  --path-entry "${work}/inputs with spaces")
math(EXPR positive "${positive}+1")
execute_process(COMMAND "$ENV{SystemRoot}/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command
  "New-Item -ItemType Junction -Path '${work}/junction' -Target '${work}/actual' | Out-Null"
  RESULT_VARIABLE junction_result)
if(NOT junction_result EQUAL 0)
  message(FATAL_ERROR "cannot establish junction mutation")
endif()
foreach(kind pure script cwd path-entry include module-dir)
  set(args --pure "${FIXTURE}" --script "${work}/pristine.pure")
  if(kind STREQUAL pure)
    set(args --pure "${work}/junction/${fixture_name}" --script "${work}/pristine.pure")
  elseif(kind STREQUAL script)
    set(args --pure "${FIXTURE}" --script "${work}/junction/pristine.pure")
  else()
    list(APPEND args "--${kind}" "${work}/junction")
  endif()
  run_case("reparse-${kind}" 2 ${args})
  math(EXPR negative "${negative}+1")
endforeach()
run_case(noncanonical 2 --pure "${FIXTURE}" --script "${work}/actual/../pristine.pure")
run_case(relative-path 2 --pure "${FIXTURE}" --script "${work}/pristine.pure" --path-entry .)
run_case(fixed-token 2 --pure "${FIXTURE}" --script "${work}/pristine.pure" --token forged)
math(EXPR negative "${negative}+3")
# Remove exactly this known junction itself, never recursively traverse it.
execute_process(COMMAND "$ENV{SystemRoot}/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command "[IO.Directory]::Delete('${work}/junction')"
  RESULT_VARIABLE unlink_result)
if(NOT unlink_result EQUAL 0)
  message(FATAL_ERROR "cannot unlink contract junction")
endif()
execute_process(COMMAND "${RUNNER}" --cleanup --cwd "${work}" RESULT_VARIABLE cleanup)
if(NOT cleanup EQUAL 0)
  message(FATAL_ERROR "contract cleanup failed")
endif()
if(failures)
  message(FATAL_ERROR "${failures} runner contract failures")
endif()
message(STATUS "RUNNER_CONTRACT_OK negative=${negative} positive=${positive} descendant_checks=1")
