include(ExternalProject)

set(LIBLO_VERSION "0.36")
set(LIBLO_ARCHIVE_URL
  "https://github.com/radarsat1/liblo/releases/download/${LIBLO_VERSION}/liblo-${LIBLO_VERSION}.tar.gz")
set(LIBLO_ARCHIVE_SHA256
  "c08d14832e8dcf8f06840405824a4f9611a0cb3daed0198946326c740941c8b6")
set(LIBLO_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/liblo-prefix")
set(LIBLO_INCLUDE_DIR "${LIBLO_PREFIX}/include")
set(LIBLO_RUNTIME_DLL "${LIBLO_PREFIX}/bin/liblo.dll")
set(LIBLO_IMPORT_LIBRARY "${LIBLO_PREFIX}/lib/liblo.dll.a")
file(MAKE_DIRECTORY "${LIBLO_INCLUDE_DIR}")

ExternalProject_Add(liblo-external
  URL "${LIBLO_ARCHIVE_URL}"
  URL_HASH "SHA256=${LIBLO_ARCHIVE_SHA256}"
  DOWNLOAD_EXTRACT_TIMESTAMP TRUE
  SOURCE_SUBDIR cmake
  CMAKE_GENERATOR "${CMAKE_GENERATOR}"
  CMAKE_ARGS
    "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
    "-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}"
    "-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>"
    -DWITH_TOOLS=OFF
    -DWITH_TESTS=OFF
    -DWITH_EXAMPLES=OFF
    -DWITH_CPP_TESTS=OFF
    -DWITH_STATIC=OFF
    -DTHREADING=ON
  INSTALL_DIR "${LIBLO_PREFIX}"
  BUILD_BYPRODUCTS
    "${LIBLO_RUNTIME_DLL}"
    "${LIBLO_IMPORT_LIBRARY}")

ExternalProject_Get_Property(liblo-external SOURCE_DIR)
set(LIBLO_LICENSE_FILE "${SOURCE_DIR}/COPYING")

add_library(liblo::liblo SHARED IMPORTED GLOBAL)
set_target_properties(liblo::liblo PROPERTIES
  IMPORTED_LOCATION "${LIBLO_RUNTIME_DLL}"
  IMPORTED_IMPLIB "${LIBLO_IMPORT_LIBRARY}"
  INTERFACE_INCLUDE_DIRECTORIES "${LIBLO_INCLUDE_DIR}")
add_dependencies(liblo::liblo liblo-external)
