cmake_minimum_required(VERSION 3.25)

foreach(required DIST_SOURCE_ROOT DIST_ARCHIVE_BASENAME DIST_FILES)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()
if(NOT DIST_ARCHIVE_BASENAME STREQUAL "pure-audio-0.6")
  message(FATAL_ERROR "Source archive requires the declared pure-audio-0.6 basename")
endif()
get_filename_component(root "${DIST_SOURCE_ROOT}" ABSOLUTE)
if(NOT DEFINED DIST_OUTPUT_DIRECTORY OR DIST_OUTPUT_DIRECTORY STREQUAL "")
  set(DIST_OUTPUT_DIRECTORY "${root}")
endif()
get_filename_component(output_dir "${DIST_OUTPUT_DIRECTORY}" ABSOLUTE)
set(destination "${output_dir}/${DIST_ARCHIVE_BASENAME}.tar.gz")
string(STRIP "${DIST_FILES}" names)
string(REGEX REPLACE "[ \t\r\n]+" ";" names "${names}")
set(unique ${names})
list(REMOVE_DUPLICATES unique)
if(NOT unique STREQUAL names)
  message(FATAL_ERROR "Duplicate source archive input")
endif()
list(SORT names)
foreach(name IN LISTS names)
  if(NOT name MATCHES "^[A-Za-z0-9_+./-]+$" OR name MATCHES "^/|(^|/)\.\.(/|$)")
    message(FATAL_ERROR "Malformed source archive input: ${name}")
  endif()
endforeach()
if(NOT DEFINED DIST_TAR OR DIST_TAR STREQUAL "")
  set(DIST_TAR tar)
endif()
if(IS_ABSOLUTE "${DIST_TAR}")
  get_filename_component(tar "${DIST_TAR}" ABSOLUTE)
else()
  find_program(tar NAMES "${DIST_TAR}" REQUIRED)
endif()
get_filename_component(tool_dir "${tar}" DIRECTORY)
find_program(gzip NAMES gzip HINTS "${tool_dir}" NO_DEFAULT_PATH REQUIRED)

function(archive_posix_path path kind)
  if(kind STREQUAL "file")
    execute_process(COMMAND test -f "${path}" RESULT_VARIABLE regular)
    if(NOT regular EQUAL 0)
      message(FATAL_ERROR "Expected regular source/archive input: ${path}")
    endif()
  elseif(NOT IS_DIRECTORY "${path}")
    message(FATAL_ERROR "Expected archive directory: ${path}")
  endif()
  while(NOT path STREQUAL "")
    if(IS_SYMLINK "${path}")
      message(FATAL_ERROR "Source/archive reparse component: ${path}")
    endif()
    get_filename_component(parent "${path}" DIRECTORY)
    if(parent STREQUAL path)
      break()
    endif()
    set(path "${parent}")
  endwhile()
endfunction()

if(CMAKE_HOST_WIN32)
  cmake_host_system_information(RESULT windows_root QUERY WINDOWS_REGISTRY
    "HKLM/SOFTWARE/Microsoft/Windows NT/CurrentVersion" VALUE SystemRoot)
  set(powershell "${windows_root}/System32/WindowsPowerShell/v1.0/powershell.exe")
  set(helper "${CMAKE_CURRENT_LIST_DIR}/SourceArchiveTools.ps1")
  list(JOIN names "|" joined)
  execute_process(COMMAND "${powershell}" -NoProfile -NonInteractive -ExecutionPolicy Bypass
    -File "${helper}" -Mode Validate -Root "${root}" -Directory "${output_dir}"
    -Destination "${destination}" -Names "${joined}" -Tools "${tar}|${gzip}|${CMAKE_COMMAND}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Archive preflight failed: ${rc}\n${out}${err}")
  endif()
else()
  archive_posix_path("${root}" directory)
  archive_posix_path("${output_dir}" directory)
  foreach(name IN LISTS names)
    archive_posix_path("${root}/${name}" file)
  endforeach()
  foreach(tool "${tar}" "${gzip}")
    archive_posix_path("${tool}" file)
  endforeach()
  if(EXISTS "${destination}" OR IS_SYMLINK "${destination}")
    message(FATAL_ERROR "Archive destination already exists (no overwrite)")
  endif()
endif()
# GNU archive tools accept ambient option variables, including destructive tar
# --remove-files. Clear both variables for every tool subprocess, while keeping
# tool paths and command arguments explicitly declared above.
set(archive_environment "${CMAKE_COMMAND}" -E env --unset=TAR_OPTIONS --unset=GZIP)
execute_process(COMMAND ${archive_environment} "${tar}" --version RESULT_VARIABLE rc OUTPUT_VARIABLE version ERROR_VARIABLE err TIMEOUT 10)
if(NOT rc EQUAL 0 OR NOT version MATCHES "GNU tar")
  message(FATAL_ERROR "The source archive requires GNU tar: ${version}${err}")
endif()
function(reserve_archive_file result)
if(CMAKE_HOST_WIN32)
  execute_process(COMMAND "${powershell}" -NoProfile -NonInteractive -ExecutionPolicy Bypass
    -File "${helper}" -Mode Reserve -Directory "${output_dir}" -Destination "${destination}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE temporary ERROR_VARIABLE err OUTPUT_STRIP_TRAILING_WHITESPACE TIMEOUT 10)
else()
  execute_process(COMMAND mktemp "${output_dir}/.pure-audio-dist-XXXXXXXX.tmp"
    RESULT_VARIABLE rc OUTPUT_VARIABLE temporary ERROR_VARIABLE err OUTPUT_STRIP_TRAILING_WHITESPACE TIMEOUT 10)
endif()
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot reserve unique source archive: ${err}")
endif()
set(${result} "${temporary}" PARENT_SCOPE)
endfunction()
reserve_archive_file(temporary)
reserve_archive_file(raw)
# No directory inputs, staging tree, symlink dereference, or recursive cleanup.
# gzip receives a pipe and -n, so its header records no source name/timestamp.
set(data_names ${names})
list(REMOVE_ITEM data_names debian/rules)
execute_process(COMMAND ${archive_environment} "${tar}" --force-local --create --format=ustar "--file=${raw}" --no-recursion
  --mtime=@0 --owner=0 --group=0 --numeric-owner --mode=0644
  "--transform=s,^,${DIST_ARCHIVE_BASENAME}/," -- ${data_names}
  WORKING_DIRECTORY "${root}" RESULT_VARIABLE rc ERROR_VARIABLE err TIMEOUT 90)
if(rc EQUAL 0 AND "debian/rules" IN_LIST names)
  execute_process(COMMAND ${archive_environment} "${tar}" --force-local --append --format=ustar "--file=${raw}" --no-recursion
    --mtime=@0 --owner=0 --group=0 --numeric-owner --mode=0755
    "--transform=s,^,${DIST_ARCHIVE_BASENAME}/," -- debian/rules
    WORKING_DIRECTORY "${root}" RESULT_VARIABLE rc ERROR_VARIABLE err TIMEOUT 30)
endif()
if(rc EQUAL 0)
  execute_process(COMMAND ${archive_environment} "${gzip}" -n -9 INPUT_FILE "${raw}"
    OUTPUT_FILE "${temporary}" RESULT_VARIABLE rc ERROR_VARIABLE err TIMEOUT 90)
endif()
file(REMOVE "${raw}")
if(NOT rc EQUAL 0)
  file(REMOVE "${temporary}")
  message(FATAL_ERROR "Source archive creation failed: ${rc}\n${err}")
endif()
if(CMAKE_HOST_WIN32)
  execute_process(COMMAND "${powershell}" -NoProfile -NonInteractive -ExecutionPolicy Bypass
    -File "${helper}" -Mode Publish -Directory "${output_dir}"
    -Temporary "${temporary}" -Destination "${destination}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 10)
else()
  archive_posix_path("${output_dir}" directory)
  file(RENAME "${temporary}" "${destination}" NO_REPLACE RESULT rc)
endif()
if(NOT rc STREQUAL "0")
  file(REMOVE "${temporary}")
  message(FATAL_ERROR "No-overwrite source archive publication failed: ${rc}\n${err}")
endif()
file(SHA256 "${destination}" hash)
list(LENGTH names count)
message(STATUS "SOURCE_ARCHIVE_OK files=${count} sha256=${hash} archive=${destination}")
