if(NOT MODE STREQUAL "playback" AND NOT MODE STREQUAL "capture")
  message(FATAL_ERROR "MODE must be playback or capture")
endif()
set(TEST_SCRIPT "${PURE_SOURCE_DIR}/tests/hardware-${MODE}.pure")
set(TEST_TIMEOUT 15000)
include("${CMAKE_CURRENT_LIST_DIR}/RunPureTest.cmake")
