cmake_minimum_required(VERSION 3.25)
function(source_workflow_debuild_flags output)
  if(DEFINED DEBUILD_FLAGS)
    set(text "${DEBUILD_FLAGS}")
  else()
    set(text "$ENV{DEBUILD_FLAGS}")
  endif()
  separate_arguments(flags UNIX_COMMAND "${text}")
  set(${output} "${flags}" PARENT_SCOPE)
endfunction()
function(source_workflow_validate_leaf root leaf)
  get_filename_component(expected_parent "${root}" ABSOLUTE)
  get_filename_component(actual_leaf "${leaf}" ABSOLUTE)
  get_filename_component(parent "${actual_leaf}" DIRECTORY)
  get_filename_component(name "${actual_leaf}" NAME)
  if(NOT parent STREQUAL expected_parent OR NOT name MATCHES "^run-[A-Za-z0-9]+$")
    message(FATAL_ERROR "Owned workflow leaf has wrong literal parent/name")
  endif()
endfunction()
if(NOT MODE MATCHES "^(distcheck|diffs|deb)$" OR NOT DIST_ARCHIVE_BASENAME STREQUAL "pure-audio-0.6")
  message(FATAL_ERROR "Package workflow requires the literal pure-audio-0.6 release and declared mode")
endif()
if(CMAKE_HOST_WIN32)
  if(NOT MODE STREQUAL "distcheck")
    message(FATAL_ERROR "${MODE} requires the POSIX pure-gen/Debian toolchain; use make dist, then run this target in a POSIX checkout with pure-gen or debuild installed. No source or package tree was changed.")
  endif()
  if(NOT IS_ABSOLUTE "${DIST_AUDIT_BUILD}" OR NOT EXISTS "${DIST_AUDIT_BUILD}/CTestTestfile.cmake")
    message(FATAL_ERROR "Windows distcheck requires DIST_AUDIT_BUILD=<strict configured and built directory>; its source-dist contract performs archive/extracted-source configure, build, PE, tests and install. Standalone make dist needs no build.")
  endif()
  # The registered contract owns every leaf, and uses the extracted runner for
  # nested contracts. Do not implement a second extraction/cleanup path here.
  file(READ "${DIST_AUDIT_BUILD}/CTestTestfile.cmake" tests)
  if(NOT tests MATCHES "add_test\\(\\[=\\[pure-audio-source-dist-contract\\]=\\]" AND
      NOT tests MATCHES "add_test\\(\"?pure-audio-source-dist-contract")
    message(FATAL_ERROR "DIST_AUDIT_BUILD does not register pure-audio-source-dist-contract; reconfigure the current sources with strict auditing enabled")
  endif()
  get_filename_component(tool_dir "${CMAKE_COMMAND}" DIRECTORY)
  execute_process(COMMAND "${tool_dir}/ctest.exe" --test-dir "${DIST_AUDIT_BUILD}"
    -R "^pure-audio-source-dist-contract$" --output-on-failure RESULT_VARIABLE rc)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Audited extracted-source distcheck failed: ${rc}")
  endif()
  return()
endif()

# POSIX legacy workflows: fixed root, atomically unique leaf, exact ownership
# sentinel and preflighted enumerated cleanup. Never rm -rf a caller name.
find_program(make NAMES "${DIST_MAKE}" make REQUIRED)
if(MODE STREQUAL "diffs")
  find_program(generator NAMES pure-gen)
  if(NOT generator)
    message(FATAL_ERROR "diffs requires pure-gen and PortAudio/libsamplerate/libsndfile development headers; install them, then retry. No tree was changed.")
  endif()
elseif(MODE STREQUAL "deb")
  find_program(debuild NAMES debuild)
  if(NOT debuild OR NOT IS_ABSOLUTE "${DIST_DEBIAN_ORIG}" OR NOT EXISTS "${DIST_DEBIAN_ORIG}")
    message(FATAL_ERROR "deb requires debuild plus DIST_DEBIAN_ORIG=<absolute authoritative pure-audio_0.6.orig.tar.gz>. Obtain and verify that upstream input explicitly; this target never downloads it.")
  endif()
endif()
function(workflow_path path)
  while(NOT path STREQUAL "")
    if(IS_SYMLINK "${path}")
      message(FATAL_ERROR "Package workflow refuses a symlink component: ${path}")
    endif()
    get_filename_component(parent "${path}" DIRECTORY)
    if(parent STREQUAL path)
      break()
    endif()
    set(path "${parent}")
  endwhile()
endfunction()
get_filename_component(source "${DIST_SOURCE_ROOT}" ABSOLUTE)
workflow_path("${source}")
if(NOT IS_DIRECTORY "${source}")
  message(FATAL_ERROR "Package source is not a directory")
endif()
set(root "${source}/.pure-audio-source-workflows")
workflow_path("${root}")
file(MAKE_DIRECTORY "${root}")
execute_process(COMMAND mktemp -d "${root}/run-XXXXXXXXXXXX" RESULT_VARIABLE rc
  OUTPUT_VARIABLE leaf OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot create owned workflow leaf: ${err}")
endif()
source_workflow_validate_leaf("${root}" "${leaf}")
string(RANDOM LENGTH 48 ALPHABET 0123456789abcdef nonce)
set(sentinel "pure-audio-source-workflow-v1\n${leaf}\n${nonce}\n")
file(WRITE "${leaf}/.owner" "${sentinel}")
function(workflow_cleanup)
  workflow_path("${leaf}")
  file(READ "${leaf}/.owner" actual)
  if(NOT actual STREQUAL sentinel)
    message(FATAL_ERROR "Refusing cleanup: source workflow ownership mismatch")
  endif()
  file(GLOB_RECURSE entries LIST_DIRECTORIES TRUE "${leaf}/*" "${leaf}/.*")
  list(SORT entries ORDER DESCENDING)
  # Complete validation precedes deletion, including empty symlink endpoints.
  foreach(entry IN LISTS entries)
    workflow_path("${entry}")
    if(NOT IS_DIRECTORY "${entry}")
      execute_process(COMMAND test -f "${entry}" RESULT_VARIABLE regular)
      if(NOT regular EQUAL 0)
        message(FATAL_ERROR "Refusing cleanup: nonregular workflow entry")
      endif()
    endif()
  endforeach()
  foreach(entry IN LISTS entries)
    if(IS_DIRECTORY "${entry}")
      execute_process(COMMAND rmdir -- "${entry}" RESULT_VARIABLE removed)
      if(NOT removed EQUAL 0)
        message(FATAL_ERROR "Owned workflow directory not empty; retained")
      endif()
    else()
      file(REMOVE "${entry}")
    endif()
  endforeach()
  execute_process(COMMAND rmdir -- "${leaf}" RESULT_VARIABLE removed)
  if(NOT removed EQUAL 0)
    message(FATAL_ERROR "Owned workflow leaf not empty; retained")
  endif()
endfunction()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DDIST_SOURCE_ROOT=${source}"
  "-DDIST_OUTPUT_DIRECTORY=${leaf}" "-DDIST_ARCHIVE_BASENAME=${DIST_ARCHIVE_BASENAME}"
  "-DDIST_FILES=${DIST_FILES}" "-DDIST_TAR=${DIST_TAR}"
  -P "${CMAKE_CURRENT_LIST_DIR}/CreateSourceArchive.cmake" RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  workflow_cleanup()
  message(FATAL_ERROR "Source workflow archive failed")
endif()
file(ARCHIVE_EXTRACT INPUT "${leaf}/pure-audio-0.6.tar.gz" DESTINATION "${leaf}/original")
set(tree "${leaf}/original/pure-audio-0.6")
if(MODE STREQUAL "diffs")
  file(ARCHIVE_EXTRACT INPUT "${leaf}/pure-audio-0.6.tar.gz" DESTINATION "${leaf}/generated")
  execute_process(COMMAND "${make}" generate WORKING_DIRECTORY "${leaf}/generated/pure-audio-0.6" RESULT_VARIABLE rc)
  if(rc EQUAL 0)
    execute_process(COMMAND diff -ru "${tree}" "${leaf}/generated/pure-audio-0.6" RESULT_VARIABLE difference)
    if(NOT difference MATCHES "^[01]$")
      set(rc "${difference}")
    endif()
  endif()
elseif(MODE STREQUAL "distcheck")
  execute_process(COMMAND "${make}" WORKING_DIRECTORY "${tree}" RESULT_VARIABLE rc)
  if(rc EQUAL 0)
    execute_process(COMMAND "${make}" install "DESTDIR=${leaf}/installed" WORKING_DIRECTORY "${tree}" RESULT_VARIABLE rc)
  endif()
else()
  workflow_path("${DIST_DEBIAN_ORIG}")
  file(COPY_FILE "${DIST_DEBIAN_ORIG}" "${leaf}/original/pure-audio_0.6.orig.tar.gz")
  source_workflow_debuild_flags(debuild_flags)
  execute_process(COMMAND "${debuild}" ${debuild_flags} WORKING_DIRECTORY "${tree}" RESULT_VARIABLE rc)
  # Successful Debian artifacts are intentionally retained under their unique
  # owned leaf. Never delete source or outputs in a shared caller directory.
  if(rc EQUAL 0)
    message(STATUS "Debian artifacts retained in ${leaf}; ownership sentinel .owner")
    return()
  endif()
endif()
workflow_cleanup()
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "${MODE} failed: ${rc}; owned temporary leaf cleaned")
endif()
