cmake_minimum_required(VERSION 3.25)

# The context is trusted configure output. All inventory/session files below
# are strictly parsed data, never included as executable CMake.
if(NOT DEFINED AUDIO_INSTALL_CONTEXT OR NOT EXISTS "${AUDIO_INSTALL_CONTEXT}")
  message(FATAL_ERROR "AUDIO_INSTALL_CONTEXT from the strict build is required")
endif()
# Use the adjacent audited helper and registered Windows authority before
# including executable context. A redirected context must never run first.
set(PURE_AUDIO_VERIFIER_HELPERS_ONLY ON)
include("${CMAKE_CURRENT_LIST_DIR}/VerifyWindowsDependencies.cmake")
unset(PURE_AUDIO_VERIFIER_HELPERS_ONLY)
cmake_host_system_information(RESULT install_windows_root QUERY WINDOWS_REGISTRY
  "HKLM/SOFTWARE/Microsoft/Windows NT/CurrentVersion" VALUE SystemRoot)
set(PURE_AUDIO_WINDOWS_SYSTEM_DIRECTORY "${install_windows_root}/System32")
audio_windows_authority()
audio_path("${AUDIO_INSTALL_CONTEXT}" file AUDIO_INSTALL_CONTEXT)
audio_no_reparse("${AUDIO_INSTALL_CONTEXT}")
include("${AUDIO_INSTALL_CONTEXT}")
if(NOT DEFINED AUDIO_INSTALL_MODE)
  set(AUDIO_INSTALL_MODE verify)
endif()
if(NOT AUDIO_INSTALL_MODE MATCHES "^(seal|install|verify)$")
  message(FATAL_ERROR "Unknown install verification mode")
endif()
audio_windows_authority()

function(install_relative path)
  if(NOT path MATCHES "^[A-Za-z0-9_+.-]+(/[A-Za-z0-9_+.-]+)*$" OR
      path MATCHES "(^|/)\\.\\.?(/|$)" OR path MATCHES "[.](/|$)")
    message(FATAL_ERROR "install audit: malformed relative path ${path}")
  endif()
endfunction()
function(install_rows text output)
  if(text MATCHES "[;\r]" OR NOT text MATCHES "\n$")
    message(FATAL_ERROR "install audit: malformed record stream")
  endif()
  string(REGEX REPLACE "\n$" "" text "${text}")
  string(REPLACE "\n" ";" rows "${text}")
  set(${output} "${rows}" PARENT_SCOPE)
endfunction()
function(install_tree root output)
  audio_path("${root}" directory root)
  audio_no_reparse("${root}")
  file(GLOB_RECURSE paths LIST_DIRECTORIES TRUE RELATIVE "${root}" "${root}/*")
  list(SORT paths)
  set(absolute)
  set(seen)
  foreach(path IN LISTS paths)
    install_relative("${path}")
    string(TOLOWER "${path}" folded)
    if(folded IN_LIST seen)
      message(FATAL_ERROR "install audit: case-ambiguous tree path ${path}")
    endif()
    list(APPEND seen "${folded}")
    list(APPEND absolute "${root}/${path}")
  endforeach()
  # CMP0009 forbids traversal through links; reject every reparse attribute and
  # ancestor before hashing (including directory endpoints and empty junctions).
  if(absolute)
    audio_no_reparse(${absolute})
  endif()
  set(rows)
  foreach(path IN LISTS paths)
    if(NOT IS_DIRECTORY "${root}/${path}")
      file(SHA256 "${root}/${path}" hash)
      list(APPEND rows "${path}|${hash}")
    endif()
  endforeach()
  set(${output} "${rows}" PARENT_SCOPE)
endfunction()
function(install_write_rows path rows)
  list(JOIN rows "\n" content)
  if(rows)
    string(APPEND content "\n")
  endif()
  install_guard_operation(--write "${path}" "${content}")
endfunction()
function(install_guard_operation operation)
  if(operation STREQUAL "--write")
    # Unquoted list expansion drops an empty manifest argument. Preserve the
    # empty byte stream for a fully identical, legitimately zero-delta stage.
    execute_process(COMMAND "${AUDIO_INSTALL_GUARD}" "${operation}" "${ARGV1}" "${ARGV2}"
      RESULT_VARIABLE rc TIMEOUT 40)
  else()
    execute_process(COMMAND "${AUDIO_INSTALL_GUARD}" ${ARGV}
      RESULT_VARIABLE rc TIMEOUT 40)
  endif()
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "install audit: guarded operation failed (${rc})")
  endif()
endfunction()
function(install_read_tree path output)
  file(READ "${path}" content)
  if(content STREQUAL "")
    set(${output} "" PARENT_SCOPE)
    return()
  endif()
  install_rows("${content}" rows)
  set(seen)
  foreach(row IN LISTS rows)
    string(REPLACE "|" ";" fields "${row}")
    list(LENGTH fields count)
    if(NOT count EQUAL 2)
      message(FATAL_ERROR "install audit: malformed tree manifest ${path}")
    endif()
    list(GET fields 0 name)
    list(GET fields 1 hash)
    install_relative("${name}")
    string(LENGTH "${hash}" length)
    string(TOLOWER "${name}" lower)
    if(lower IN_LIST seen OR NOT hash MATCHES "^[a-f0-9]+$" OR NOT length EQUAL 64)
      message(FATAL_ERROR "install audit: duplicate/malformed tree manifest ${path}")
    endif()
    list(APPEND seen "${lower}")
  endforeach()
  set(sorted "${rows}")
  list(SORT sorted)
  if(NOT sorted STREQUAL rows)
    message(FATAL_ERROR "install audit: unsorted tree manifest ${path}")
  endif()
  set(${output} "${rows}" PARENT_SCOPE)
endfunction()

install_rows("${AUDIO_INSTALL_POLICY}" policy)
set(sealed)
set(destinations)
set(sources "${AUDIO_INSTALL_CONTEXT}")
foreach(row IN LISTS policy)
  string(REPLACE "|" ";" fields "${row}")
  list(LENGTH fields count)
  if(NOT count EQUAL 9)
    message(FATAL_ERROR "install audit: malformed artifact policy")
  endif()
  list(GET fields 0 component)
  list(GET fields 1 destination)
  list(GET fields 2 source)
  list(GET fields 3 expected)
  list(GET fields 8 mappings)
  install_relative("${destination}")
  string(TOLOWER "${destination}" lower)
  if(lower IN_LIST destinations OR NOT component MATCHES "^(runtime|documentation|baseline)$" OR mappings STREQUAL "")
    message(FATAL_ERROR "install audit: duplicate destination, component or license mapping")
  endif()
  list(APPEND destinations "${lower}")
  audio_path("${source}" file source)
  list(APPEND sources "${source}")
  file(SHA256 "${source}" hash)
  if(NOT expected STREQUAL "BUILD" AND NOT hash STREQUAL expected)
    message(FATAL_ERROR "install audit: configured source hash mismatch: ${source}")
  endif()
  list(REMOVE_AT fields 3)
  list(INSERT fields 3 "${hash}")
  list(JOIN fields "|" row)
  list(APPEND sealed "${row}")
endforeach()
audio_no_reparse(${sources})
list(SORT sealed)
list(JOIN sealed "\n" inventory)
string(APPEND inventory "\n")
string(SHA256 inventory_hash "${inventory}")
if(AUDIO_INSTALL_MODE STREQUAL "seal" AND NOT EXISTS "${AUDIO_INSTALL_INVENTORY}" AND
    NOT EXISTS "${AUDIO_INSTALL_INVENTORY}.sha256")
  file(WRITE "${AUDIO_INSTALL_INVENTORY}" "${inventory}")
  file(WRITE "${AUDIO_INSTALL_INVENTORY}.sha256" "${inventory_hash}\n")
endif()
foreach(path "${AUDIO_INSTALL_INVENTORY}" "${AUDIO_INSTALL_INVENTORY}.sha256")
  audio_path("${path}" file unused)
endforeach()
audio_no_reparse("${AUDIO_INSTALL_INVENTORY}" "${AUDIO_INSTALL_INVENTORY}.sha256")
file(READ "${AUDIO_INSTALL_INVENTORY}" recorded)
file(READ "${AUDIO_INSTALL_INVENTORY}.sha256" pin)
if(NOT recorded STREQUAL inventory OR NOT pin STREQUAL "${inventory_hash}\n")
  message(FATAL_ERROR "install audit: frozen artifact inventory/source mismatch; use a fresh build for changed inputs")
endif()
# Every mapping must name a declared documentation payload, with the same
# project/license identity as its binary (the own-package COPYING is shared).
foreach(row IN LISTS sealed)
  string(REPLACE "|" ";" fields "${row}")
  list(GET fields 4 project)
  list(GET fields 7 license)
  list(GET fields 8 mappings)
  string(REPLACE "," ";" mappings "${mappings}")
  foreach(mapping IN LISTS mappings)
    set(found FALSE)
    foreach(candidate IN LISTS sealed)
      string(REPLACE "|" ";" c "${candidate}")
      list(GET c 0 cc)
      list(GET c 1 cd)
      list(GET c 4 cp)
      list(GET c 7 cl)
      if(cd STREQUAL mapping AND cc STREQUAL "documentation" AND cp STREQUAL project AND cl STREQUAL license)
        set(found TRUE)
      endif()
    endforeach()
    if(NOT found)
      message(FATAL_ERROR "install audit: runtime-to-license mismatch: ${mapping}")
    endif()
  endforeach()
endforeach()
if(AUDIO_INSTALL_MODE STREQUAL "seal")
  file(SHA256 "${AUDIO_INSTALL_GUARD}" guard_hash)
  if(NOT EXISTS "${AUDIO_INSTALL_BUILD_DIR}/install-guard.sha256")
    file(WRITE "${AUDIO_INSTALL_BUILD_DIR}/install-guard.sha256" "${guard_hash}\n")
  endif()
  file(READ "${AUDIO_INSTALL_BUILD_DIR}/install-guard.sha256" guard_pin)
  if(NOT guard_pin STREQUAL "${guard_hash}\n")
    message(FATAL_ERROR "install audit: frozen native guard changed; use a fresh build")
  endif()
  message(STATUS "Sealed 74 artifact records: runtime=22 documentation=39 baseline=13")
  return()
endif()
if(NOT DEFINED STAGE_PREFIX OR NOT IS_DIRECTORY "${STAGE_PREFIX}")
  message(FATAL_ERROR "install audit: existing portable Pure STAGE_PREFIX is required")
endif()
if(DEFINED ENV{DESTDIR} AND NOT "$ENV{DESTDIR}" STREQUAL "")
  message(FATAL_ERROR "install audit: DESTDIR is not supported")
endif()
audio_no_reparse("${AUDIO_INSTALL_GUARD}" "${AUDIO_INSTALL_BUILD_DIR}/install-guard.sha256")
file(SHA256 "${AUDIO_INSTALL_GUARD}" guard_hash)
file(READ "${AUDIO_INSTALL_BUILD_DIR}/install-guard.sha256" guard_pin)
if(NOT guard_pin STREQUAL "${guard_hash}\n")
  message(FATAL_ERROR "install audit: frozen native guard identity mismatch")
endif()
if(DEFINED ENV{PURE_AUDIO_INSTALL_CHANNEL})
  # A public flag/pipe name cannot bypass ownership: the native server checks
  # the actual client PID's parent against its own guarded CMake child.
  install_guard_operation(--probe)
else()
  execute_process(COMMAND "${AUDIO_INSTALL_GUARD}" --run
    "${STAGE_PREFIX}" "${AUDIO_INSTALL_BUILD_DIR}" "${CMAKE_COMMAND}"
    "${AUDIO_INSTALL_CONTEXT}" "${AUDIO_INSTALL_SCRIPT}"
    "${AUDIO_INSTALL_MODE}" "${AUDIO_INSTALL_COMPONENT}"
    RESULT_VARIABLE rc TIMEOUT 260)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "install audit: exclusive guarded operation failed (${rc})")
  endif()
  return()
endif()
audio_path("${STAGE_PREFIX}" directory stage)
string(TOLOWER "${stage}" stage_key)
string(SHA256 stage_key "${stage_key}")
set(session "${AUDIO_INSTALL_BUILD_DIR}/install-audits/${stage_key}")
install_tree("${stage}" current)
install_tree("${PURE_AUDIO_PURE_PREFIX}" source_baseline)
install_rows("${AUDIO_INSTALL_BASELINE_POLICY}" baseline_policy)
if(NOT source_baseline STREQUAL baseline_policy)
  message(FATAL_ERROR "install audit: configured portable Pure baseline changed")
endif()
foreach(row IN LISTS baseline_policy)
  if(NOT row IN_LIST current)
    message(FATAL_ERROR "install audit: missing or altered portable Pure baseline: ${row}")
  endif()
endforeach()

# Preflight ALL components before recording state or copying even one file.
foreach(row IN LISTS sealed)
  string(REPLACE "|" ";" fields "${row}")
  list(GET fields 0 component)
  list(GET fields 1 destination)
  list(GET fields 3 hash)
  if(EXISTS "${stage}/${destination}" OR IS_SYMLINK "${stage}/${destination}")
    if(NOT "${destination}|${hash}" IN_LIST current)
      message(FATAL_ERROR "install audit: non-identical destination collision: ${destination}")
    endif()
  elseif(component STREQUAL "baseline")
    message(FATAL_ERROR "install audit: missing reused baseline runtime ${destination}")
  endif()
  get_filename_component(parent "${stage}/${destination}" DIRECTORY)
  while(NOT parent STREQUAL stage)
    if(EXISTS "${parent}" AND NOT IS_DIRECTORY "${parent}")
      message(FATAL_ERROR "install audit: non-directory destination ancestor ${parent}")
    endif()
    get_filename_component(parent "${parent}" DIRECTORY)
  endwhile()
endforeach()
if(NOT EXISTS "${session}/baseline.tsv")
  if(NOT AUDIO_INSTALL_MODE STREQUAL "install")
    message(FATAL_ERROR "install audit: missing preserved baseline manifest")
  endif()
  audio_no_reparse("${AUDIO_INSTALL_BUILD_DIR}")
  # Only the fixed build-owned session path is created. No recursive deletion.
  install_guard_operation(--mkdir "${session}")
  audio_no_reparse("${session}")
  install_write_rows("${session}/baseline.tsv" "${current}")
  file(SHA256 "${session}/baseline.tsv" baseline_pin)
  install_guard_operation(--write "${session}/baseline.sha256" "${baseline_pin}\n")
endif()
audio_no_reparse("${session}" "${session}/baseline.tsv" "${session}/baseline.sha256")
file(SHA256 "${session}/baseline.tsv" baseline_pin)
file(READ "${session}/baseline.sha256" recorded_pin)
if(NOT recorded_pin STREQUAL "${baseline_pin}\n")
  message(FATAL_ERROR "install audit: preserved baseline manifest changed")
endif()
install_read_tree("${session}/baseline.tsv" baseline)
set(expected_tree "${baseline}")
set(total_delta 0)
foreach(component runtime documentation)
  set(delta_${component} "")
  foreach(row IN LISTS sealed)
    string(REPLACE "|" ";" fields "${row}")
    list(GET fields 0 owner)
    list(GET fields 1 destination)
    list(GET fields 3 hash)
    if(owner STREQUAL component AND NOT "${destination}|${hash}" IN_LIST baseline)
      list(APPEND delta_${component} "${destination}|${hash}")
    endif()
  endforeach()
  list(SORT delta_${component})
  if(EXISTS "${session}/${component}.tsv")
    audio_no_reparse("${session}/${component}.tsv")
    install_read_tree("${session}/${component}.tsv" preserved)
    if(NOT "${preserved}" STREQUAL "${delta_${component}}")
      message(FATAL_ERROR "install audit: ${component} manifest missing/duplicate/cross-component entry")
    endif()
    list(APPEND expected_tree ${preserved})
  elseif(AUDIO_INSTALL_MODE STREQUAL "verify")
    message(FATAL_ERROR "install audit: missing ${component} manifest")
  endif()
  list(LENGTH delta_${component} count)
  math(EXPR total_delta "${total_delta}+${count}")
endforeach()
list(SORT expected_tree)
if(NOT current STREQUAL expected_tree)
  message(FATAL_ERROR "install audit: post tree differs from byte-identical baseline plus declared delta")
endif()

if(AUDIO_INSTALL_MODE STREQUAL "install")
  if(NOT AUDIO_INSTALL_COMPONENT MATCHES "^(runtime|documentation|all)$")
    message(FATAL_ERROR "install audit: unknown component")
  endif()
  foreach(row IN LISTS sealed)
    string(REPLACE "|" ";" fields "${row}")
    list(GET fields 0 owner)
    list(GET fields 1 destination)
    list(GET fields 2 source)
    list(GET fields 3 hash)
    if((owner STREQUAL AUDIO_INSTALL_COMPONENT OR
        (AUDIO_INSTALL_COMPONENT STREQUAL "all" AND NOT owner STREQUAL "baseline")) AND
        NOT "${destination}|${hash}" IN_LIST current)
      install_guard_operation(--copy "${source}" "${stage}/${destination}" "${hash}")
      list(APPEND expected_tree "${destination}|${hash}")
    endif()
  endforeach()
  install_tree("${stage}" after)
  list(SORT expected_tree)
  if(NOT after STREQUAL expected_tree)
    message(FATAL_ERROR "install audit: post-install tree mismatch")
  endif()
  foreach(component runtime documentation)
    if(NOT component STREQUAL AUDIO_INSTALL_COMPONENT AND NOT AUDIO_INSTALL_COMPONENT STREQUAL "all")
      continue()
    endif()
    if(NOT EXISTS "${session}/${component}.tsv")
      install_write_rows("${session}/${component}.tsv" "${delta_${component}}")
    endif()
    # Emit the conventional CMake path-only manifest inside the same guard.
    # Install.cmake returns before CMake's unguarded final file(WRITE).
    set(manifest)
    foreach(row IN LISTS delta_${component})
      string(REPLACE "|" ";" fields "${row}")
      list(GET fields 0 destination)
      list(APPEND manifest "${stage}/${destination}")
    endforeach()
    install_write_rows("${AUDIO_INSTALL_BUILD_DIR}/install_manifest_${component}.txt" "${manifest}")
  endforeach()
  message(STATUS "Installed audited ${AUDIO_INSTALL_COMPONENT}; preserved manifests: ${session}")
  return()
endif()

execute_process(COMMAND "${CMAKE_COMMAND}"
  "-DLLVM_READOBJ=${LLVM_READOBJ}"
  "-DPURE_AUDIO_LLVM_READOBJ_SHA256=${PURE_AUDIO_LLVM_READOBJ_SHA256}"
  "-DAUDIO_MODULE_DIR=${AUDIO_INSTALL_BUILD_DIR}"
  "-DPURE_AUDIO_CLANG64_PREFIX=${PURE_AUDIO_CLANG64_PREFIX}"
  "-DPURE_AUDIO_PURE_PREFIX=${PURE_AUDIO_PURE_PREFIX}"
  "-DPURE_AUDIO_WINDOWS_SYSTEM_DIRECTORY=${PURE_AUDIO_WINDOWS_SYSTEM_DIRECTORY}"
  "-DPURE_AUDIO_RUNTIME_MANIFEST=${PURE_AUDIO_RUNTIME_MANIFEST}"
  "-DSTAGE_PREFIX=${stage}"
  -P "${AUDIO_INSTALL_SOURCE_DIR}/cmake/VerifyWindowsDependencies.cmake"
  RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 120)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "install audit: staged PE closure failed\n${out}${err}")
endif()
message(STATUS "${out}")
set(PURE_AUDIO_RUNNER "${AUDIO_INSTALL_BUILD_DIR}/run_pure_test.exe")
set(PURE_EXECUTABLE "${stage}/bin/pure.exe")
set(PURE_SOURCE_DIR "${stage}/lib/pure")
set(MODULE_DIR "${stage}/lib/pure")
set(TEST_SCRIPT "${stage}/share/doc/pure-audio/tests/smoke.pure")
get_filename_component(windows_root "${AUDIO_SYSTEM_DIR}" DIRECTORY)
set(RUNTIME_DIRS "${stage}/bin;${AUDIO_SYSTEM_DIR};${windows_root}")
set(TEST_TIMEOUT 45000)
set(PURE_AUDIO_STDERR_ALLOWLIST "")
# Include only definitions, then invoke the fixture explicitly. Caller-visible
# helper state and earlier includes must never decide whether smoke executes.
set(PURE_AUDIO_RUNNER_HELPERS_ONLY ON)
include("${AUDIO_INSTALL_SOURCE_DIR}/cmake/RunPureTest.cmake")
pure_audio_run_fixture()
message(STATUS "INSTALL_PACKAGE_OK artifacts=61 runtime=22 documentation=39 delta=${total_delta} pe=29 license_payloads=27 third_party_dlls=22 project_owned_pe=7")
