function(pure_fastcgi_parse_coff_imports read_output out_imports out_error)
  string(REPLACE "\r" "" normalized_output "${read_output}")
  string(REPLACE "\n" ";" output_lines "${normalized_output}")
  set(saw_file FALSE)
  set(saw_format FALSE)
  set(saw_arch FALSE)
  set(saw_address_size FALSE)
  set(in_import FALSE)
  set(import_name "")
  set(imports)
  set(parse_error "")

  foreach(line IN LISTS output_lines)
    if(line STREQUAL "")
      continue()
    elseif(line MATCHES "^File: .+$")
      if(saw_file OR in_import)
        set(parse_error "duplicate or misplaced File field")
        break()
      endif()
      set(saw_file TRUE)
    elseif(line STREQUAL "Format: COFF-x86-64")
      if(saw_format OR in_import)
        set(parse_error "duplicate or misplaced Format field")
        break()
      endif()
      set(saw_format TRUE)
    elseif(line STREQUAL "Arch: x86_64")
      if(saw_arch OR in_import)
        set(parse_error "duplicate or misplaced Arch field")
        break()
      endif()
      set(saw_arch TRUE)
    elseif(line STREQUAL "AddressSize: 64bit")
      if(saw_address_size OR in_import)
        set(parse_error "duplicate or misplaced AddressSize field")
        break()
      endif()
      set(saw_address_size TRUE)
    elseif(line STREQUAL "Import {")
      if(in_import)
        set(parse_error "nested Import block")
        break()
      endif()
      set(in_import TRUE)
      set(import_name "")
    elseif(line STREQUAL "}")
      if(NOT in_import OR import_name STREQUAL "")
        set(parse_error "incomplete Import block")
        break()
      endif()
      list(APPEND imports "${import_name}")
      set(in_import FALSE)
    elseif(line MATCHES "^  Name: .+$")
      if(NOT in_import OR NOT import_name STREQUAL "")
        set(parse_error "misplaced or duplicate import Name")
        break()
      endif()
      string(REGEX REPLACE "^  Name: *" "" import_name "${line}")
      string(STRIP "${import_name}" import_name)
      if(import_name STREQUAL "")
        set(parse_error "empty import Name")
        break()
      endif()
    elseif(NOT in_import)
      set(parse_error "unrecognized top-level output")
      break()
    endif()
  endforeach()

  if(parse_error STREQUAL "" AND in_import)
    set(parse_error "unterminated Import block")
  endif()
  if(parse_error STREQUAL "" AND
      (NOT saw_file OR NOT saw_format OR NOT saw_arch OR NOT saw_address_size))
    set(parse_error "missing required COFF header fields")
  endif()

  set(${out_imports} "${imports}" PARENT_SCOPE)
  set(${out_error} "${parse_error}" PARENT_SCOPE)
endfunction()
