cmake_minimum_required(VERSION 3.25)
# Select at execution time; the ambient legacy PURE_MIDI_OUT is never used.
if(NOT DEFINED MIDI_OUTPUT_SELECTOR)
  set(MIDI_OUTPUT_SELECTOR "$ENV{PURE_MIDI_TEST_OUTPUT}")
endif()
if(MIDI_OUTPUT_SELECTOR STREQUAL "")
  message(FATAL_ERROR "optional hardware output requires an explicit MIDI_OUTPUT_SELECTOR or PURE_MIDI_TEST_OUTPUT")
endif()
set(TEST_SCRIPT "${PURE_SOURCE_DIR}/tests/hardware-output.pure")
set(TIMEOUT_MS 12000)
include("${CMAKE_CURRENT_LIST_DIR}/RunPureTest.cmake")
