cmake_minimum_required(VERSION 3.25)
set(PURE_MIDI_VERIFIER_HELPERS_ONLY ON)
include("${CMAKE_CURRENT_LIST_DIR}/VerifyWindowsDependencies.cmake")
unset(PURE_MIDI_VERIFIER_HELPERS_ONLY)
cmake_host_system_information(RESULT install_windows_root QUERY WINDOWS_REGISTRY
  "HKLM/SOFTWARE/Microsoft/Windows NT/CurrentVersion" VALUE SystemRoot)
set(PURE_MIDI_WINDOWS_SYSTEM_DIRECTORY "${install_windows_root}/System32")
midi_windows_authority()

function(install_relative path)
  string(TOLOWER "${path}" lower)
  if(NOT path MATCHES "^[A-Za-z0-9_+.-]+(/[A-Za-z0-9_+.-]+)*$" OR
      path MATCHES "(^|/)\\.\\.?(/|$)" OR path MATCHES "[.](/|$)" OR
      lower MATCHES "(^|/)(con|prn|aux|nul|com[0-9]|lpt[0-9])([./]|$)")
    message(FATAL_ERROR "install audit: malformed relative path ${path}")
  endif()
endfunction()
function(install_rows text output)
  if(text MATCHES "[;\r]" OR text MATCHES "\n\n" OR NOT text MATCHES "\n$")
    message(FATAL_ERROR "install audit: malformed record stream")
  endif()
  string(REGEX REPLACE "\n$" "" text "${text}")
  string(REPLACE "\n" ";" rows "${text}")
  set(${output} "${rows}" PARENT_SCOPE)
endfunction()
function(install_tree root output)
  midi_path("${root}" directory root)
  midi_no_reparse("${root}")
  if(EXISTS "${MIDI_INSTALL_GUARD}")
    execute_process(COMMAND "${MIDI_INSTALL_GUARD}" --check-tree "${root}" RESULT_VARIABLE rc TIMEOUT 30)
    if(NOT rc EQUAL 0)
      message(FATAL_ERROR "install audit: non-regular, reparse or hardlinked tree")
    endif()
  endif()
  # CMP0009 prohibits link traversal; validate every discovered endpoint and
  # ancestor before hashing. Empty directories are part of the exact contract.
  file(GLOB_RECURSE paths LIST_DIRECTORIES TRUE RELATIVE "${root}" "${root}/*")
  list(SORT paths)
  set(absolute)
  set(seen)
  foreach(path IN LISTS paths)
    install_relative("${path}")
    string(TOLOWER "${path}" folded)
    if(folded IN_LIST seen)
      message(FATAL_ERROR "install audit: case-ambiguous tree path ${path}")
    endif()
    list(APPEND seen "${folded}")
    list(APPEND absolute "${root}/${path}")
  endforeach()
  if(absolute)
    midi_no_reparse(${absolute})
  endif()
  set(rows)
  foreach(path IN LISTS paths)
    if(IS_DIRECTORY "${root}/${path}")
      list(APPEND rows "${path}|d|0|-")
    else()
      file(SIZE "${root}/${path}" size)
      file(SHA256 "${root}/${path}" hash)
      list(APPEND rows "${path}|f|${size}|${hash}")
    endif()
  endforeach()
  list(SORT rows)
  set(${output} "${rows}" PARENT_SCOPE)
endfunction()
function(install_guard_operation operation)
  if(operation STREQUAL "--queue-write")
    execute_process(COMMAND "${MIDI_INSTALL_GUARD}" "${operation}" "${ARGV1}" "${ARGV2}"
      --scope "${STAGE_PREFIX}" "${MIDI_INSTALL_BUILD_DIR}" RESULT_VARIABLE rc TIMEOUT 40)
  else()
    execute_process(COMMAND "${MIDI_INSTALL_GUARD}" ${ARGV}
      --scope "${STAGE_PREFIX}" "${MIDI_INSTALL_BUILD_DIR}" RESULT_VARIABLE rc TIMEOUT 40)
  endif()
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "install audit: guarded operation failed (${rc})")
  endif()
endfunction()
function(install_queue_rows path rows)
  list(JOIN rows "\n" content)
  if(rows)
    string(APPEND content "\n")
  endif()
  install_guard_operation(--queue-write "${path}" "${content}")
endfunction()
function(install_read_tree path output)
  midi_path("${path}" file checked)
  midi_no_reparse("${checked}")
  file(READ "${path}" content)
  install_rows("${content}" rows)
  set(seen)
  foreach(row IN LISTS rows)
    string(REPLACE "|" ";" fields "${row}")
    list(LENGTH fields count)
    if(NOT count EQUAL 4)
      message(FATAL_ERROR "install audit: malformed tree manifest ${path}")
    endif()
    list(GET fields 0 name)
    list(GET fields 1 type)
    list(GET fields 2 size)
    list(GET fields 3 hash)
    install_relative("${name}")
    string(LENGTH "${hash}" length)
    string(TOLOWER "${name}" lower)
    if(lower IN_LIST seen OR NOT size MATCHES "^(0|[1-9][0-9]*)$" OR
        (type STREQUAL "f" AND (NOT hash MATCHES "^[a-f0-9]+$" OR NOT length EQUAL 64)) OR
        (type STREQUAL "d" AND (NOT size STREQUAL "0" OR NOT hash STREQUAL "-")) OR
        NOT type MATCHES "^[fd]$")
      message(FATAL_ERROR "install audit: duplicate/malformed tree manifest ${path}")
    endif()
    list(APPEND seen "${lower}")
  endforeach()
  set(sorted "${rows}")
  list(SORT sorted)
  if(NOT sorted STREQUAL rows)
    message(FATAL_ERROR "install audit: unsorted tree manifest ${path}")
  endif()
  set(${output} "${rows}" PARENT_SCOPE)
endfunction()
if(MIDI_INSTALL_HELPERS_ONLY)
  if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    message(FATAL_ERROR "install audit: helpers-only mode requires inclusion by a driver")
  endif()
  return()
endif()

# This file is trusted configure output. Validate its origin before including;
# artifact/session manifests are parsed strictly as data, never executable code.
midi_path("${MIDI_INSTALL_CONTEXT}" file MIDI_INSTALL_CONTEXT)
midi_no_reparse("${MIDI_INSTALL_CONTEXT}")
include("${MIDI_INSTALL_CONTEXT}")
if(NOT DEFINED MIDI_INSTALL_MODE)
  set(MIDI_INSTALL_MODE verify)
endif()
if(NOT MIDI_INSTALL_MODE MATCHES "^(seal|install|verify)$")
  message(FATAL_ERROR "install audit: unknown operation")
endif()
midi_windows_authority()
midi_path("${MIDI_INSTALL_GUARD}" file MIDI_INSTALL_GUARD)
midi_no_reparse("${MIDI_INSTALL_GUARD}" "${MIDI_INSTALL_BUILD_DIR}")

install_rows("${MIDI_INSTALL_POLICY}" policy)
set(sealed)
set(destinations)
set(sources "${MIDI_INSTALL_CONTEXT}")
foreach(row IN LISTS policy)
  string(REPLACE "|" ";" fields "${row}")
  list(LENGTH fields count)
  if(NOT count EQUAL 9)
    message(FATAL_ERROR "install audit: malformed artifact policy")
  endif()
  list(GET fields 0 component)
  list(GET fields 1 destination)
  list(GET fields 2 source)
  list(GET fields 3 expected)
  list(GET fields 8 mapping)
  install_relative("${destination}")
  string(TOLOWER "${destination}" lower)
  if(lower IN_LIST destinations OR NOT component MATCHES "^(runtime|documentation)$" OR mapping STREQUAL "")
    message(FATAL_ERROR "install audit: duplicate destination, component or license mapping")
  endif()
  list(APPEND destinations "${lower}")
  midi_path("${source}" file source)
  list(APPEND sources "${source}")
  file(SHA256 "${source}" hash)
  file(SIZE "${source}" size)
  if(NOT expected STREQUAL "BUILD" AND NOT hash STREQUAL expected)
    message(FATAL_ERROR "install audit: configured source hash mismatch: ${source}")
  endif()
  if(destination STREQUAL "bin/libportmidi.dll")
    midi_equal_path("${source}" "${PURE_MIDI_CLANG64_PREFIX}/bin/libportmidi.dll")
    if(NOT hash STREQUAL "99454395751bfad786db9c457b93db62f31f7d68dc2bebb2281f33289d43cb49")
      message(FATAL_ERROR "install audit: PortMidi runtime/license identity mismatch")
    endif()
  endif()
  list(REMOVE_AT fields 3)
  list(INSERT fields 3 "${hash}")
  list(JOIN fields "|" row)
  list(APPEND sealed "${row}")
  list(APPEND delta_${component} "${destination}|f|${size}|${hash}")
endforeach()
midi_no_reparse(${sources})
list(LENGTH sealed artifact_count)
list(LENGTH delta_runtime runtime_count)
list(LENGTH delta_documentation documentation_count)
if(NOT runtime_count EQUAL 6 OR NOT documentation_count EQUAL 11)
  message(FATAL_ERROR "install audit: incomplete component inventory")
endif()
list(SORT sealed)
list(JOIN sealed "\n" inventory)
string(APPEND inventory "\n")
string(SHA256 inventory_hash "${inventory}")
if(MIDI_INSTALL_MODE STREQUAL "seal" AND NOT EXISTS "${MIDI_INSTALL_INVENTORY}" AND
    NOT EXISTS "${MIDI_INSTALL_INVENTORY}.sha256")
  file(CONFIGURE OUTPUT "${MIDI_INSTALL_INVENTORY}" CONTENT "${inventory}" @ONLY NEWLINE_STYLE UNIX)
  file(WRITE "${MIDI_INSTALL_INVENTORY}.sha256" "${inventory_hash}\n")
endif()
midi_no_reparse("${MIDI_INSTALL_INVENTORY}" "${MIDI_INSTALL_INVENTORY}.sha256")
file(READ "${MIDI_INSTALL_INVENTORY}" recorded)
file(READ "${MIDI_INSTALL_INVENTORY}.sha256" pin)
file(SHA256 "${MIDI_INSTALL_INVENTORY}" inventory_bytes_hash)
if(NOT recorded STREQUAL inventory OR NOT pin STREQUAL "${inventory_hash}\n" OR
    NOT inventory_bytes_hash STREQUAL inventory_hash)
  message(FATAL_ERROR "install audit: frozen artifact inventory/source mismatch; use a fresh build for changed inputs")
endif()
foreach(row IN LISTS sealed)
  string(REPLACE "|" ";" fields "${row}")
  list(GET fields 4 project)
  list(GET fields 5 version)
  list(GET fields 6 url)
  list(GET fields 7 license)
  list(GET fields 8 mapping)
  set(found FALSE)
  foreach(candidate IN LISTS sealed)
    string(REPLACE "|" ";" c "${candidate}")
    list(GET c 0 cc)
    list(GET c 1 cd)
    list(GET c 4 cp)
    list(GET c 5 cv)
    list(GET c 6 cu)
    list(GET c 7 cl)
    if(cd STREQUAL mapping AND cc STREQUAL documentation AND cp STREQUAL project AND
        cv STREQUAL version AND cu STREQUAL url AND cl STREQUAL license)
      set(found TRUE)
    endif()
  endforeach()
  if(NOT found)
    message(FATAL_ERROR "install audit: runtime-to-license mismatch: ${mapping}")
  endif()
endforeach()
file(SHA256 "${MIDI_INSTALL_GUARD}" guard_hash)
if(MIDI_INSTALL_MODE STREQUAL seal AND NOT EXISTS "${MIDI_INSTALL_BUILD_DIR}/install-guard.sha256")
  file(WRITE "${MIDI_INSTALL_BUILD_DIR}/install-guard.sha256" "${guard_hash}\n")
endif()
midi_no_reparse("${MIDI_INSTALL_BUILD_DIR}/install-guard.sha256")
file(READ "${MIDI_INSTALL_BUILD_DIR}/install-guard.sha256" guard_pin)
if(NOT guard_pin STREQUAL "${guard_hash}\n")
  message(FATAL_ERROR "install audit: frozen native guard identity mismatch")
endif()
install_tree("${PURE_MIDI_PURE_PREFIX}" source_baseline)
install_rows("${MIDI_INSTALL_BASELINE_POLICY}" baseline)
midi_path("${MIDI_INSTALL_BASELINE_PIN}" file baseline_pin)
midi_no_reparse("${baseline_pin}")
file(READ "${baseline_pin}" frozen_baseline)
file(SHA256 "${baseline_pin}" baseline_hash)
if(NOT frozen_baseline STREQUAL MIDI_INSTALL_BASELINE_POLICY OR
    NOT baseline_hash STREQUAL MIDI_INSTALL_BASELINE_SHA256)
  message(FATAL_ERROR "install audit: frozen portable baseline identity mismatch; use a fresh build")
endif()
if(NOT source_baseline STREQUAL baseline)
  message(FATAL_ERROR "install audit: configured portable Pure baseline changed")
endif()
# Derive directory ownership from the canonical baseline and fixed artifact
# destinations. Shared existing ancestors remain baseline; no overlapping deltas.
foreach(component runtime documentation)
  foreach(row IN LISTS delta_${component})
    string(REPLACE "|" ";" fields "${row}")
    list(GET fields 0 destination)
    get_filename_component(parent "${destination}" DIRECTORY)
    while(NOT parent STREQUAL "")
      if(NOT "${parent}|d|0|-" IN_LIST baseline)
        list(APPEND dirs_${component} "${parent}|d|0|-")
      endif()
      get_filename_component(parent "${parent}" DIRECTORY)
    endwhile()
  endforeach()
  list(APPEND delta_${component} ${dirs_${component}})
  list(REMOVE_DUPLICATES delta_${component})
  list(SORT delta_${component})
endforeach()
foreach(row IN LISTS delta_runtime)
  if(row IN_LIST delta_documentation OR row IN_LIST baseline)
    message(FATAL_ERROR "install audit: overlapping component or baseline delta")
  endif()
endforeach()
if(MIDI_INSTALL_MODE STREQUAL seal)
  message(STATUS "INSTALL_INVENTORY_SEALED artifacts=17 runtime=6 documentation=11")
  return()
endif()
if(DEFINED ENV{DESTDIR} AND NOT "$ENV{DESTDIR}" STREQUAL "")
  message(FATAL_ERROR "install audit: DESTDIR is not supported")
endif()
midi_path("${STAGE_PREFIX}" directory STAGE_PREFIX)
midi_no_reparse("${STAGE_PREFIX}")
if(DEFINED ENV{PURE_MIDI_INSTALL_CHANNEL})
  install_guard_operation(--probe)
else()
  execute_process(COMMAND "${MIDI_INSTALL_GUARD}" --run "${STAGE_PREFIX}" "${MIDI_INSTALL_BUILD_DIR}"
    "${CMAKE_COMMAND}" "${MIDI_INSTALL_CONTEXT}" "${MIDI_INSTALL_SCRIPT}"
    "${MIDI_INSTALL_MODE}" "${MIDI_INSTALL_COMPONENT}" RESULT_VARIABLE rc TIMEOUT 260)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "install audit: exclusive guarded operation failed (${rc})")
  endif()
  return()
endif()
set(stage "${STAGE_PREFIX}")
string(TOLOWER "${stage}" stage_key)
string(SHA256 stage_key "${stage_key}")
set(session "${MIDI_INSTALL_BUILD_DIR}/install-audits/${stage_key}")
install_tree("${stage}" current)
set(expected_tree "${baseline}")
if(EXISTS "${session}/baseline.tsv")
  install_read_tree("${session}/baseline.tsv" preserved)
  if(NOT preserved STREQUAL baseline)
    message(FATAL_ERROR "install audit: preserved baseline differs from configured canonical baseline")
  endif()
elseif(MIDI_INSTALL_MODE STREQUAL verify)
  message(FATAL_ERROR "install audit: missing baseline manifest")
endif()
foreach(component runtime documentation)
  if(EXISTS "${session}/${component}.tsv")
    install_read_tree("${session}/${component}.tsv" preserved)
    if(NOT preserved STREQUAL delta_${component})
      message(FATAL_ERROR "install audit: ${component} manifest missing/extra/cross-component entry")
    endif()
    list(APPEND expected_tree ${preserved})
    set(installed_${component} TRUE)
  elseif(MIDI_INSTALL_MODE STREQUAL verify)
    message(FATAL_ERROR "install audit: missing ${component} manifest")
  endif()
endforeach()
list(SORT expected_tree)
if(NOT current STREQUAL expected_tree)
  message(FATAL_ERROR "install audit: tree differs from byte-identical canonical baseline plus declared disjoint delta (collision, missing or extra path)")
endif()
if(MIDI_INSTALL_MODE STREQUAL install)
  if(NOT MIDI_INSTALL_COMPONENT MATCHES "^(runtime|documentation|all)$")
    message(FATAL_ERROR "install audit: unknown component")
  endif()
  if(NOT EXISTS "${session}/baseline.tsv")
    install_queue_rows("${session}/baseline.tsv" "${baseline}")
  endif()
  foreach(row IN LISTS sealed)
    string(REPLACE "|" ";" fields "${row}")
    list(GET fields 0 component)
    list(GET fields 1 destination)
    list(GET fields 2 source)
    list(GET fields 3 hash)
    if(installed_${component})
      continue()
    endif()
    if(component STREQUAL MIDI_INSTALL_COMPONENT OR MIDI_INSTALL_COMPONENT STREQUAL all)
      install_guard_operation(--copy "${source}" "${stage}/${destination}" "${hash}")
    else()
      install_guard_operation(--reserve "${stage}/${destination}")
    endif()
  endforeach()
  foreach(component runtime documentation)
    if(NOT component STREQUAL MIDI_INSTALL_COMPONENT AND NOT MIDI_INSTALL_COMPONENT STREQUAL all)
      continue()
    endif()
    if(NOT installed_${component})
      install_queue_rows("${session}/${component}.tsv" "${delta_${component}}")
      list(APPEND expected_tree ${delta_${component}})
    endif()
    set(manifest)
    foreach(row IN LISTS delta_${component})
      string(REPLACE "|" ";" fields "${row}")
      list(GET fields 0 destination)
      list(GET fields 1 type)
      if(type STREQUAL f)
        list(APPEND manifest "${stage}/${destination}")
      endif()
    endforeach()
    install_queue_rows("${MIDI_INSTALL_BUILD_DIR}/install_manifest_${component}.txt" "${manifest}")
  endforeach()
  install_guard_operation(--publish)
  install_tree("${stage}" after)
  list(SORT expected_tree)
  if(NOT after STREQUAL expected_tree)
    message(FATAL_ERROR "install audit: post-install tree mismatch")
  endif()
  message(STATUS "INSTALL_COMPONENT_OK component=${MIDI_INSTALL_COMPONENT} manifests=${session}")
  return()
endif()

# Every executable, interface, module, test, and fixture given to the Task4
# supervisor is in the stage. Its owned working leaf is outside the stage.
foreach(case device-timing smoke)
  execute_process(COMMAND "${MIDI_INSTALL_RUNNER}" --nonce RESULT_VARIABLE rc
    OUTPUT_VARIABLE token OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "install audit: completion nonce generation failed")
  endif()
  execute_process(COMMAND "${MIDI_INSTALL_RUNNER}"
    --pure "${stage}/bin/pure.exe" --script "${stage}/share/doc/pure-midi/tests/${case}.pure"
    --token "${token}" --timeout-ms 30000 --cwd "${MIDI_INSTALL_CONTRACT_ROOT}"
    --include "${stage}/lib/pure" --library "${stage}/lib/pure"
    --input "${stage}/lib/pure/midi.pure" --input "${stage}/lib/pure/portmidi.pure"
    --input "${stage}/lib/pure/midifile.pure" --input "${stage}/lib/pure/pmlib.dll"
    --input "${stage}/lib/pure/midifile.dll"
    --path-entry "${stage}/lib/pure" --path-entry "${stage}/bin"
    --fixture "${stage}/share/doc/pure-midi/examples/prelude3.mid"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 40)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "install audit: staged ${case} failed (${rc})\n${out}${err}")
  endif()
  message(STATUS "${out}")
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" "-DLLVM_READOBJ=${LLVM_READOBJ}"
  "-DPURE_MIDI_LLVM_READOBJ_SHA256=${PURE_MIDI_LLVM_READOBJ_SHA256}"
  "-DMIDI_MODULE_DIR=${MIDI_INSTALL_BUILD_DIR}"
  "-DPURE_MIDI_CLANG64_PREFIX=${PURE_MIDI_CLANG64_PREFIX}"
  "-DPURE_MIDI_PURE_PREFIX=${PURE_MIDI_PURE_PREFIX}"
  "-DPURE_MIDI_WINDOWS_SYSTEM_DIRECTORY=${PURE_MIDI_WINDOWS_SYSTEM_DIRECTORY}"
  "-DPURE_MIDI_RUNTIME_MANIFEST=${PURE_MIDI_RUNTIME_MANIFEST}"
  "-DSTAGE_PREFIX=${stage}" -P "${CMAKE_CURRENT_LIST_DIR}/VerifyWindowsDependencies.cmake"
  RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 120)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "install audit: staged recursive PE closure failed\n${out}${err}")
endif()
message(STATUS "${out}")
install_tree("${stage}" final)
if(NOT final STREQUAL expected_tree)
  message(FATAL_ERROR "install audit: installed tests changed the exact stage")
endif()
list(LENGTH baseline baseline_count)
list(LENGTH final final_count)
message(STATUS "INSTALL_PACKAGE_OK baseline=${baseline_count} runtime=6 documentation=11 delta_files=17 delta_directories=5 final=${final_count} pe=16 installed_tests=2 license_payloads=1")
