if(NOT DEFINED SOURCE_DIR OR "${SOURCE_DIR}" STREQUAL "")
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()
include("${SOURCE_DIR}/cmake/CompilerClosure.cmake")
list(LENGTH PURE_FAUST_COMPILER_HEADER_FILES header_count)
if(NOT header_count EQUAL 21)
  message(FATAL_ERROR "Expected 21 dependency-derived headers, got ${header_count}")
endif()
foreach(forbidden IN ITEMS
    include/windows.h include/d3d12.h include/ddraw.h include/ntddk.h)
  if(forbidden IN_LIST PURE_FAUST_COMPILER_HEADER_FILES)
    message(FATAL_ERROR "Unrelated SDK/DDK/DirectX header selected: ${forbidden}")
  endif()
endforeach()
message(STATUS "Dependency-derived header closure excludes SDK/DDK/DirectX")
