include_guard(GLOBAL)
# Shared with deterministic CMake-level tests on hosts without POSIX CMake.
function(pure_gl_legacy_check_names source)
  set(reserved .pure-gl-source .pure-gl-dist .pure-gl-dist/.pure-gl-owner
    pure-gl.dll pure-gl.so pure-gl.dylib pure-gl.a pure-gl.dll.a pure-gl-0.9.tar.gz)
  foreach(name GL GL_ARB GL_EXT GL_NV GL_ATI GLU GLUT)
    list(APPEND reserved "${name}.o" "${name}.obj" "${name}.c" "${name}.pure")
  endforeach()
  file(GLOB_RECURSE entries LIST_DIRECTORIES TRUE "${source}/*" "${source}/.*")
  set(seen)
  foreach(path IN LISTS entries)
    string(TOLOWER "${path}" folded)
    if(folded IN_LIST seen)
      message(FATAL_ERROR "Source case-folded duplicate: ${path}")
    endif()
    list(APPEND seen "${folded}")
    file(RELATIVE_PATH relative "${source}" "${path}")
    string(TOLOWER "${relative}" relative_folded)
    foreach(name IN LISTS reserved)
      string(TOLOWER "${name}" name_folded)
      if(relative_folded STREQUAL name_folded AND NOT relative STREQUAL name)
        message(FATAL_ERROR "Source reserved-name case alias: ${relative}; expected ${name}")
      endif()
    endforeach()
    if(IS_SYMLINK "${path}" OR folded MATCHES "(^|/)(\\.git|\\.codex|\\.agents|\\.pure-gl-protected)(/|$)")
      message(FATAL_ERROR "Source reparse/protected descendant: ${path}")
    endif()
  endforeach()
endfunction()
