cmake_minimum_required(VERSION 3.25)
if(NOT MODE MATCHES "^(clean|realclean|generate|dist|distcheck|deb)$")
  message(FATAL_ERROR "Unknown fixed pure-gl workflow")
endif()
if(NOT DLL_SUFFIX MATCHES "^\\.(dll|so|dylib)$")
  message(FATAL_ERROR "Invalid Pure DLL suffix")
endif()
if(NOT PKG_CONFIG_EXECUTABLE)
  message(FATAL_ERROR "Explicit pkg-config is required to validate pure.pc")
endif()
execute_process(COMMAND "${PKG_CONFIG_EXECUTABLE}" --exists pure
  RESULT_VARIABLE rc ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Missing pure.pc: ${err}")
endif()
if(CMAKE_HOST_WIN32)
  if(MODE STREQUAL deb)
    message(FATAL_ERROR "Debian packaging requires a POSIX debuild toolchain; use make dist on Windows")
  endif()
  cmake_host_system_information(RESULT windows_root QUERY WINDOWS_REGISTRY
    "HKLM/SOFTWARE/Microsoft/Windows NT/CurrentVersion" VALUE SystemRoot)
  execute_process(COMMAND "${windows_root}/System32/WindowsPowerShell/v1.0/powershell.exe"
    -NoProfile -NonInteractive -ExecutionPolicy Bypass
    -File "${CMAKE_CURRENT_LIST_DIR}/LegacyWorkflow.ps1"
    -Mode "${MODE}" -SourceRoot "${SOURCE_ROOT}" -CMake "${CMAKE_COMMAND}"
    -DistFiles "${DIST_FILES}" -AuditBuild "${DIST_AUDIT_BUILD}"
    RESULT_VARIABLE rc)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Guarded pure-gl ${MODE} refused (${rc})")
  endif()
  return()
endif()

# POSIX keeps the legacy build usable with the same literal outputs. Symlink,
# protected-tree, sentinel and canonical-path checks precede every removal.
get_filename_component(source "${CMAKE_CURRENT_LIST_DIR}/.." REALPATH)
if(NOT source STREQUAL SOURCE_ROOT)
  message(FATAL_ERROR "Source root is a noncanonical alias")
endif()
set(path "${source}")
while(NOT path STREQUAL "/")
  if(IS_SYMLINK "${path}")
    message(FATAL_ERROR "Source reparse component")
  endif()
  get_filename_component(path "${path}" DIRECTORY)
endwhile()
file(READ "${source}/.pure-gl-source" owner)
if(NOT owner STREQUAL "pure-gl source 0.9\n")
  message(FATAL_ERROR "Source sentinel mismatch")
endif()
file(GLOB_RECURSE entries LIST_DIRECTORIES TRUE "${source}/*" "${source}/.*")
set(seen)
foreach(path IN LISTS entries)
  string(TOLOWER "${path}" folded)
  if(folded IN_LIST seen)
    message(FATAL_ERROR "Source case-folded duplicate: ${path}")
  endif()
  list(APPEND seen "${folded}")
  if(IS_SYMLINK "${path}" OR path MATCHES "(^|/)(\\.git|\\.codex|\\.agents|\\.pure-gl-protected)(/|$)")
    message(FATAL_ERROR "Source reparse/protected descendant: ${path}")
  endif()
endforeach()
set(leaf "${source}/.pure-gl-dist")
set(leaf_owner "pure-gl legacy dist leaf\nsource=${source}\n")
function(clean_work_leaf)
  file(READ "${source}/.pure-gl-source" current_source_owner)
  file(READ "${leaf}/.pure-gl-owner" current_leaf_owner)
  if(NOT current_source_owner STREQUAL owner OR NOT current_leaf_owner STREQUAL leaf_owner)
    message(FATAL_ERROR "Source/work leaf sentinel mismatch")
  endif()
  file(GLOB_RECURSE paths LIST_DIRECTORIES TRUE "${leaf}/*" "${leaf}/.*")
  foreach(path IN LISTS paths)
    cmake_path(IS_PREFIX leaf "${path}" NORMALIZE owned)
    if(NOT owned OR path STREQUAL leaf OR IS_SYMLINK "${path}" OR
        path MATCHES "(^|/)(\\.git|\\.codex|\\.agents|\\.pure-gl-protected)(/|$)")
      message(FATAL_ERROR "Work leaf reparse/protected descendant: ${path}")
    endif()
  endforeach()
  list(SORT paths ORDER DESCENDING)
  foreach(path IN LISTS paths)
    if(IS_DIRECTORY "${path}")
      execute_process(COMMAND rmdir "${path}" COMMAND_ERROR_IS_FATAL ANY)
    else()
      file(REMOVE "${path}")
    endif()
  endforeach()
  execute_process(COMMAND rmdir "${leaf}" COMMAND_ERROR_IS_FATAL ANY)
endfunction()
if(EXISTS "${leaf}")
  file(READ "${leaf}/.pure-gl-owner" actual_leaf_owner)
  if(NOT actual_leaf_owner STREQUAL leaf_owner)
    message(FATAL_ERROR "Work leaf sentinel mismatch")
  endif()
endif()
set(outputs pure-gl.dll pure-gl.so pure-gl.dylib pure-gl.a pure-gl.dll.a)
foreach(name GL GL_ARB GL_EXT GL_NV GL_ATI GLU GLUT)
  list(APPEND outputs "${name}.o" "${name}.obj")
  if(MODE STREQUAL realclean)
    list(APPEND outputs "${name}.c" "${name}.pure")
  endif()
endforeach()
foreach(name IN LISTS outputs)
  if(IS_DIRECTORY "${source}/${name}")
    message(FATAL_ERROR "Expected regular package output: ${name}")
  endif()
endforeach()
if(MODE MATCHES "^(dist|distcheck|deb)$")
  if(NOT MODE STREQUAL dist)
    find_program(work_make NAMES "${GNU_MAKE_EXECUTABLE}" make REQUIRED)
  endif()
  if(MODE STREQUAL deb)
    find_program(debuild NAMES debuild REQUIRED)
  endif()
  string(STRIP "${DIST_FILES}" names)
  string(REGEX REPLACE "[ \t\r\n]+" ";" names "${names}")
  set(seen)
  foreach(name IN LISTS names)
    string(TOLOWER "${name}" folded)
    if(NOT name MATCHES "^[A-Za-z0-9_+./-]+$" OR name MATCHES "^/|(^|/)\\.\\.(/|$)" OR
        folded IN_LIST seen OR NOT EXISTS "${source}/${name}" OR IS_DIRECTORY "${source}/${name}")
      message(FATAL_ERROR "Invalid release input: ${name}")
    endif()
    list(APPEND seen "${folded}")
  endforeach()
  if(IS_DIRECTORY "${source}/pure-gl-0.9.tar.gz")
    message(FATAL_ERROR "Expected regular archive output")
  endif()
  if(EXISTS "${leaf}")
    clean_work_leaf()
  endif()
  file(MAKE_DIRECTORY "${leaf}")
  file(WRITE "${leaf}/.pure-gl-owner" "${leaf_owner}")
  set(package "${leaf}/pure-gl-0.9")
  file(MAKE_DIRECTORY "${package}" "${package}/GL" "${package}/cmake"
    "${package}/debian/source" "${package}/examples/flexi-line" "${package}/tests/fixtures")
  foreach(name IN LISTS names)
    file(COPY_FILE "${source}/${name}" "${package}/${name}")
  endforeach()
  file(READ "${package}/README" readme)
  string(TIMESTAMP today "%B %d, %Y")
  string(REPLACE "@version@" "0.9" readme "${readme}")
  string(REPLACE "|today|" "${today}" readme "${readme}")
  file(WRITE "${package}/README" "${readme}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cfz payload.tar.gz --format=gnutar pure-gl-0.9
    WORKING_DIRECTORY "${leaf}" COMMAND_ERROR_IS_FATAL ANY)
  file(REMOVE "${source}/pure-gl-0.9.tar.gz")
  file(RENAME "${leaf}/payload.tar.gz" "${source}/pure-gl-0.9.tar.gz" NO_REPLACE)
  if(MODE STREQUAL distcheck)
    execute_process(COMMAND "${work_make}" WORKING_DIRECTORY "${package}" COMMAND_ERROR_IS_FATAL ANY)
    execute_process(COMMAND "${work_make}" install "DESTDIR=${leaf}/BUILD"
      WORKING_DIRECTORY "${package}" COMMAND_ERROR_IS_FATAL ANY)
  elseif(MODE STREQUAL deb)
    file(COPY_FILE "${source}/pure-gl-0.9.tar.gz" "${leaf}/pure-gl_0.9.orig.tar.gz")
    separate_arguments(flags UNIX_COMMAND "${DEBUILD_FLAGS}")
    execute_process(COMMAND "${debuild}" ${flags} WORKING_DIRECTORY "${package}" COMMAND_ERROR_IS_FATAL ANY)
    # Keep successful Debian artifacts in the owned leaf for the caller.
    return()
  endif()
  clean_work_leaf()
  return()
endif()
foreach(name IN LISTS outputs)
  file(REMOVE "${source}/${name}")
endforeach()
