include_guard(GLOBAL)
function(gl_pe_loader)
  execute_process(COMMAND "${LLVM_STRINGS}" "${PURE_GL_MODULE}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE strings ERROR_VARIABLE err TIMEOUT 30 ENCODING UTF-8)
  string(REPLACE "\r\n" "\n" strings "${strings}")
  if(NOT rc EQUAL 0 OR NOT err STREQUAL "" OR strings MATCHES "[^\t\n -~]")
    message(FATAL_ERROR "pure-gl PE: strings tool/decoding failed for ${PURE_GL_MODULE}: ${rc}\n${err}")
  endif()
  if(NOT strings MATCHES "(^|\n)libfreeglut\\.dll(\n|$)")
    message(FATAL_ERROR "pure-gl PE: ${PURE_GL_MODULE} requires a line-exact libfreeglut.dll reference")
  endif()
  if(strings MATCHES "(^|\n)freeglut\\.dll(\n|$)")
    message(FATAL_ERROR "pure-gl PE: ${PURE_GL_MODULE} contains obsolete freeglut.dll")
  endif()
  # Each wrapper family embeds the same loader name. Repetition is expected;
  # alternate case, prefixes, suffixes or whitespace are ambiguous loader names.
  string(REGEX MATCHALL "[^\n]*[Ff][Rr][Ee][Ee][Gg][Ll][Uu][Tt]\\.[Dd][Ll][Ll][^\n]*" loader_names "${strings}")
  foreach(loader IN LISTS loader_names)
    if(NOT loader STREQUAL "libfreeglut.dll")
      message(FATAL_ERROR "pure-gl PE: ${PURE_GL_MODULE} ambiguous loader string ${loader}")
    endif()
  endforeach()
endfunction()

function(gl_pe_equal_path actual expected)
  file(TO_CMAKE_PATH "${actual}" actual)
  file(TO_CMAKE_PATH "${expected}" expected)
  string(TOLOWER "${actual}" actual)
  string(TOLOWER "${expected}" expected)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "pure-gl PE: wrong origin; expected ${expected}, actual ${actual}")
  endif()
endfunction()

function(gl_pe_path path kind)
  if(NOT path MATCHES "^[A-Za-z]:/" OR path MATCHES "[;|<>\"?*'\r\n]" OR
      path MATCHES "(^|/)[^/]*[. ](/|$)" OR path MATCHES ":[^/]" OR path MATCHES "//")
    message(FATAL_ERROR "pure-gl PE: malformed absolute path: ${path}")
  endif()
  cmake_path(NORMAL_PATH path OUTPUT_VARIABLE normalized)
  if(NOT normalized STREQUAL path OR NOT EXISTS "${path}" OR IS_SYMLINK "${path}")
    message(FATAL_ERROR "pure-gl PE: missing, noncanonical or reparse path: ${path}")
  endif()
  if((kind STREQUAL "file" AND IS_DIRECTORY "${path}") OR
      (kind STREQUAL "directory" AND NOT IS_DIRECTORY "${path}"))
    message(FATAL_ERROR "pure-gl PE: expected ${kind}: ${path}")
  endif()
  file(REAL_PATH "${path}" real)
  gl_pe_equal_path("${real}" "${path}")
endfunction()

# Check all ancestors, including Windows junctions not covered by IS_SYMLINK.
# Powershell is selected only from the registry-validated Windows directory.
function(gl_pe_no_reparse)
  set(quoted)
  foreach(path IN LISTS ARGN)
    gl_pe_path("${path}" any)
    list(APPEND quoted "'${path}'")
  endforeach()
  list(JOIN quoted "," array)
  execute_process(COMMAND "${GL_PE_POWERSHELL}" -NoProfile -NonInteractive -Command
    "$ErrorActionPreference='Stop'; $seen=@{}; foreach($p in @(${array})) { while($p -and -not $seen.ContainsKey($p)) { $i=Get-Item -LiteralPath $p -Force; if(($i.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw ('reparse component: '+$p) }; $seen[$p]=1; $p=[IO.Path]::GetDirectoryName($p.TrimEnd('/','\\')) } }"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
  if(NOT rc EQUAL 0 OR NOT out STREQUAL "" OR NOT err STREQUAL "")
    message(FATAL_ERROR "pure-gl PE: reparse validation failed: ${rc}\n${out}${err}")
  endif()
endfunction()

function(gl_pe_pin path expected)
  gl_pe_path("${path}" file)
  string(LENGTH "${expected}" length)
  file(SHA256 "${path}" actual)
  string(TOLOWER "${expected}" expected)
  if(NOT length EQUAL 64 OR NOT expected MATCHES "^[0-9a-f]+$" OR
      NOT actual STREQUAL expected)
    message(FATAL_ERROR "pure-gl PE: SHA256 mismatch for ${path}; expected ${expected}, actual ${actual}")
  endif()
endfunction()

function(gl_pe_exact binary expected actual)
  set(missing ${expected})
  set(unexpected ${actual})
  if(actual)
    list(REMOVE_ITEM missing ${actual})
  endif()
  if(expected)
    list(REMOVE_ITEM unexpected ${expected})
  endif()
  if(missing OR unexpected)
    message(FATAL_ERROR
      "pure-gl PE ${binary}: expected=[${expected}] actual=[${actual}] missing=[${missing}] unexpected=[${unexpected}]")
  endif()
endfunction()

function(gl_pe_fixture name output)
  if(name STREQUAL "libfreeglut.dll")
    set(stem freeglut)
  else()
    string(REGEX REPLACE "\\.dll$" "" stem "${name}")
  endif()
  file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../tests/fixtures/${stem}-imports.txt" text)
  string(REPLACE "\r\n" "\n" text "${text}")
  string(REGEX REPLACE "\n$" "" text "${text}")
  string(REPLACE "\n" ";" names "${text}")
  foreach(import IN LISTS names)
    if(NOT import MATCHES "^[a-z0-9_+.-]+\\.dll$")
      message(FATAL_ERROR "pure-gl PE: malformed literal fixture for ${name}: ${import}")
    endif()
  endforeach()
  set(normalized ${names})
  list(REMOVE_DUPLICATES normalized)
  list(SORT normalized)
  if(NOT names STREQUAL normalized)
    message(FATAL_ERROR "pure-gl PE: fixture must be unique, sorted and lowercase: ${name}")
  endif()
  set(${output} "${names}" PARENT_SCOPE)
endfunction()

function(gl_pe_read path output)
  execute_process(COMMAND "${LLVM_READOBJ}" --file-headers --coff-imports "${path}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE records ERROR_VARIABLE err TIMEOUT 30
    ENCODING UTF-8)
  if(NOT rc EQUAL 0 OR NOT err STREQUAL "" OR records MATCHES "[^\t\r\n -~]")
    message(FATAL_ERROR "pure-gl PE: reader failed or decoding failed for ${path}: ${rc}\n${err}")
  endif()
  gl_pe_parse_pe("${records}" "${path}" imports)
  set(${output} "${imports}" PARENT_SCOPE)
endfunction()

# Classify names before searching: foreign roots cannot satisfy Pure/system
# dependencies. Inspect competing runtime directories to catch loader shadows.
function(gl_pe_resolve name output system_output)
  if(name MATCHES "^(msys-2\\.0\\.dll|libgcc.*|libstdc\\+\\+.*)$")
    message(FATAL_ERROR "pure-gl PE: forbidden runtime import ${name}")
  endif()
  set(system FALSE)
  if(name STREQUAL "pure-gl.dll")
    set(wanted "${PURE_GL_MODULE}")
  elseif(name STREQUAL "libfreeglut.dll")
    set(wanted "${FREEGLUT_DLL}")
  elseif(name IN_LIST GL_PE_PURE_NAMES)
    set(wanted "${PURE_GL_PURE_PREFIX}/bin/${name}")
  elseif(name IN_LIST GL_PE_SYSTEM_NAMES)
    set(wanted "${PURE_GL_WINDOWS_SYSTEM_DIRECTORY}/${name}")
    set(system TRUE)
  elseif(name MATCHES "^api-ms-win-crt-(convert|environment|filesystem|heap|locale|math|multibyte|private|process|runtime|stdio|string|time|utility)-l1-1-0\\.dll$")
    # Windows 10+ API-set contracts map these normal imports to the OS UCRT.
    # The schema names are literal/closed; arbitrary api-* names are rejected.
    set(wanted "${PURE_GL_WINDOWS_SYSTEM_DIRECTORY}/ucrtbase.dll")
    set(system TRUE)
  else()
    message(FATAL_ERROR "pure-gl PE: unreviewed dependency ${name}")
  endif()
  set(candidates)
  foreach(directory "${GL_PE_MODULE_DIRECTORY}" "${PURE_GL_RUNTIME_DIRECTORY}")
    if(EXISTS "${directory}/${name}")
      list(APPEND candidates "${directory}/${name}")
    endif()
  endforeach()
  if(EXISTS "${wanted}")
    list(APPEND candidates "${wanted}")
  endif()
  set(folded)
  foreach(candidate IN LISTS candidates)
    string(TOLOWER "${candidate}" key)
    list(APPEND folded "${key}")
  endforeach()
  list(REMOVE_DUPLICATES folded)
  list(LENGTH folded count)
  if(count GREATER 1)
    message(FATAL_ERROR "pure-gl PE: ambiguous resolution for ${name}: ${candidates}")
  elseif(NOT count EQUAL 1)
    message(FATAL_ERROR "pure-gl PE: missing dependency ${name}; expected ${wanted}")
  endif()
  list(GET candidates 0 actual)
  gl_pe_equal_path("${actual}" "${wanted}")
  gl_pe_path("${wanted}" file)
  set(${output} "${wanted}" PARENT_SCOPE)
  set(${system_output} "${system}" PARENT_SCOPE)
endfunction()
# Strict COFF record grammar adapted from pure-midi's audited parser. Keep this
# local so released pure-gl sources do not depend on another package checkout.
function(gl_pe_parse_pe text path output)
  # COFF flag names and bits from the Windows SDK/LLVM COFF definitions.
  # Each printed row must account for exactly one bit in its enclosing mask.
  set(flags_ImageFileHeader
    "IMAGE_FILE_RELOCS_STRIPPED|0x1" "IMAGE_FILE_EXECUTABLE_IMAGE|0x2"
    "IMAGE_FILE_LINE_NUMS_STRIPPED|0x4" "IMAGE_FILE_LOCAL_SYMS_STRIPPED|0x8"
    "IMAGE_FILE_AGGRESSIVE_WS_TRIM|0x10" "IMAGE_FILE_LARGE_ADDRESS_AWARE|0x20"
    "IMAGE_FILE_BYTES_REVERSED_LO|0x80" "IMAGE_FILE_32BIT_MACHINE|0x100"
    "IMAGE_FILE_DEBUG_STRIPPED|0x200" "IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP|0x400"
    "IMAGE_FILE_NET_RUN_FROM_SWAP|0x800" "IMAGE_FILE_SYSTEM|0x1000"
    "IMAGE_FILE_DLL|0x2000" "IMAGE_FILE_UP_SYSTEM_ONLY|0x4000"
    "IMAGE_FILE_BYTES_REVERSED_HI|0x8000")
  set(flags_ImageOptionalHeader
    "IMAGE_DLL_CHARACTERISTICS_HIGH_ENTROPY_VA|0x20"
    "IMAGE_DLL_CHARACTERISTICS_DYNAMIC_BASE|0x40"
    "IMAGE_DLL_CHARACTERISTICS_FORCE_INTEGRITY|0x80"
    "IMAGE_DLL_CHARACTERISTICS_NX_COMPAT|0x100"
    "IMAGE_DLL_CHARACTERISTICS_NO_ISOLATION|0x200"
    "IMAGE_DLL_CHARACTERISTICS_NO_SEH|0x400"
    "IMAGE_DLL_CHARACTERISTICS_NO_BIND|0x800"
    "IMAGE_DLL_CHARACTERISTICS_APPCONTAINER|0x1000"
    "IMAGE_DLL_CHARACTERISTICS_WDM_DRIVER|0x2000"
    "IMAGE_DLL_CHARACTERISTICS_GUARD_CF|0x4000"
    "IMAGE_DLL_CHARACTERISTICS_TERMINAL_SERVER_AWARE|0x8000")
  foreach(section ImageFileHeader ImageOptionalHeader)
    foreach(row IN LISTS flags_${section})
      string(REPLACE "|" ";" parts "${row}")
      list(GET parts 0 name)
      list(GET parts 1 bit)
      list(APPEND flag_names_${section} "${name}")
      set(flag_value_${section}_${name} "${bit}")
    endforeach()
  endforeach()
  set(keys_ImageFileHeader Machine SectionCount TimeDateStamp PointerToSymbolTable
    SymbolCount StringTableSize OptionalHeaderSize Characteristics)
  set(keys_ImageOptionalHeader Magic MajorLinkerVersion MinorLinkerVersion
    SizeOfCode SizeOfInitializedData SizeOfUninitializedData AddressOfEntryPoint
    BaseOfCode ImageBase SectionAlignment FileAlignment MajorOperatingSystemVersion
    MinorOperatingSystemVersion MajorImageVersion MinorImageVersion MajorSubsystemVersion
    MinorSubsystemVersion SizeOfImage SizeOfHeaders CheckSum Subsystem Characteristics
    SizeOfStackReserve SizeOfStackCommit SizeOfHeapReserve SizeOfHeapCommit
    NumberOfRvaAndSize DataDirectory)
  set(keys_DOSHeader Magic UsedBytesInTheLastPage FileSizeInPages NumberOfRelocationItems
    HeaderSizeInParagraphs MinimumExtraParagraphs MaximumExtraParagraphs InitialRelativeSS
    InitialSP Checksum InitialIP InitialRelativeCS AddressOfRelocationTable OverlayNumber
    OEMid OEMinfo AddressOfNewExeHeader)
  set(keys_DataDirectory ExportTableRVA ExportTableSize ImportTableRVA ImportTableSize
    ResourceTableRVA ResourceTableSize ExceptionTableRVA ExceptionTableSize
    CertificateTableRVA CertificateTableSize BaseRelocationTableRVA BaseRelocationTableSize
    DebugRVA DebugSize ArchitectureRVA ArchitectureSize GlobalPtrRVA GlobalPtrSize
    TLSTableRVA TLSTableSize LoadConfigTableRVA LoadConfigTableSize BoundImportRVA
    BoundImportSize IATRVA IATSize DelayImportDescriptorRVA DelayImportDescriptorSize
    CLRRuntimeHeaderRVA CLRRuntimeHeaderSize ReservedRVA ReservedSize)
  string(REPLACE "\r\n" "\n" text "${text}")
  if(text MATCHES "[;\r]" OR text MATCHES "@GL_PE_")
    message(FATAL_ERROR "pure-gl PE: malformed readobj characters for ${path}")
  endif()
  # CMake lists treat unmatched square brackets as grouping, even across
  # semicolons. Encode readobj's flag delimiters before splitting lines.
  string(REPLACE "[" "@GL_PE_LBRACKET@" text "${text}")
  string(REPLACE "]" "@GL_PE_RBRACKET@" text "${text}")
  string(REPLACE "\n" ";" lines "${text}")
  set(stack)
  set(top_seen)
  set(imports)
  foreach(line IN LISTS lines)
    string(REPLACE "@GL_PE_LBRACKET@" "[" line "${line}")
    string(REPLACE "@GL_PE_RBRACKET@" "]" line "${line}")
    if(line STREQUAL "")
      continue()
    endif()
    string(STRIP "${line}" stripped)
    if(NOT stack)
      if(line MATCHES "^(File|Format|Arch|AddressSize): (.+)$")
        set(key "${CMAKE_MATCH_1}")
        set(value "${CMAKE_MATCH_2}")
        if(key IN_LIST top_seen)
          message(FATAL_ERROR "pure-gl PE: duplicate ${key} record for ${path}")
        endif()
        list(APPEND top_seen "${key}")
        set(meta_${key} "${value}")
      elseif(line MATCHES "^(ImageFileHeader|ImageOptionalHeader|DOSHeader|Import) \\{$")
        set(section "${CMAKE_MATCH_1}")
        if(NOT section STREQUAL "Import")
          if(section IN_LIST top_seen)
            message(FATAL_ERROR "pure-gl PE: duplicate ${section} for ${path}")
          endif()
          list(APPEND top_seen "${section}")
        endif()
        set(stack "${section}")
        set(fields)
        set(import_symbols)
      else()
        message(FATAL_ERROR "pure-gl PE: unknown/incomplete top-level record for ${path}: ${line}")
      endif()
      continue()
    endif()
    list(GET stack -1 current)
    list(LENGTH stack depth)
    if(stripped STREQUAL "}" OR stripped STREQUAL "]")
      if((current STREQUAL "Characteristics" AND NOT stripped STREQUAL "]") OR
          (NOT current STREQUAL "Characteristics" AND NOT stripped STREQUAL "}"))
        message(FATAL_ERROR "pure-gl PE: unbalanced readobj block for ${path}")
      endif()
      if(section STREQUAL "Import")
        foreach(required Name ImportLookupTableRVA ImportAddressTableRVA Symbol)
          if(NOT required IN_LIST fields)
            message(FATAL_ERROR "pure-gl PE: incomplete import (${required}) for ${path}")
          endif()
        endforeach()
        string(TOLOWER "${import_Name}" name)
        if(name MATCHES "^(msys.*|libgcc.*|libstdc\\+\\+.*)\\.dll$")
          message(FATAL_ERROR "pure-gl PE: forbidden runtime import ${name} for ${path}")
        endif()
        if(name IN_LIST imports)
          message(FATAL_ERROR "pure-gl PE: duplicate import ${name} for ${path}")
        endif()
        list(APPEND imports "${name}")
      elseif(current STREQUAL "Characteristics")
        if(NOT characteristics_bits EQUAL characteristics_mask)
          message(FATAL_ERROR "pure-gl PE: incomplete/mismatched Characteristics mask for ${path}")
        endif()
        set(header_${section}_Characteristics "${characteristics_bits}")
      else()
        foreach(key IN LISTS keys_${current})
          if(NOT "${current}_${key}" IN_LIST fields)
            message(FATAL_ERROR "pure-gl PE: incomplete ${current} field ${key} for ${path}")
          endif()
        endforeach()
      endif()
      list(POP_BACK stack)
    elseif(section STREQUAL "Import")
      if(NOT depth EQUAL 1 OR NOT line MATCHES "^  (Name|ImportLookupTableRVA|ImportAddressTableRVA|Symbol): (.+)$")
        message(FATAL_ERROR "pure-gl PE: malformed import record for ${path}: ${line}")
      endif()
      set(key "${CMAKE_MATCH_1}")
      set(value "${CMAKE_MATCH_2}")
      if(NOT key STREQUAL "Symbol")
        if(key IN_LIST fields)
          message(FATAL_ERROR "pure-gl PE: multiple ${key} fields in import for ${path}")
        endif()
        list(APPEND fields "${key}")
      endif()
      if(key STREQUAL "Name")
        if(NOT value MATCHES "^[A-Za-z0-9_+.-]+\\.[dD][lL][lL]$")
          message(FATAL_ERROR "pure-gl PE: malformed import name ${value} for ${path}")
        endif()
      elseif(key MATCHES "RVA$" AND NOT value MATCHES "^0x[0-9A-Fa-f]+$")
        message(FATAL_ERROR "pure-gl PE: malformed import RVA for ${path}")
      elseif(key STREQUAL "Symbol" AND NOT value MATCHES "^[^{}]+ \\([0-9]+\\)$")
        message(FATAL_ERROR "pure-gl PE: malformed import symbol for ${path}")
      endif()
      if(key STREQUAL "Symbol")
        if(value IN_LIST import_symbols)
          message(FATAL_ERROR "pure-gl PE: duplicate import symbol for ${path}")
        endif()
        list(APPEND import_symbols "${value}")
        list(APPEND fields Symbol)
      endif()
      set(import_${key} "${value}")
    elseif(stripped MATCHES "^Characteristics \\[ \\((0x[0-9A-Fa-f]+)\\)$" AND
        depth EQUAL 1 AND (section STREQUAL "ImageFileHeader" OR section STREQUAL "ImageOptionalHeader"))
      set(mask "${CMAKE_MATCH_1}")
      string(LENGTH "${mask}" mask_length)
      if(mask_length GREATER 6)
        message(FATAL_ERROR "pure-gl PE: Characteristics mask exceeds 16 bits for ${path}")
      endif()
      if("${current}_Characteristics" IN_LIST fields)
        message(FATAL_ERROR "pure-gl PE: duplicate characteristics for ${path}")
      endif()
      math(EXPR characteristics_mask "${mask}")
      set(characteristics_bits 0)
      set(characteristics_seen)
      list(APPEND fields "${current}_Characteristics")
      list(APPEND stack Characteristics)
    elseif(stripped STREQUAL "DataDirectory {" AND section STREQUAL "ImageOptionalHeader" AND depth EQUAL 1)
      if(ImageOptionalHeader_DataDirectory IN_LIST fields)
        message(FATAL_ERROR "pure-gl PE: duplicate DataDirectory for ${path}")
      endif()
      list(APPEND fields ImageOptionalHeader_DataDirectory)
      list(APPEND stack DataDirectory)
    elseif(current STREQUAL "Characteristics")
      if(NOT stripped MATCHES "^(IMAGE_[A-Z0-9_]+) \\((0x[0-9A-Fa-f]+)\\)$")
        message(FATAL_ERROR "pure-gl PE: malformed PE characteristics for ${path}")
      endif()
      set(flag "${CMAKE_MATCH_1}")
      set(bit "${CMAKE_MATCH_2}")
      string(LENGTH "${bit}" bit_length)
      if(NOT flag IN_LIST flag_names_${section} OR bit_length GREATER 6)
        message(FATAL_ERROR "pure-gl PE: unknown Characteristics flag ${flag} for ${path}")
      endif()
      if(flag IN_LIST characteristics_seen)
        message(FATAL_ERROR "pure-gl PE: duplicate Characteristics flag ${flag} for ${path}")
      endif()
      if(NOT bit EQUAL flag_value_${section}_${flag})
        message(FATAL_ERROR "pure-gl PE: wrong Characteristics bit for ${flag}: ${path}")
      endif()
      list(APPEND characteristics_seen "${flag}")
      math(EXPR characteristics_bits "${characteristics_bits} | ${bit}")
    elseif(stripped MATCHES "^([A-Za-z][A-Za-z0-9]+): ([^{}]+)$")
      set(key "${CMAKE_MATCH_1}")
      set(value "${CMAKE_MATCH_2}")
      if(NOT key IN_LIST keys_${current})
        message(FATAL_ERROR "pure-gl PE: unknown ${current} field ${key} for ${path}")
      endif()
      if(key STREQUAL "Characteristics")
        message(FATAL_ERROR "pure-gl PE: bracketed Characteristics record required for ${path}")
      elseif(key STREQUAL "Machine")
        if(NOT value MATCHES "^IMAGE_FILE_MACHINE_[A-Z0-9_]+ \\(0x[0-9A-Fa-f]+\\)$")
          message(FATAL_ERROR "pure-gl PE: malformed Machine field for ${path}")
        endif()
      elseif(key STREQUAL "Subsystem")
        if(NOT value MATCHES "^IMAGE_SUBSYSTEM_[A-Z0-9_]+ \\(0x[0-9A-Fa-f]+\\)$")
          message(FATAL_ERROR "pure-gl PE: malformed Subsystem field for ${path}")
        endif()
      elseif(key STREQUAL "TimeDateStamp")
        if(NOT value MATCHES "^[0-9-]+ [0-9:]+ \\(0x[0-9A-Fa-f]+\\)$")
          message(FATAL_ERROR "pure-gl PE: malformed TimeDateStamp field for ${path}")
        endif()
      elseif(NOT (current STREQUAL "DOSHeader" AND key STREQUAL "Magic") AND
          NOT value MATCHES "^(0x[0-9A-Fa-f]+|[0-9]+)$")
        message(FATAL_ERROR "pure-gl PE: malformed numeric ${key} field for ${path}")
      endif()
      set(field "${current}_${key}")
      if(field IN_LIST fields)
        message(FATAL_ERROR "pure-gl PE: duplicate header field ${field} for ${path}")
      endif()
      list(APPEND fields "${field}")
      set(header_${field} "${value}")
    else()
      message(FATAL_ERROR "pure-gl PE: malformed header block for ${path}: ${line}")
    endif()
  endforeach()
  if(stack)
    message(FATAL_ERROR "pure-gl PE: truncated readobj block for ${path}")
  endif()
  foreach(required File Format Arch AddressSize ImageFileHeader ImageOptionalHeader DOSHeader)
    if(NOT required IN_LIST top_seen)
      message(FATAL_ERROR "pure-gl PE: missing ${required} for ${path}")
    endif()
  endforeach()
  gl_pe_equal_path("${meta_File}" "${path}")
  if(NOT meta_Format STREQUAL "COFF-x86-64" OR NOT meta_Arch STREQUAL "x86_64" OR
      NOT meta_AddressSize STREQUAL "64bit" OR
      NOT header_ImageFileHeader_Machine STREQUAL "IMAGE_FILE_MACHINE_AMD64 (0x8664)" OR
      NOT header_ImageOptionalHeader_Magic STREQUAL "0x20B" OR
      NOT header_DOSHeader_Magic STREQUAL "MZ")
    message(FATAL_ERROR "pure-gl PE: AMD64 PE32+ headers required for ${path}")
  endif()
  math(EXPR required_file_flags "${header_ImageFileHeader_Characteristics} & 0x22")
  math(EXPR forbidden_file_flags "${header_ImageFileHeader_Characteristics} & 0x8180")
  math(EXPR dll_flag "${header_ImageFileHeader_Characteristics} & 0x2000")
  math(EXPR required_optional_flags "${header_ImageOptionalHeader_Characteristics} & 0x160")
  string(TOLOWER "${path}" lower_path)
  if(NOT required_file_flags EQUAL 0x22 OR NOT forbidden_file_flags EQUAL 0 OR
      NOT required_optional_flags EQUAL 0x160 OR
      (lower_path MATCHES "\\.dll$" AND NOT dll_flag EQUAL 0x2000) OR
      (lower_path MATCHES "\\.exe$" AND NOT dll_flag EQUAL 0))
    message(FATAL_ERROR "pure-gl PE: required AMD64 PE32+ Characteristics semantics for ${path}")
  endif()
  if(NOT header_DataDirectory_DelayImportDescriptorRVA STREQUAL "0x0" OR
      NOT header_DataDirectory_DelayImportDescriptorSize STREQUAL "0x0")
    message(FATAL_ERROR "pure-gl PE: absent/malformed/nonzero delay import directory for ${path}")
  endif()
  if(NOT header_ImageFileHeader_OptionalHeaderSize STREQUAL "240" OR
      NOT header_ImageOptionalHeader_NumberOfRvaAndSize STREQUAL "16")
    message(FATAL_ERROR "pure-gl PE: unsupported PE header layout for ${path}")
  endif()
  foreach(field BoundImportRVA BoundImportSize CLRRuntimeHeaderRVA CLRRuntimeHeaderSize ReservedRVA ReservedSize)
    if(NOT header_DataDirectory_${field} STREQUAL "0x0")
      message(FATAL_ERROR "pure-gl PE: unsupported PE directory ${field} for ${path}")
    endif()
  endforeach()
  list(SORT imports)
  set(${output} "${imports}" PARENT_SCOPE)
endfunction()
