cmake_minimum_required(VERSION 3.25)
include("${CMAKE_CURRENT_LIST_DIR}/PeHelpers.cmake")
cmake_host_system_information(RESULT install_windows_root QUERY WINDOWS_REGISTRY
  "HKLM/SOFTWARE/Microsoft/Windows NT/CurrentVersion" VALUE SystemRoot)
file(TO_CMAKE_PATH "${install_windows_root}/System32" install_system)
set(GL_PE_POWERSHELL "${install_system}/WindowsPowerShell/v1.0/powershell.exe")
function(gl_install_path path kind output)
  file(TO_CMAKE_PATH "${path}" path)
  gl_pe_path("${path}" "${kind}")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
function(gl_install_no_reparse)
  if(EXISTS "${GL_INSTALL_GUARD}")
    foreach(path IN LISTS ARGN)
      gl_pe_path("${path}" any)
    endforeach()
    execute_process(COMMAND "${GL_INSTALL_GUARD}" --check-paths ${ARGN}
      RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    if(NOT rc EQUAL 0)
      message(FATAL_ERROR "install audit: native no-reparse validation failed\n${out}${err}")
    endif()
  else()
    gl_pe_no_reparse(${ARGN})
  endif()
endfunction()
function(gl_install_windows_authority)
  gl_pe_equal_path("${PURE_GL_WINDOWS_SYSTEM_DIRECTORY}" "${install_system}")
endfunction()

function(install_relative path)
  string(TOLOWER "${path}" lower)
  if(NOT path MATCHES "^[A-Za-z0-9_+.-]+(/[A-Za-z0-9_+.-]+)*$" OR
      path MATCHES "(^|/)\\.\\.?(/|$)" OR path MATCHES "[.](/|$)" OR
      lower MATCHES "(^|/)(con|prn|aux|nul|com[0-9]|lpt[0-9])([./]|$)")
    message(FATAL_ERROR "install audit: malformed relative path ${path}")
  endif()
endfunction()
function(install_rows text output)
  if(text MATCHES "[;\r]" OR text MATCHES "\n\n" OR NOT text MATCHES "\n$")
    message(FATAL_ERROR "install audit: malformed record stream")
  endif()
  string(REGEX REPLACE "\n$" "" text "${text}")
  string(REPLACE "\n" ";" rows "${text}")
  set(${output} "${rows}" PARENT_SCOPE)
endfunction()
function(install_tree root output)
  if(DEFINED ENV{PURE_GL_INSTALL_CHANNEL} AND root STREQUAL STAGE_PREFIX AND
      NOT GL_INSTALL_MODE STREQUAL "seal")
    execute_process(COMMAND "${GL_INSTALL_GUARD}" --tree --scope "${STAGE_PREFIX}" "${GL_INSTALL_BUILD_DIR}"
      RESULT_VARIABLE rc OUTPUT_VARIABLE content ERROR_VARIABLE err TIMEOUT 40)
    if(NOT rc EQUAL 0)
      message(FATAL_ERROR "install audit: retained tree snapshot failed (${rc})\n${err}")
    endif()
    install_rows("${content}" rows)
    set(seen)
    foreach(row IN LISTS rows)
      string(REPLACE "|" ";" fields "${row}")
      list(LENGTH fields count)
      if(NOT count EQUAL 4)
        message(FATAL_ERROR "install audit: malformed retained tree record")
      endif()
      list(GET fields 0 path)
      install_relative("${path}")
      string(TOLOWER "${path}" lower)
      if(lower IN_LIST seen)
        message(FATAL_ERROR "install audit: case-ambiguous retained tree")
      endif()
      list(APPEND seen "${lower}")
    endforeach()
    list(SORT rows)
    set(${output} "${rows}" PARENT_SCOPE)
    return()
  endif()
  gl_install_path("${root}" directory root)
  gl_install_no_reparse("${root}")
  if(EXISTS "${GL_INSTALL_GUARD}")
    execute_process(COMMAND "${GL_INSTALL_GUARD}" --check-tree "${root}" RESULT_VARIABLE rc TIMEOUT 30)
    if(NOT rc EQUAL 0)
      message(FATAL_ERROR "install audit: non-regular, reparse or hardlinked tree")
    endif()
  endif()
  # CMP0009 prohibits link traversal; validate every discovered endpoint and
  # ancestor before hashing. Empty directories are part of the exact contract.
  file(GLOB_RECURSE paths LIST_DIRECTORIES TRUE RELATIVE "${root}" "${root}/*")
  list(SORT paths)
  set(absolute)
  set(seen)
  foreach(path IN LISTS paths)
    install_relative("${path}")
    string(TOLOWER "${path}" folded)
    if(folded IN_LIST seen)
      message(FATAL_ERROR "install audit: case-ambiguous tree path ${path}")
    endif()
    list(APPEND seen "${folded}")
    list(APPEND absolute "${root}/${path}")
  endforeach()
  if(absolute AND NOT EXISTS "${GL_INSTALL_GUARD}")
    gl_install_no_reparse(${absolute})
  endif()
  set(rows)
  foreach(path IN LISTS paths)
    if(IS_DIRECTORY "${root}/${path}")
      list(APPEND rows "${path}|d|0|-")
    else()
      file(SIZE "${root}/${path}" size)
      file(SHA256 "${root}/${path}" hash)
      list(APPEND rows "${path}|f|${size}|${hash}")
    endif()
  endforeach()
  list(SORT rows)
  set(${output} "${rows}" PARENT_SCOPE)
endfunction()
function(install_guard_operation operation)
  if(operation STREQUAL "--queue-write" OR operation STREQUAL "--write")
    execute_process(COMMAND "${GL_INSTALL_GUARD}" "${operation}" "${ARGV1}" "${ARGV2}"
      --scope "${STAGE_PREFIX}" "${GL_INSTALL_BUILD_DIR}" RESULT_VARIABLE rc TIMEOUT 40)
  else()
    execute_process(COMMAND "${GL_INSTALL_GUARD}" ${ARGV}
      --scope "${STAGE_PREFIX}" "${GL_INSTALL_BUILD_DIR}" RESULT_VARIABLE rc TIMEOUT 40)
  endif()
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "install audit: guarded operation failed (${rc})")
  endif()
endfunction()
function(install_queue_rows path rows)
  list(JOIN rows "\n" content)
  if(rows)
    string(APPEND content "\n")
  endif()
  install_guard_operation(--queue-write "${path}" "${content}")
endfunction()
function(install_read_tree path output)
  gl_install_path("${path}" file checked)
  gl_install_no_reparse("${checked}")
  file(READ "${path}" content)
  install_rows("${content}" rows)
  set(seen)
  foreach(row IN LISTS rows)
    string(REPLACE "|" ";" fields "${row}")
    list(LENGTH fields count)
    if(NOT count EQUAL 4)
      message(FATAL_ERROR "install audit: malformed tree manifest ${path}")
    endif()
    list(GET fields 0 name)
    list(GET fields 1 type)
    list(GET fields 2 size)
    list(GET fields 3 hash)
    install_relative("${name}")
    string(LENGTH "${hash}" length)
    string(TOLOWER "${name}" lower)
    if(lower IN_LIST seen OR NOT size MATCHES "^(0|[1-9][0-9]*)$" OR
        (type STREQUAL "f" AND (NOT hash MATCHES "^[a-f0-9]+$" OR NOT length EQUAL 64)) OR
        (type STREQUAL "d" AND (NOT size STREQUAL "0" OR NOT hash STREQUAL "-")) OR
        NOT type MATCHES "^[fd]$")
      message(FATAL_ERROR "install audit: duplicate/malformed tree manifest ${path}")
    endif()
    list(APPEND seen "${lower}")
  endforeach()
  set(sorted "${rows}")
  list(SORT sorted)
  if(NOT sorted STREQUAL rows)
    message(FATAL_ERROR "install audit: unsorted tree manifest ${path}")
  endif()
  set(${output} "${rows}" PARENT_SCOPE)
endfunction()
if(GL_INSTALL_HELPERS_ONLY)
  if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    message(FATAL_ERROR "install audit: helpers-only mode requires inclusion by a driver")
  endif()
  return()
endif()

# Enter the compiled owner before consuming configure output. A one-shot hash
# check cannot authorize a later include after its identity handles are closed.
gl_install_path("${GL_INSTALL_CONTEXT}" file GL_INSTALL_CONTEXT)
gl_install_no_reparse("${GL_INSTALL_CONTEXT}")
get_filename_component(configured_build "${GL_INSTALL_CONTEXT}" DIRECTORY)
set(configured_guard "${configured_build}/pure-gl-install-guard.exe")
gl_install_no_reparse("${configured_guard}")
if(NOT DEFINED GL_INSTALL_MODE)
  set(GL_INSTALL_MODE verify)
endif()
if(NOT GL_INSTALL_MODE MATCHES "^(seal|install|verify)$")
  message(FATAL_ERROR "install audit: unknown operation")
endif()
set(GL_INSTALL_GUARD "${configured_guard}")
set(GL_INSTALL_BUILD_DIR "${configured_build}")
if(GL_INSTALL_MODE STREQUAL "seal")
  set(STAGE_PREFIX "${configured_build}")
endif()
gl_install_path("${STAGE_PREFIX}" directory STAGE_PREFIX)
if(NOT DEFINED ENV{PURE_GL_INSTALL_CHANNEL})
  execute_process(COMMAND "${configured_guard}" --run "${STAGE_PREFIX}" "${configured_build}"
    "${CMAKE_COMMAND}" "${GL_INSTALL_CONTEXT}" "${CMAKE_CURRENT_LIST_FILE}"
    "${GL_INSTALL_MODE}" "${GL_INSTALL_COMPONENT}" RESULT_VARIABLE owner_rc TIMEOUT 260)
  if(NOT owner_rc EQUAL 0)
    message(FATAL_ERROR "install audit: exclusive guarded operation failed (${owner_rc})")
  endif()
  return()
endif()
install_guard_operation(--probe)
include("${GL_INSTALL_CONTEXT}")
include("${GL_INSTALL_COMPLETED_SEAL}")
gl_install_windows_authority()
gl_pe_equal_path("${GL_INSTALL_GUARD}" "${configured_guard}")
gl_install_path("${GL_INSTALL_GUARD}" file GL_INSTALL_GUARD)
gl_install_no_reparse("${GL_INSTALL_GUARD}" "${GL_INSTALL_BUILD_DIR}")
install_rows("${GL_INSTALL_TRUSTED_SOURCES}" trusted_sources)
set(trusted_paths)
foreach(row IN LISTS trusted_sources)
  string(REPLACE "|" ";" fields "${row}")
  list(LENGTH fields count)
  if(NOT count EQUAL 2)
    message(FATAL_ERROR "install audit: malformed trusted source identity")
  endif()
  list(GET fields 0 path)
  list(GET fields 1 hash)
  gl_pe_pin("${path}" "${hash}")
  list(APPEND trusted_paths "${path}")
endforeach()
gl_install_no_reparse(${trusted_paths})

install_rows("${GL_INSTALL_POLICY}" policy)
set(sealed)
set(destinations)
set(sources "${GL_INSTALL_CONTEXT}")
foreach(row IN LISTS policy)
  string(REPLACE "|" ";" fields "${row}")
  list(LENGTH fields count)
  if(NOT count EQUAL 9)
    message(FATAL_ERROR "install audit: malformed artifact policy")
  endif()
  list(GET fields 0 component)
  list(GET fields 1 destination)
  list(GET fields 2 source)
  list(GET fields 3 expected)
  list(GET fields 8 mapping)
  install_relative("${destination}")
  string(TOLOWER "${destination}" lower)
  if(lower IN_LIST destinations OR NOT component MATCHES "^(runtime|documentation)$" OR mapping STREQUAL "")
    message(FATAL_ERROR "install audit: duplicate destination, component or license mapping")
  endif()
  list(APPEND destinations "${lower}")
  gl_install_path("${source}" file source)
  list(APPEND sources "${source}")
  file(SHA256 "${source}" hash)
  file(SIZE "${source}" size)
  if(expected STREQUAL "NATIVE_COMPLETED_MODULE" AND
      source STREQUAL "${GL_INSTALL_BUILD_DIR}/pure-gl.dll")
    set(expected "${GL_INSTALL_MODULE_SHA256}")
  endif()
  if(NOT hash STREQUAL expected)
    message(FATAL_ERROR "install audit: configured source hash mismatch: ${source}")
  endif()
  list(GET fields 4 project)
  list(GET fields 5 version)
  list(GET fields 6 url)
  list(GET fields 7 license)
  if(destination STREQUAL "bin/libfreeglut.dll" OR
      destination STREQUAL "share/doc/pure-gl/licenses/FreeGLUT.txt")
    if(destination STREQUAL "bin/libfreeglut.dll")
      gl_pe_equal_path("${source}" "${PURE_GL_CLANG64_PREFIX}/bin/libfreeglut.dll")
      set(pinned a297e3b3fa824de6eb21285e23a409fbbf0bc573c60dd04c227bbc89d8398519)
      set(want_component runtime)
    else()
      gl_pe_equal_path("${source}" "${PURE_GL_CLANG64_PREFIX}/share/licenses/freeglut/COPYING")
      set(pinned b6593d5ec4c113a274abb85b10e8615895cb0ddb89f7912af5fe5aa8df38a275)
      set(want_component documentation)
    endif()
    if(NOT hash STREQUAL pinned OR NOT expected STREQUAL pinned OR
        NOT project STREQUAL FreeGLUT OR NOT version STREQUAL "3.8.0" OR
        NOT url STREQUAL "https://github.com/FreeGLUTProject/freeglut/releases/download/v3.8.0/freeglut-3.8.0.tar.gz" OR
        NOT license STREQUAL MIT OR NOT component STREQUAL want_component OR
        NOT mapping STREQUAL "share/doc/pure-gl/licenses/FreeGLUT.txt")
      message(FATAL_ERROR "install audit: FreeGLUT runtime/license identity mismatch")
    endif()
  elseif(NOT project STREQUAL pure-gl OR NOT version STREQUAL "0.9" OR
      NOT url STREQUAL "https://github.com/agraef/pure-lang/tree/master/pure-gl" OR
      NOT license STREQUAL BSD-3-Clause OR NOT mapping STREQUAL "share/doc/pure-gl/COPYING")
    message(FATAL_ERROR "install audit: pure-gl package/license identity mismatch")
  endif()
  list(REMOVE_AT fields 3)
  list(INSERT fields 3 "${hash}")
  list(JOIN fields "|" row)
  list(APPEND sealed "${row}")
  list(APPEND delta_${component} "${destination}|f|${size}|${hash}")
endforeach()
gl_install_no_reparse(${sources})
list(LENGTH sealed artifact_count)
list(LENGTH delta_runtime runtime_count)
list(LENGTH delta_documentation documentation_count)
if(NOT runtime_count EQUAL 9 OR NOT documentation_count EQUAL 17)
  message(FATAL_ERROR "install audit: incomplete component inventory")
endif()
list(SORT sealed)
list(JOIN sealed "\n" inventory)
string(APPEND inventory "\n")
string(SHA256 inventory_hash "${inventory}")
set(had_inventory FALSE)
if(EXISTS "${GL_INSTALL_INVENTORY}" OR EXISTS "${GL_INSTALL_INVENTORY}.sha256")
  set(had_inventory TRUE)
endif()
if(GL_INSTALL_MODE STREQUAL "seal" AND NOT EXISTS "${GL_INSTALL_INVENTORY}" AND
    NOT EXISTS "${GL_INSTALL_INVENTORY}.sha256")
  install_guard_operation(--write "${GL_INSTALL_INVENTORY}" "${inventory}")
  install_guard_operation(--write "${GL_INSTALL_INVENTORY}.sha256" "${inventory_hash}\n")
endif()
gl_install_no_reparse("${GL_INSTALL_INVENTORY}" "${GL_INSTALL_INVENTORY}.sha256")
file(READ "${GL_INSTALL_INVENTORY}" recorded)
file(READ "${GL_INSTALL_INVENTORY}.sha256" pin)
file(SHA256 "${GL_INSTALL_INVENTORY}" inventory_bytes_hash)
if(NOT recorded STREQUAL inventory OR NOT pin STREQUAL "${inventory_hash}\n" OR
    NOT inventory_bytes_hash STREQUAL inventory_hash)
  message(FATAL_ERROR "install audit: frozen artifact inventory/source mismatch; use a fresh build for changed inputs")
endif()
foreach(row IN LISTS sealed)
  string(REPLACE "|" ";" fields "${row}")
  list(GET fields 4 project)
  list(GET fields 5 version)
  list(GET fields 6 url)
  list(GET fields 7 license)
  list(GET fields 8 mapping)
  set(found FALSE)
  foreach(candidate IN LISTS sealed)
    string(REPLACE "|" ";" c "${candidate}")
    list(GET c 0 cc)
    list(GET c 1 cd)
    list(GET c 4 cp)
    list(GET c 5 cv)
    list(GET c 6 cu)
    list(GET c 7 cl)
    if(cd STREQUAL mapping AND cc STREQUAL documentation AND cp STREQUAL project AND
        cv STREQUAL version AND cu STREQUAL url AND cl STREQUAL license)
      set(found TRUE)
    endif()
  endforeach()
  if(NOT found)
    message(FATAL_ERROR "install audit: runtime-to-license mismatch: ${mapping}")
  endif()
endforeach()
file(SHA256 "${GL_INSTALL_GUARD}" guard_hash)
if(had_inventory AND NOT EXISTS "${GL_INSTALL_BUILD_DIR}/install-guard.sha256")
  message(FATAL_ERROR "install audit: missing frozen native guard identity; use a fresh build")
endif()
if(GL_INSTALL_MODE STREQUAL seal AND NOT EXISTS "${GL_INSTALL_BUILD_DIR}/install-guard.sha256")
  install_guard_operation(--write "${GL_INSTALL_BUILD_DIR}/install-guard.sha256" "${guard_hash}\n")
endif()
gl_install_no_reparse("${GL_INSTALL_BUILD_DIR}/install-guard.sha256")
file(READ "${GL_INSTALL_BUILD_DIR}/install-guard.sha256" guard_pin)
if(NOT guard_pin STREQUAL "${guard_hash}\n")
  message(FATAL_ERROR "install audit: frozen native guard identity mismatch")
endif()
file(SHA256 "${GL_INSTALL_RUNNER}" runner_hash)
if(NOT runner_hash STREQUAL GL_INSTALL_RUNNER_SHA256)
  message(FATAL_ERROR "install audit: completed runner identity mismatch")
endif()
set(runner_pin_file "${GL_INSTALL_BUILD_DIR}/install-runner.sha256")
if(GL_INSTALL_MODE STREQUAL seal AND NOT had_inventory AND NOT EXISTS "${runner_pin_file}")
  install_guard_operation(--write "${runner_pin_file}" "${runner_hash}\n")
endif()
gl_install_no_reparse("${runner_pin_file}" "${GL_INSTALL_RUNNER}")
file(READ "${runner_pin_file}" runner_pin)
if(NOT runner_pin STREQUAL "${runner_hash}\n")
  message(FATAL_ERROR "install audit: frozen authenticated runner identity mismatch")
endif()
install_tree("${PURE_GL_PURE_PREFIX}" source_baseline)
install_rows("${GL_INSTALL_BASELINE_POLICY}" baseline)
gl_install_path("${GL_INSTALL_BASELINE_PIN}" file baseline_pin)
gl_install_no_reparse("${baseline_pin}")
file(READ "${baseline_pin}" frozen_baseline)
file(SHA256 "${baseline_pin}" baseline_hash)
if(NOT frozen_baseline STREQUAL GL_INSTALL_BASELINE_POLICY OR
    NOT baseline_hash STREQUAL GL_INSTALL_BASELINE_SHA256)
  message(FATAL_ERROR "install audit: frozen portable baseline identity mismatch; use a fresh build")
endif()
if(NOT source_baseline STREQUAL baseline)
  message(FATAL_ERROR "install audit: configured portable Pure baseline changed")
endif()
# Derive directory ownership from the canonical baseline and fixed artifact
# destinations. Shared existing ancestors remain baseline; no overlapping deltas.
foreach(component runtime documentation)
  foreach(row IN LISTS delta_${component})
    string(REPLACE "|" ";" fields "${row}")
    list(GET fields 0 destination)
    get_filename_component(parent "${destination}" DIRECTORY)
    while(NOT parent STREQUAL "")
      if(NOT "${parent}|d|0|-" IN_LIST baseline)
        list(APPEND dirs_${component} "${parent}|d|0|-")
      endif()
      get_filename_component(parent "${parent}" DIRECTORY)
    endwhile()
  endforeach()
  list(APPEND delta_${component} ${dirs_${component}})
  list(REMOVE_DUPLICATES delta_${component})
  list(SORT delta_${component})
endforeach()
set(owned_paths)
foreach(component runtime documentation)
  foreach(row IN LISTS delta_${component})
    string(REPLACE "|" ";" fields "${row}")
    list(GET fields 0 path)
    string(TOLOWER "${path}" lower)
    if(lower IN_LIST owned_paths)
      message(FATAL_ERROR "install audit: overlapping component delta")
    endif()
    list(APPEND owned_paths "${lower}")
  endforeach()
endforeach()
foreach(row IN LISTS baseline)
  string(REPLACE "|" ";" fields "${row}")
  list(GET fields 0 path)
  string(TOLOWER "${path}" lower)
  if(lower IN_LIST owned_paths)
    message(FATAL_ERROR "install audit: baseline collides with pure-gl package delta: ${path}")
  endif()
endforeach()
if(GL_INSTALL_MODE STREQUAL seal)
  message(STATUS "PURE_GL_INSTALL_INVENTORY_SEALED artifacts=26 runtime=9 documentation=17")
  return()
endif()
if(DEFINED ENV{DESTDIR} AND NOT "$ENV{DESTDIR}" STREQUAL "")
  message(FATAL_ERROR "install audit: DESTDIR is not supported")
endif()
gl_install_path("${STAGE_PREFIX}" directory STAGE_PREFIX)
gl_install_no_reparse("${STAGE_PREFIX}")
string(TOLOWER "${STAGE_PREFIX}" stage_casefolded)
string(TOLOWER "${PURE_GL_PURE_PREFIX}" baseline_casefolded)
cmake_path(IS_PREFIX baseline_casefolded "${stage_casefolded}" NORMALIZE stage_in_baseline)
cmake_path(IS_PREFIX stage_casefolded "${baseline_casefolded}" NORMALIZE baseline_in_stage)
if(stage_in_baseline OR baseline_in_stage)
  message(FATAL_ERROR "install audit: stage must be separate from configured portable Pure baseline")
endif()
set(stage "${STAGE_PREFIX}")
string(TOLOWER "${stage}" stage_key)
string(SHA256 stage_key "${stage_key}")
set(session "${GL_INSTALL_BUILD_DIR}/install-audits/${stage_key}")
install_tree("${stage}" current)
set(expected_tree "${baseline}")
if(EXISTS "${session}/baseline.tsv")
  install_read_tree("${session}/baseline.tsv" preserved)
  if(NOT preserved STREQUAL baseline)
    message(FATAL_ERROR "install audit: preserved baseline differs from configured canonical baseline")
  endif()
elseif(GL_INSTALL_MODE STREQUAL verify)
  message(FATAL_ERROR "install audit: missing baseline manifest")
endif()
foreach(component runtime documentation)
  if(EXISTS "${session}/${component}.tsv")
    install_read_tree("${session}/${component}.tsv" preserved)
    if(NOT preserved STREQUAL delta_${component})
      message(FATAL_ERROR "install audit: ${component} manifest missing/extra/cross-component entry")
    endif()
    list(APPEND expected_tree ${preserved})
    set(installed_${component} TRUE)
  elseif(GL_INSTALL_MODE STREQUAL verify)
    message(FATAL_ERROR "install audit: missing ${component} manifest")
  endif()
endforeach()
list(SORT expected_tree)
if(NOT current STREQUAL expected_tree)
  message(FATAL_ERROR "install audit: tree differs from byte-identical canonical baseline plus declared disjoint delta (collision, missing or extra path)")
endif()
if(GL_INSTALL_MODE STREQUAL install)
  if(NOT GL_INSTALL_COMPONENT MATCHES "^(runtime|documentation|all)$")
    message(FATAL_ERROR "install audit: unknown component")
  endif()
  if(NOT EXISTS "${session}/baseline.tsv")
    install_queue_rows("${session}/baseline.tsv" "${baseline}")
  endif()
  foreach(row IN LISTS sealed)
    string(REPLACE "|" ";" fields "${row}")
    list(GET fields 0 component)
    list(GET fields 1 destination)
    list(GET fields 2 source)
    list(GET fields 3 hash)
    if(installed_${component})
      continue()
    endif()
    if(component STREQUAL GL_INSTALL_COMPONENT OR GL_INSTALL_COMPONENT STREQUAL all)
      install_guard_operation(--copy "${source}" "${stage}/${destination}" "${hash}")
    else()
      install_guard_operation(--reserve "${stage}/${destination}")
    endif()
  endforeach()
  foreach(component runtime documentation)
    if(NOT component STREQUAL GL_INSTALL_COMPONENT AND NOT GL_INSTALL_COMPONENT STREQUAL all)
      continue()
    endif()
    if(NOT installed_${component})
      install_queue_rows("${session}/${component}.tsv" "${delta_${component}}")
      list(APPEND expected_tree ${delta_${component}})
    endif()
    set(manifest)
    foreach(row IN LISTS delta_${component})
      string(REPLACE "|" ";" fields "${row}")
      list(GET fields 0 destination)
      list(GET fields 1 type)
      if(type STREQUAL f)
        list(APPEND manifest "${stage}/${destination}")
      endif()
    endforeach()
    install_queue_rows("${GL_INSTALL_BUILD_DIR}/install_manifest_${component}.txt" "${manifest}")
  endforeach()
  install_guard_operation(--publish)
  install_tree("${stage}" after)
  list(SORT expected_tree)
  if(NOT after STREQUAL expected_tree)
    message(FATAL_ERROR "install audit: post-install tree mismatch")
  endif()
  install_guard_operation(--checked)
  message(STATUS "INSTALL_COMPONENT_OK component=${GL_INSTALL_COMPONENT} manifests=${session}")
  return()
endif()

# Both functional tests consume only the stage and run outside source/build.
# The installed FreeGLUT directory is also Pure/bin. Pass it only once: the
# Task 1 supervisor deliberately rejects duplicate runtime PATH entries.
set(staged_inputs)
foreach(name GL GL_ARB GL_EXT GL_NV GL_ATI GLU GLUT)
  list(APPEND staged_inputs --input "${stage}/lib/pure/${name}.pure")
endforeach()
# Pure 0.68 mixes its UTF-8 default libdir with narrow Windows CRT file APIs.
# Only the executable spelling uses a verified Windows ASCII alias of the same
# physical stage. Every ownership/hash/provenance/script/module path stays canonical.
execute_process(COMMAND "${GL_INSTALL_RUNNER}" --print-pure-executable-alias "${stage}/bin/pure.exe"
  RESULT_VARIABLE alias_rc OUTPUT_VARIABLE staged_pure_alias ERROR_VARIABLE alias_err
  OUTPUT_STRIP_TRAILING_WHITESPACE TIMEOUT 20)
if(NOT alias_rc EQUAL 0 OR staged_pure_alias STREQUAL "" OR NOT alias_err STREQUAL "")
  message(FATAL_ERROR "install audit: same-stage ASCII executable alias unavailable (${alias_rc}): ${alias_err}")
endif()
foreach(case load hidden-render)
  execute_process(COMMAND "${GL_INSTALL_RUNNER}"
    --pure "${stage}/bin/pure.exe"
    --pure-executable-alias "${staged_pure_alias}"
    --script "${stage}/share/doc/pure-gl/tests/${case}.pure"
    --timeout-ms 90000 --cwd "${install_windows_root}"
    ${staged_inputs} --input "${stage}/lib/pure/pure-gl.dll"
    --input "${stage}/bin/libfreeglut.dll" --include "${stage}/lib/pure"
    --library "${stage}/lib/pure" --path-entry "${stage}/bin"
    --path-entry "${stage}/lib/pure" --path-entry "${PURE_GL_WINDOWS_SYSTEM_DIRECTORY}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 100)
  if(NOT rc EQUAL 0 OR NOT err STREQUAL "")
    message(FATAL_ERROR "install audit: staged ${case} failed (${rc})\n${out}${err}")
  endif()
  message(STATUS "${out}")
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}"
  "-DLLVM_READOBJ=${LLVM_READOBJ_EXECUTABLE}"
  "-DLLVM_READOBJ_SHA256=${LLVM_READOBJ_SHA256}"
  "-DLLVM_STRINGS=${LLVM_STRINGS_EXECUTABLE}"
  "-DLLVM_STRINGS_SHA256=${LLVM_STRINGS_SHA256}"
  "-DPURE_GL_MODULE=${stage}/lib/pure/pure-gl.dll"
  "-DFREEGLUT_DLL=${stage}/bin/libfreeglut.dll"
  "-DPURE_GL_PURE_PREFIX=${stage}"
  "-DPURE_GL_CLANG64_PREFIX=${PURE_GL_CLANG64_PREFIX}"
  "-DPURE_GL_WINDOWS_SYSTEM_DIRECTORY=${PURE_GL_WINDOWS_SYSTEM_DIRECTORY}"
  "-DPURE_GL_RUNTIME_DIRECTORY=${stage}/bin" -DPURE_GL_AUDIT_MODE=INSTALLED
  -P "${CMAKE_CURRENT_LIST_DIR}/VerifyWindowsDependencies.cmake"
  RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 120)
if(NOT rc EQUAL 0 OR NOT err STREQUAL "" OR NOT out MATCHES "PURE_GL_PE_OK AMD64 non-system=12 imports=141 system=10")
  message(FATAL_ERROR "install audit: staged recursive PE closure failed\n${out}${err}")
endif()
message(STATUS "${out}")
install_tree("${stage}" final)
if(NOT final STREQUAL expected_tree)
  message(FATAL_ERROR "install audit: installed tests changed the exact stage")
endif()
list(LENGTH baseline baseline_count)
list(LENGTH final final_count)
set(delta_dirs ${dirs_runtime} ${dirs_documentation})
list(REMOVE_DUPLICATES delta_dirs)
list(LENGTH delta_dirs directory_count)
set(baseline_files 0)
foreach(row IN LISTS baseline)
  if(row MATCHES "[|]f[|]")
    math(EXPR baseline_files "${baseline_files}+1")
  endif()
endforeach()
math(EXPR baseline_dirs "${baseline_count}-${baseline_files}")
message(STATUS "PURE_GL_INSTALL_PACKAGE_OK baseline=${baseline_count} baseline_files=${baseline_files} baseline_directories=${baseline_dirs} runtime=${runtime_count} documentation=${documentation_count} delta_files=${artifact_count} delta_directories=${directory_count} final=${final_count} pe=22 installed_tests=2 license_payloads=1")
