cmake_minimum_required(VERSION 3.25)
foreach(required IN ITEMS MODULE_DLL MODULE_SOURCE LLVM_READOBJ_EXECUTABLE)
  if(NOT DEFINED ${required} OR NOT EXISTS "${${required}}")
    message(FATAL_ERROR "${required} must name an existing file")
  endif()
endforeach()
execute_process(COMMAND "${LLVM_READOBJ_EXECUTABLE}" --file-headers
  --coff-exports --coff-imports "${MODULE_DLL}"
  RESULT_VARIABLE result OUTPUT_VARIABLE pe ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "llvm-readobj failed:\n${pe}${error}")
endif()
if(NOT pe MATCHES "Format: COFF-x86-64" OR
    NOT pe MATCHES "Machine: IMAGE_FILE_MACHINE_AMD64")
  message(FATAL_ERROR "Module is not an AMD64 PE image:\n${pe}")
endif()
string(REGEX MATCHALL "Name: [^\r\n]+" name_lines "${pe}")
set(exports)
set(imports)
foreach(line IN LISTS name_lines)
  string(REPLACE "Name: " "" name "${line}")
  if(name MATCHES "\\.dll$")
    string(TOLOWER "${name}" name)
    list(APPEND imports "${name}")
  else()
    list(APPEND exports "${name}")
  endif()
endforeach()
file(STRINGS "${MODULE_SOURCE}" declarations REGEX "^extern .+\\);")
set(expected_exports)
foreach(declaration IN LISTS declarations)
  string(REGEX MATCH "([A-Za-z_][A-Za-z0-9_]*)\\(" match "${declaration}")
  list(APPEND expected_exports "${CMAKE_MATCH_1}")
endforeach()
list(REMOVE_DUPLICATES expected_exports)
list(SORT expected_exports)
list(SORT exports)
if(NOT exports STREQUAL expected_exports)
  message(FATAL_ERROR
    "PE exports differ from the Pure extern contract. Expected "
    "'${expected_exports}', got '${exports}'")
endif()
set(expected_imports api-ms-win-crt-heap-l1-1-0.dll
  api-ms-win-crt-private-l1-1-0.dll
  api-ms-win-crt-runtime-l1-1-0.dll api-ms-win-crt-stdio-l1-1-0.dll
  api-ms-win-crt-string-l1-1-0.dll kernel32.dll libc++.dll libpure.dll)
get_filename_component(module_name "${MODULE_SOURCE}" NAME_WE)
if(module_name STREQUAL "hashdict")
  list(APPEND expected_imports api-ms-win-crt-math-l1-1-0.dll)
endif()
list(SORT expected_imports)
list(SORT imports)
if(NOT imports STREQUAL expected_imports)
  message(FATAL_ERROR "Unexpected imports. Expected '${expected_imports}', got '${imports}'")
endif()
if(pe MATCHES
    "(__cxa_throw|__cxa_allocate_exception|__gxx_personality|_Unwind_|_ZSt9terminate)")
  message(FATAL_ERROR "C++ exception ABI import crossed the module boundary")
endif()
