include_guard(GLOBAL)
function(gl_audit_require_disjoint_layout)
  file(REAL_PATH "${SOURCE_DIR}" source_root)
  file(REAL_PATH "${BINARY_DIR}" build_root)
  if(CMAKE_HOST_WIN32)
    string(TOLOWER "${source_root}" source_root)
    string(TOLOWER "${build_root}" build_root)
  endif()
  cmake_path(IS_PREFIX source_root "${build_root}" NORMALIZE build_beneath_source)
  cmake_path(IS_PREFIX build_root "${source_root}" NORMALIZE source_beneath_build)
  if(build_beneath_source OR source_beneath_build)
    message(FATAL_ERROR "Source/build layouts overlap; release contracts require disjoint source and build trees")
  endif()
endfunction()
# All recursive cleanup goes through the compiled native authority. These
# functions never accept a cleanup path from their caller.
function(gl_audit_open leaf output)
  if(NOT leaf MATCHES "^(configure-contract|runner-contract|render-contract|source-dist-contract|source-dist-input|cleanup-contract)$")
    message(FATAL_ERROR "Unknown fixed audit leaf")
  endif()
  set(guard "${BINARY_DIR}/pure-gl-install-guard.exe")
  execute_process(COMMAND "${guard}" --check-paths "${BINARY_DIR}" "${SOURCE_DIR}"
    RESULT_VARIABLE rc ERROR_VARIABLE err)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Audit authority path rejected: ${err}")
  endif()
  set(root "${BINARY_DIR}/pure-gl-audits")
  set(root_owner "pure-gl audit root\nbuild=${BINARY_DIR}\nsource=${SOURCE_DIR}\n")
  if(EXISTS "${root}")
    execute_process(COMMAND "${guard}" --check-paths "${root}" "${root}/.pure-gl-owner"
      RESULT_VARIABLE rc ERROR_VARIABLE err)
    if(NOT rc EQUAL 0)
      message(FATAL_ERROR "Audit root rejected: ${err}")
    endif()
    file(READ "${root}/.pure-gl-owner" actual)
    if(NOT actual STREQUAL root_owner)
      message(FATAL_ERROR "Audit root sentinel mismatch")
    endif()
  else()
    file(MAKE_DIRECTORY "${root}")
    file(WRITE "${root}/.pure-gl-owner" "${root_owner}")
  endif()
  if(EXISTS "${root}/${leaf}")
    gl_audit_clean("${leaf}")
  endif()
  file(MAKE_DIRECTORY "${root}/${leaf}")
  file(WRITE "${root}/${leaf}/.pure-gl-owner"
    "pure-gl audit leaf\nleaf=${leaf}\nbuild=${BINARY_DIR}\nsource=${SOURCE_DIR}\n")
  set(${output} "${root}/${leaf}" PARENT_SCOPE)
endfunction()

function(gl_audit_clean leaf)
  execute_process(COMMAND "${BINARY_DIR}/pure-gl-install-guard.exe" --clean-audit "${leaf}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 60)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Owned audit cleanup refused (${rc}): ${out}${err}")
  endif()
endfunction()

function(gl_audit_run name)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE rc OUTPUT_VARIABLE out
    ERROR_VARIABLE err TIMEOUT 1500)
  file(WRITE "${work}/${name}.log" "exit=${rc}\n${out}${err}")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "${name} failed (${rc}): ${out}${err}")
  endif()
  message(STATUS "AUDIT_CASE_OK ${name}")
  set(last_output "${out}${err}" PARENT_SCOPE)
endfunction()
