cmake_minimum_required(VERSION 3.25)
# The native authority must reject changed build outputs even when their mutable
# data sidecars describe the changed bytes consistently. Restore before failing.
set(failures)
include("${BINARY_DIR}/pure-gl-install-context.cmake")
foreach(kind module runner)
  if(kind STREQUAL module)
    set(artifact "${BINARY_DIR}/pure-gl.dll")
    set(sidecar "${BINARY_DIR}/pure-gl-install-inventory.tsv")
  else()
    set(artifact "${BINARY_DIR}/pure-gl-test-runner.exe")
    set(sidecar "${BINARY_DIR}/install-runner.sha256")
  endif()
  file(COPY_FILE "${artifact}" "${artifact}.contract-saved")
  file(READ "${sidecar}" saved_sidecar)
  file(COPY_FILE "${sidecar}" "${sidecar}.contract-saved")
  if(kind STREQUAL module)
    file(READ "${sidecar}.sha256" saved_pin)
    file(COPY_FILE "${sidecar}.sha256" "${sidecar}.sha256.contract-saved")
  endif()
  file(SHA256 "${artifact}" original_hash)
  foreach(case missing modified coordinated)
    if(case STREQUAL missing)
      file(RENAME "${artifact}" "${artifact}.contract-missing")
    else()
      file(APPEND "${artifact}" "\nBUILD_AUTHORITY_CONTRACT\n")
      if(case STREQUAL coordinated)
        file(SHA256 "${artifact}" changed_hash)
        string(REPLACE "${original_hash}" "${changed_hash}" updated "${saved_sidecar}")
        file(WRITE "${sidecar}" "${updated}")
        if(kind STREQUAL module)
          file(SHA256 "${sidecar}" updated_hash)
          file(WRITE "${sidecar}.sha256" "${updated_hash}\n")
        endif()
      endif()
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}"
      "-DGL_INSTALL_CONTEXT=${BINARY_DIR}/pure-gl-install-context.cmake"
      -DGL_INSTALL_MODE=seal -P "${GL_INSTALL_SCRIPT}"
      RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(case STREQUAL missing)
      file(RENAME "${artifact}.contract-missing" "${artifact}")
    endif()
    file(COPY_FILE "${artifact}.contract-saved" "${artifact}")
    file(COPY_FILE "${sidecar}.contract-saved" "${sidecar}")
    if(kind STREQUAL module)
      file(COPY_FILE "${sidecar}.sha256.contract-saved" "${sidecar}.sha256")
    endif()
    if(rc EQUAL 0 OR NOT err MATCHES "completed ${kind} identity")
      list(APPEND failures "${kind}/${case}: accepted or unrelated rejection (${rc}) ${err}")
    else()
      message(STATUS "BUILT_AUTHORITY_REJECT_OK ${kind}/${case}")
    endif()
  endforeach()
  file(REMOVE "${artifact}.contract-saved")
  file(REMOVE "${sidecar}.contract-saved")
  if(kind STREQUAL module)
    file(REMOVE "${sidecar}.sha256.contract-saved")
  endif()
endforeach()
set(seal "${BINARY_DIR}/pure-gl-built-authority.cmake")
file(READ "${seal}" saved_seal)
file(COPY_FILE "${seal}" "${seal}.contract-original")
foreach(case missing modified)
  if(case STREQUAL missing)
    file(RENAME "${seal}" "${seal}.contract-saved")
  else()
    file(APPEND "${seal}" "# untrusted completed build seal\n")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}"
    "-DGL_INSTALL_CONTEXT=${BINARY_DIR}/pure-gl-install-context.cmake"
    -DGL_INSTALL_MODE=seal -P "${GL_INSTALL_SCRIPT}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(case STREQUAL missing)
    file(RENAME "${seal}.contract-saved" "${seal}")
  endif()
  file(COPY_FILE "${seal}.contract-original" "${seal}")
  if(rc EQUAL 0 OR NOT err MATCHES "completed build seal identity")
    list(APPEND failures "build-seal/${case}: accepted or unrelated rejection (${rc}) ${err}")
  else()
    message(STATUS "BUILT_AUTHORITY_REJECT_OK build-seal/${case}")
  endif()
endforeach()
file(REMOVE "${seal}.contract-original")
if(failures)
  message(FATAL_ERROR "Completed build authority failed: ${failures}")
endif()
execute_process(COMMAND "${BINARY_DIR}/pure-gl-install-guard.exe"
  --validate-context "${BINARY_DIR}/pure-gl-install-context.cmake"
  COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "PURE_GL_BUILT_AUTHORITY_OK negatives=8 pristine=1")
