cmake_minimum_required(VERSION 3.25)
# Removing full-tree equality, source pins, or disjoint manifest validation must
# make the corresponding mutation below succeed, and therefore fail this test.
set(GL_INSTALL_CONTRACT_HELPERS_ONLY ON)
include("${CMAKE_CURRENT_LIST_DIR}/install_guard_contract.cmake")
unset(GL_INSTALL_CONTRACT_HELPERS_ONLY)
gl_contract_open(install-contract)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef instance)
set(stage "${work}/stage-${instance}")
file(MAKE_DIRECTORY "${stage}")
file(COPY "${PURE_PREFIX}/" DESTINATION "${stage}")

if(RED_ONLY)
  gl_contract_run(legacy-install PASS "${CMAKE_COMMAND}" --install "${BINARY_DIR}"
    --prefix "${stage}")
  # Tasks 1 and 3 intentionally replaced the executable protocols. Exercise
  # the current verifier's unchanged filesystem boundary before those calls.
  file(READ "${SOURCE_DIR}/cmake/VerifyInstalledPackage.cmake" legacy)
  string(FIND "${legacy}" "set(ENV{PATH}" boundary)
  if(boundary LESS 0)
    message(FATAL_ERROR "RED fixture requires the original ownership verifier")
  endif()
  string(SUBSTRING "${legacy}" 0 ${boundary} checks)
  file(WRITE "${work}/legacy-ownership.cmake" "${checks}")
  set(legacy_args "-DSTAGE_PREFIX=${stage}"
    "-DSOURCE_RUNTIME_DIR=${CLANG64_PREFIX}/bin" -DLLVM_READOBJ=unused
    -DLLVM_STRINGS=unused -P "${work}/legacy-ownership.cmake")
  gl_contract_run(legacy-pristine PASS "${CMAKE_COMMAND}" ${legacy_args})
  foreach(case extra-owned extra-outside altered)
    if(case STREQUAL extra-owned)
      set(path "${stage}/lib/pure/unowned.pure")
      file(WRITE "${path}" "UNDECLARED\n")
    elseif(case STREQUAL extra-outside)
      set(path "${stage}/unowned.txt")
      file(WRITE "${path}" "UNDECLARED\n")
    else()
      set(path "${stage}/share/doc/pure-gl/README")
      file(READ "${path}" saved)
      file(APPEND "${path}" "ALTERED INSTALLED BYTES\n")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" ${legacy_args}
      RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    file(WRITE "${work}/red-${case}.log" "exit=${rc}\n${out}${err}")
    if(NOT rc EQUAL 0)
      message(FATAL_ERROR "Legacy ${case} did not reach ownership acceptance: ${out}${err}")
    endif()
    message(STATUS "RED ${case}: current ownership verifier accepted mutation")
    if(case STREQUAL altered)
      file(WRITE "${path}" "${saved}")
    else()
      gl_contract_remove_file("${path}")
    endif()
  endforeach()
  message(FATAL_ERROR "RED: extra-owned, extra-outside and altered bytes were accepted")
endif()

set(context "${BINARY_DIR}/pure-gl-install-context.cmake")
set(verify "${CMAKE_COMMAND}" "-DGL_INSTALL_CONTEXT=${context}"
  "-DSTAGE_PREFIX=${stage}" -P "${SOURCE_DIR}/cmake/VerifyInstalledPackage.cmake")
set(install "${CMAKE_COMMAND}" --install "${BINARY_DIR}" --prefix "${stage}")
gl_contract_snapshot("${stage}" baseline)

foreach(case collision identical-collision changed-baseline extra-outside extra-directory)
  if(case STREQUAL changed-baseline)
    set(path "${stage}/lib/pure/prelude.pure")
    file(COPY_FILE "${path}" "${work}/saved")
    file(APPEND "${path}" "CHANGED BASELINE\n")
  elseif(case STREQUAL extra-outside)
    set(path "${stage}/unowned.txt")
    file(WRITE "${path}" "UNOWNED\n")
  elseif(case STREQUAL extra-directory)
    set(path "${stage}/unowned")
    file(MAKE_DIRECTORY "${path}")
  else()
    set(path "${stage}/lib/pure/GL.pure")
    if(case STREQUAL identical-collision)
      file(COPY_FILE "${SOURCE_DIR}/GL.pure" "${path}")
    else()
      file(WRITE "${path}" "KEEP COLLISION\n")
    endif()
  endif()
  gl_contract_snapshot("${stage}" before)
  gl_contract_run("before-${case}" "canonical baseline|collision" ${install} --component runtime)
  gl_contract_same("${stage}" "${before}")
  if(case STREQUAL changed-baseline)
    file(COPY_FILE "${work}/saved" "${path}")
  elseif(case STREQUAL extra-directory)
    gl_contract_remove_empty("${path}")
  else()
    gl_contract_remove_file("${path}")
  endif()
endforeach()
gl_contract_same("${stage}" "${baseline}")
gl_contract_run(runtime PASS ${install} --component runtime)
if(EXISTS "${stage}/share/doc/pure-gl/README")
  message(FATAL_ERROR "runtime installed documentation")
endif()
gl_contract_run(documentation PASS ${install} --component documentation)
gl_contract_snapshot("${stage}" pristine)

# Literal package destinations independently check the generated inventory.
set(runtime bin/libfreeglut.dll lib/pure/pure-gl.dll lib/pure/GL.pure
  lib/pure/GL_ARB.pure lib/pure/GL_EXT.pure lib/pure/GL_NV.pure
  lib/pure/GL_ATI.pure lib/pure/GLU.pure lib/pure/GLUT.pure)
set(documentation)
foreach(path README COPYING WINDOWS.md THIRD_PARTY.md licenses/FreeGLUT.txt
    examples/simple_glut_example.pure examples/teapot.pure examples/texture.pure
    examples/Imlib2.pure examples/fractal.jpg examples/flexi-line/vector_math.pure
    examples/flexi-line/glamour.pure examples/flexi-line/flexi-line.pure
    examples/flexi-line/flexi-line-auto.pure tests/load.pure tests/hidden-render.pure
    tests/interactive.pure)
  list(APPEND documentation "share/doc/pure-gl/${path}")
endforeach()
foreach(component runtime documentation)
  file(STRINGS "${BINARY_DIR}/install_manifest_${component}.txt" actual)
  list(TRANSFORM actual REPLACE "^${stage}/" "")
  list(SORT actual)
  list(SORT ${component})
  if(NOT actual STREQUAL ${component})
    message(FATAL_ERROR "${component} does not match literal package destinations: ${actual}")
  endif()
endforeach()
gl_contract_run(pristine "PURE_GL_INSTALL_PACKAGE_OK.*installed_tests=2" ${verify})
gl_contract_run(idempotent PASS ${install} --component runtime)
gl_contract_same("${stage}" "${pristine}")
file(RENAME "${stage}/lib/pure/GL.pure" "${stage}/lib/pure/gl.PURE")
gl_contract_snapshot("${stage}" before)
gl_contract_run(case-alias "canonical baseline" ${verify})
gl_contract_same("${stage}" "${before}")
file(RENAME "${stage}/lib/pure/gl.PURE" "${stage}/lib/pure/GL.pure")

foreach(path lib/pure/GL.pure lib/pure/pure-gl.dll bin/libfreeglut.dll
    share/doc/pure-gl/README share/doc/pure-gl/licenses/FreeGLUT.txt
    share/doc/pure-gl/tests/load.pure lib/pure/prelude.pure)
  file(COPY_FILE "${stage}/${path}" "${work}/saved")
  file(APPEND "${stage}/${path}" "ALTERED\n")
  gl_contract_snapshot("${stage}" before)
  string(REPLACE "/" "_" name "${path}")
  gl_contract_run("altered-${name}" "canonical baseline" ${verify})
  gl_contract_same("${stage}" "${before}")
  file(COPY_FILE "${work}/saved" "${stage}/${path}")
endforeach()
foreach(path lib/pure/unowned.pure outside-historical-globs.txt)
  file(WRITE "${stage}/${path}" "UNOWNED\n")
  gl_contract_snapshot("${stage}" before)
  string(REPLACE "/" "_" name "${path}")
  gl_contract_run("extra-${name}" "canonical baseline" ${verify})
  gl_contract_same("${stage}" "${before}")
  gl_contract_remove_file("${stage}/${path}")
endforeach()
file(RENAME "${stage}/lib/pure/GL.pure" "${work}/missing.pure")
gl_contract_snapshot("${stage}" before)
gl_contract_run(missing "canonical baseline" ${verify})
gl_contract_same("${stage}" "${before}")
file(RENAME "${work}/missing.pure" "${stage}/lib/pure/GL.pure")

string(TOLOWER "${stage}" key)
string(SHA256 key "${key}")
set(session "${BINARY_DIR}/install-audits/${key}")
file(READ "${session}/runtime.tsv" manifest)
foreach(case duplicate case-duplicate component-overlap missing unsorted)
  set(mutated "${manifest}")
  if(case STREQUAL duplicate)
    string(REGEX MATCH "[^\n]+" first "${manifest}")
    string(APPEND mutated "${first}\n")
  elseif(case STREQUAL case-duplicate)
    string(REGEX MATCH "[^\n]+" first "${manifest}")
    string(REPLACE "libfreeglut.dll" "LIBFREEGLUT.DLL" first "${first}")
    string(APPEND mutated "${first}\n")
  elseif(case STREQUAL component-overlap)
    file(STRINGS "${session}/documentation.tsv" doc LIMIT_COUNT 1)
    string(APPEND mutated "${doc}\n")
  elseif(case STREQUAL missing)
    file(STRINGS "${session}/runtime.tsv" remaining)
    list(REMOVE_AT remaining 0)
    list(JOIN remaining "\n" mutated)
    string(APPEND mutated "\n")
  else()
    file(STRINGS "${session}/runtime.tsv" reversed)
    list(REVERSE reversed)
    list(JOIN reversed "\n" mutated)
    string(APPEND mutated "\n")
  endif()
  file(WRITE "${session}/runtime.tsv" "${mutated}")
  gl_contract_run("manifest-${case}" "manifest" ${verify})
  gl_contract_same("${stage}" "${pristine}")
  file(WRITE "${session}/runtime.tsv" "${manifest}")
endforeach()

# Untrusted inventory/context inputs never become alternate package authority.
file(READ "${context}" trusted_context)
foreach(case runtime-origin license-origin source-hash guard-identity)
  set(mutated "${trusted_context}")
  if(case STREQUAL runtime-origin)
    file(COPY_FILE "${CLANG64_PREFIX}/bin/libfreeglut.dll" "${work}/libfreeglut.dll")
    string(REPLACE "${CLANG64_PREFIX}/bin/libfreeglut.dll" "${work}/libfreeglut.dll" mutated "${mutated}")
  elseif(case STREQUAL license-origin)
    file(COPY_FILE "${CLANG64_PREFIX}/share/licenses/freeglut/COPYING" "${work}/COPYING")
    string(REPLACE "${CLANG64_PREFIX}/share/licenses/freeglut/COPYING" "${work}/COPYING" mutated "${mutated}")
  elseif(case STREQUAL source-hash)
    string(REPLACE "b6593d5ec4c113a274abb85b10e8615895cb0ddb89f7912af5fe5aa8df38a275" "0000000000000000000000000000000000000000000000000000000000000000" mutated "${mutated}")
  else()
    string(REPLACE "pure-gl-install-guard.exe" "pure-gl-test-runner.exe" mutated "${mutated}")
  endif()
  if(mutated STREQUAL trusted_context)
    message(FATAL_ERROR "No mutation made for ${case}")
  endif()
  file(WRITE "${work}/changed-context.cmake" "${mutated}")
  gl_contract_run("context-${case}" "configured context|context identity"
    "${BINARY_DIR}/pure-gl-install-guard.exe" --validate-context "${work}/changed-context.cmake")
  gl_contract_same("${stage}" "${pristine}")
endforeach()
set(ENV{DESTDIR} "${work}/destdir")
gl_contract_run(destdir "DESTDIR" ${install} --component runtime)
unset(ENV{DESTDIR})
foreach(component unknown Runtime OFF all/invalid)
  string(REPLACE "/" "_" name "${component}")
  gl_contract_run("component-${name}" "unknown component" ${install} --component "${component}")
  gl_contract_same("${stage}" "${pristine}")
endforeach()

# Freeze an independently copied Pure prefix with the real configure command.
# Reconfiguration must never silently bless changed baseline bytes or a lost pin.
include("${context}")
set(fixture_prefix "${work}/configured-prefix")
set(fixture_build "${work}/configured-build")
file(MAKE_DIRECTORY "${fixture_prefix}")
file(COPY "${PURE_PREFIX}/" DESTINATION "${fixture_prefix}")
file(STRINGS "${BINARY_DIR}/CMakeCache.txt" cache_rows
  REGEX "^(CMAKE_GENERATOR|CMAKE_MAKE_PROGRAM|CMAKE_C_COMPILER|PKG_CONFIG_EXECUTABLE|GNU_MAKE_EXECUTABLE):")
foreach(row IN LISTS cache_rows)
  string(REGEX REPLACE "^([^:]+):[^=]+=(.*)$" "\\1" key "${row}")
  string(REGEX REPLACE "^[^=]+=(.*)$" "\\1" value "${row}")
  set("fixture_${key}" "${value}")
endforeach()
set(configure "${CMAKE_COMMAND}" -S "${SOURCE_DIR}" -B "${fixture_build}" -G "${fixture_CMAKE_GENERATOR}"
  "-DCMAKE_MAKE_PROGRAM=${fixture_CMAKE_MAKE_PROGRAM}"
  "-DCMAKE_C_COMPILER=${fixture_CMAKE_C_COMPILER}" -DCMAKE_C_COMPILER_WORKS=1 -DCMAKE_C_ABI_COMPILED=1
  -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DPURE_GL_STRICT_AUDIT=ON
  "-DPURE_GL_PURE_PREFIX=${fixture_prefix}" "-DPURE_EXECUTABLE=${fixture_prefix}/bin/pure.exe"
  "-DPURE_GL_CLANG64_PREFIX=${CLANG64_PREFIX}" -DPURE_GL_WINDOWS_SYSTEM_DIRECTORY=C:/Windows/System32
  "-DPKG_CONFIG_EXECUTABLE=${fixture_PKG_CONFIG_EXECUTABLE}"
  "-DGNU_MAKE_EXECUTABLE=${fixture_GNU_MAKE_EXECUTABLE}"
  "-DLLVM_READOBJ_EXECUTABLE=${LLVM_READOBJ_EXECUTABLE}" "-DLLVM_READOBJ_SHA256=${LLVM_READOBJ_SHA256}"
  "-DLLVM_STRINGS_EXECUTABLE=${LLVM_STRINGS_EXECUTABLE}" "-DLLVM_STRINGS_SHA256=${LLVM_STRINGS_SHA256}")
set(saved_path "$ENV{PATH}")
set(ENV{PATH} "${CLANG64_PREFIX}/bin;C:/Windows/System32;C:/Windows")
gl_contract_run(baseline-configure PASS ${configure})
file(SHA256 "${fixture_build}/pure-gl-install-context.cmake" original_context)
file(COPY_FILE "${fixture_prefix}/lib/pure/prelude.pure" "${work}/baseline.saved")
file(APPEND "${fixture_prefix}/lib/pure/prelude.pure" "CHANGED BASELINE\n")
gl_contract_run(baseline-reconfigure "frozen portable baseline changed" ${configure})
file(SHA256 "${fixture_build}/pure-gl-install-context.cmake" preserved_context)
if(NOT preserved_context STREQUAL original_context)
  message(FATAL_ERROR "Failed reconfiguration changed trusted context")
endif()
file(COPY_FILE "${work}/baseline.saved" "${fixture_prefix}/lib/pure/prelude.pure")
file(RENAME "${fixture_build}/pure-gl-install-baseline.tsv" "${work}/baseline-pin.saved")
gl_contract_run(baseline-missing-pin "missing frozen portable baseline" ${configure})
file(RENAME "${work}/baseline-pin.saved" "${fixture_build}/pure-gl-install-baseline.tsv")
gl_contract_run(baseline-restored PASS ${configure})
gl_contract_run(baseline-build PASS "${CMAKE_COMMAND}" --build "${fixture_build}" --parallel 4)
gl_contract_snapshot("${fixture_prefix}" configured_baseline)
gl_contract_run(baseline-is-destination "stage must be separate"
  "${CMAKE_COMMAND}" --install "${fixture_build}" --prefix "${fixture_prefix}" --component runtime)
gl_contract_same("${fixture_prefix}" "${configured_baseline}")
set(ENV{PATH} "${saved_path}")
gl_contract_run(final-pristine "PURE_GL_INSTALL_PACKAGE_OK.*installed_tests=2" ${verify})
gl_contract_same("${stage}" "${pristine}")
message(STATUS "PURE_GL_INSTALL_CONTRACT_OK mutations=${negative} positives=${positive} runtime=9 documentation=17 installed_tests=4")
gl_contract_clean(install-contract)
