# Behavioral probes shared by the cleanup contract and focused release checks.
function(snapshot root output)
  file(GLOB_RECURSE paths LIST_DIRECTORIES TRUE RELATIVE "${root}" "${root}/*")
  set(rows)
  foreach(path IN LISTS paths)
    if(IS_SYMLINK "${root}/${path}")
      file(REAL_PATH "${root}/${path}" destination)
      list(APPEND rows "${path}|link|${destination}")
    elseif(IS_DIRECTORY "${root}/${path}")
      list(APPEND rows "${path}|directory")
    else()
      file(SHA256 "${root}/${path}" hash)
      list(APPEND rows "${path}|${hash}")
    endif()
  endforeach()
  list(SORT rows)
  set(${output} "${rows}" PARENT_SCOPE)
endfunction()

function(reject name root expected)
  snapshot("${root}" before)
  set(cwd "${root}")
  if(name MATCHES "^(configure|runner|render)-")
    set(cwd "${work}")
  endif()
  execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${cwd}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 120)
  file(WRITE "${work}/${name}.log" "exit=${rc}\n${out}${err}")
  snapshot("${root}" after)
  if(rc EQUAL 0 OR NOT "${out}${err}" MATCHES "${expected}" OR NOT before STREQUAL after)
    message(FATAL_ERROR "Cleanup did not reject before protected writes: ${name} (${rc})\n${out}${err}")
  endif()
  message(STATUS "CLEANUP_REJECT_OK ${name} protected_hashes_unchanged=1")
endfunction()

function(release_check_build_binding)
  set(foreign "${work}/foreign source")
  set(foreign_build "${work}/foreign build")
  file(MAKE_DIRECTORY "${foreign}")
  file(WRITE "${foreign}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.25)\nproject(foreign NONE)\nset(PURE_GL_STRICT_AUDIT ON CACHE BOOL \"\")\nenable_testing()\nadd_test(NAME pure-gl-source-dist-contract COMMAND \"${CMAKE_COMMAND}\" -E touch \"${foreign_build}/wrong-source-dispatched\")\n")
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${foreign}" -B "${foreign_build}"
    -G "${GENERATOR}" "-DCMAKE_MAKE_PROGRAM=${MAKE_PROGRAM}"
    COMMAND_ERROR_IS_FATAL ANY OUTPUT_QUIET)
  reject(distcheck-mismatched-build "${copy}" "source.*mismatch|does not match.*source"
    ${make} distcheck DLL=.dll "DIST_AUDIT_BUILD=${foreign_build}")
  if(EXISTS "${foreign_build}/wrong-source-dispatched")
    message(FATAL_ERROR "Mismatched source build dispatched its CTest")
  endif()
endfunction()

function(release_check_containment)
  foreach(driver source_dist cleanup)
    foreach(layout nested equal)
      set(probe "${work}/containment/${driver}-${layout}")
      set(probe_build "${probe}/nested build")
      if(layout STREQUAL equal)
        set(probe_build "${probe}")
      endif()
      file(MAKE_DIRECTORY "${probe}/tests" "${probe_build}")
      file(COPY_FILE "${SOURCE_DIR}/tests/AuditHelpers.cmake" "${probe}/tests/AuditHelpers.cmake")
      file(COPY_FILE "${BINARY_DIR}/pure-gl-install-guard.exe" "${probe_build}/pure-gl-install-guard.exe")
      # A junction is rejected by native --check-tree before the unfixed
      # recursive copy. Protected marker checks belong to cleanup, not snapshot.
      file(MAKE_DIRECTORY "${work}/containment target")
      file(WRITE "${work}/containment target/keep.txt" "containment target bytes\n")
      file(SHA256 "${work}/containment target/keep.txt" target_before)
      execute_process(COMMAND "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
        -NoProfile -NonInteractive -Command
        "New-Item -ItemType Junction -Path '${probe}/copy-barrier' -Target '${work}/containment target' | Out-Null"
        COMMAND_ERROR_IS_FATAL ANY)
      snapshot("${probe}" before)
      execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOURCE_DIR=${probe}"
        "-DBINARY_DIR=${probe_build}" "-DGNU_MAKE_EXECUTABLE=${GNU_MAKE_EXECUTABLE}"
        -P "${SOURCE_DIR}/tests/${driver}_contract.cmake"
        RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
      file(WRITE "${work}/containment-${driver}-${layout}.log" "exit=${rc}\n${out}${err}")
      snapshot("${probe}" after)
      set(changed FALSE)
      if(NOT before STREQUAL after OR EXISTS "${probe_build}/pure-gl-audits")
        set(changed TRUE)
      endif()
      file(SHA256 "${work}/containment target/keep.txt" target_after)
      if(NOT target_before STREQUAL target_after)
        set(changed TRUE)
      endif()
      # Unlink only the exact fixture junction after the child is gone.
      execute_process(COMMAND "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
        -NoProfile -NonInteractive -Command "[IO.Directory]::Delete('${probe}/copy-barrier')"
        COMMAND_ERROR_IS_FATAL ANY)
      if(rc EQUAL 0 OR NOT "${out}${err}" MATCHES "Source/build.*overlap" OR changed)
        message(FATAL_ERROR "Containment rejection was not early and immutable: ${driver}-${layout} (${rc})\n${out}${err}")
      endif()
      message(STATUS "SOURCE_LAYOUT_REJECT_OK ${driver}-${layout} writes=0")
    endforeach()
  endforeach()
endfunction()

function(release_check_posix_policy)
  set(probe "${work}/posix names")
  file(MAKE_DIRECTORY "${probe}/.pure-gl-dist")
  file(WRITE "${probe}/.pure-gl-source" "pure-gl source 0.9\n")
  file(WRITE "${probe}/.pure-gl-dist/.pure-gl-owner" "owned test leaf\n")
  file(WRITE "${probe}/GL.o" "owned output\n")
  file(WRITE "${probe}/keep.txt" "unrelated bytes\n")
  set(policy "${work}/posix-policy.cmake")
  file(WRITE "${policy}" "cmake_minimum_required(VERSION 3.25)\ninclude(\"${SOURCE_DIR}/cmake/LegacyPathPolicy.cmake\")\npure_gl_legacy_check_names(\"${probe}\")\n")
  foreach(pair "GL.o|gl.O" ".pure-gl-dist|.PURE-GL-DIST"
      ".pure-gl-source|.PURE-GL-SOURCE"
      ".pure-gl-dist/.pure-gl-owner|.pure-gl-dist/.PURE-GL-OWNER")
    string(REPLACE "|" ";" names "${pair}")
    list(GET names 0 original)
    list(GET names 1 alias)
    file(RENAME "${probe}/${original}" "${probe}/${alias}")
    snapshot("${probe}" before)
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${policy}"
      RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    snapshot("${probe}" after)
    file(RENAME "${probe}/${alias}" "${probe}/${original}")
    if(rc EQUAL 0 OR NOT "${out}${err}" MATCHES "case alias" OR NOT before STREQUAL after)
      message(FATAL_ERROR "POSIX reserved case alias escaped: ${pair} (${rc})\n${out}${err}")
    endif()
    message(STATUS "POSIX_NAME_REJECT_OK ${pair}")
  endforeach()
  foreach(marker .GIT .CODEX .AGENTS .PURE-GL-PROTECTED)
    file(WRITE "${probe}/${marker}" "protected marker bytes\n")
    snapshot("${probe}" before)
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${policy}"
      RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
    snapshot("${probe}" after)
    file(REMOVE "${probe}/${marker}")
    if(rc EQUAL 0 OR NOT "${out}${err}" MATCHES "protected descendant" OR NOT before STREQUAL after)
      message(FATAL_ERROR "POSIX case-folded protected marker escaped: ${marker} (${rc})\n${out}${err}")
    endif()
    message(STATUS "POSIX_NAME_REJECT_OK ${marker} writes=0")
  endforeach()
  execute_process(COMMAND "${CMAKE_COMMAND}" -P "${policy}" COMMAND_ERROR_IS_FATAL ANY)
  message(STATUS "POSIX_NAMES_PRISTINE_OK")
endfunction()

function(release_expected_clean before output)
  # Independent fixture policy, deliberately not obtained from the dispatcher.
  set(removed pure-gl.dll GL.o GL_ARB.o GL_EXT.o GL_NV.o GL_ATI.o GLU.o GLUT.o)
  set(expected)
  foreach(row IN LISTS before)
    string(REGEX REPLACE "[|].*$" "" path "${row}")
    if(NOT path IN_LIST removed)
      list(APPEND expected "${row}")
    endif()
  endforeach()
  set(${output} "${expected}" PARENT_SCOPE)
endfunction()

function(release_assert_clean expected)
  snapshot("${copy}" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Clean changed the exact expected inventory or bytes")
  endif()
  if(EXISTS "${copy}/pure-gl.dll")
    message(FATAL_ERROR "Clean retained the owned module")
  endif()
endfunction()
