cmake_minimum_required(VERSION 3.25)
get_filename_component(tools "${CMAKE_COMMAND}" DIRECTORY)
execute_process(COMMAND "${tools}/ctest.exe" --test-dir "${BINARY_DIR}" --show-only=json-v1
  RESULT_VARIABLE rc OUTPUT_VARIABLE inventory ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot inspect CTest inventory: ${err}")
endif()
set(required pure-gl.load-all-modules pure-gl.hidden-render pure-gl-render-contract
  pure-gl-configure-contract pure-gl-runner-contract pure-gl-runtime-verifier-contract
  pure-gl-install-contract pure-gl-install-guard-contract pure-gl-cleanup-contract
  pure-gl-source-dist-contract)
string(JSON count LENGTH "${inventory}" tests)
math(EXPR last "${count}-1")
foreach(i RANGE 0 ${last})
  string(JSON name GET "${inventory}" tests ${i} name)
  if(name MATCHES "interactive")
    message(FATAL_ERROR "Visible interactive test was registered: ${name}")
  endif()
  if(name IN_LIST required)
    string(JSON properties GET "${inventory}" tests ${i} properties)
    if(NOT properties MATCHES "\"gl\"")
      message(FATAL_ERROR "Mandatory contract lacks gl label: ${name}")
    endif()
    list(REMOVE_ITEM required "${name}")
  endif()
endforeach()
if(required)
  message(FATAL_ERROR "Missing mandatory noninteractive CTests: ${required}")
endif()
message(STATUS "PURE_GL_CTEST_INVENTORY_OK mandatory=10 interactive=0 total=${count}")
