cmake_minimum_required(VERSION 3.25)

# Independent explicit input fixture: do not obtain defaults from the project
# under test, pkg-config, its cache, or the inherited MSYS/Pure environment.
foreach(required SOURCE_DIR CLANG64_PREFIX PURE_PREFIX RUNNER)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()
set(input_PURE_MIDI_STRICT_WINDOWS_AUDIT ON)
set(input_CMAKE_C_COMPILER "${CLANG64_PREFIX}/bin/clang.exe")
set(input_CMAKE_C_COMPILER_TARGET "x86_64-w64-windows-gnu")
set(input_CMAKE_MAKE_PROGRAM "${CLANG64_PREFIX}/bin/ninja.exe")
set(input_PKG_CONFIG_EXECUTABLE "${CLANG64_PREFIX}/bin/pkgconf.exe")
set(input_LLVM_READOBJ "${CLANG64_PREFIX}/bin/llvm-readobj.exe")
set(input_PURE_MIDI_CLANG64_PREFIX "${CLANG64_PREFIX}")
set(input_PURE_MIDI_PURE_PREFIX "${PURE_PREFIX}")
set(input_PURE_MIDI_WINDOWS_SYSTEM_DIRECTORY "C:/Windows/System32")
set(input_PURE_EXECUTABLE "${PURE_PREFIX}/bin/pure.exe")
set(input_PURE_INCLUDE_DIR "${PURE_PREFIX}/include")
set(input_PURE_HEADER "${PURE_PREFIX}/include/pure/runtime.h")
set(input_PURE_GLOB_HEADER "${PURE_PREFIX}/include/glob.h")
set(input_PURE_IMPORT_LIBRARY "${PURE_PREFIX}/lib/libpure.dll.a")
set(input_PURE_RUNTIME_DLL "${PURE_PREFIX}/bin/libpure.dll")
set(input_PORTMIDI_HEADER "${CLANG64_PREFIX}/include/portmidi.h")
set(input_PORTMIDI_IMPORT_LIBRARY "${CLANG64_PREFIX}/lib/libportmidi.dll.a")
set(input_PORTTIME_HEADER "${CLANG64_PREFIX}/include/porttime.h")
set(input_PORTMIDI_RUNTIME_DLL "${CLANG64_PREFIX}/bin/libportmidi.dll")
set(input_GMP_HEADER "${CLANG64_PREFIX}/include/gmp.h")
set(input_MPFR_HEADER "${CLANG64_PREFIX}/include/mpfr.h")
set(input_PURE_MIDI_WINDOWS_HEADER "${CLANG64_PREFIX}/include/windows.h")
set(input_PURE_MIDI_MAKE_EXECUTABLE "${CLANG64_PREFIX}/bin/mingw32-make.exe")
set(input_PURE_MIDI_SH_EXECUTABLE "${CLANG64_PREFIX}/../usr/bin/sh.exe")
cmake_path(NORMAL_PATH input_PURE_MIDI_SH_EXECUTABLE)
set(input_PURE_MIDI_RUNTIME_SOURCES)
foreach(name pure.exe libpure.dll libc++.dll libgmp-10.dll libiconv-2.dll
    libmpfr-6.dll libpcre-1.dll libpcreposix-0.dll libreadline8.dll
    libtermcap-0.dll libwinpthread-1.dll libzstd.dll zlib1.dll)
  list(APPEND input_PURE_MIDI_RUNTIME_SOURCES "${name}|${PURE_PREFIX}/bin/${name}")
endforeach()
list(APPEND input_PURE_MIDI_RUNTIME_SOURCES "libportmidi.dll|${CLANG64_PREFIX}/bin/libportmidi.dll")
set(input_CMAKE_BUILD_TYPE Release)
get_cmake_property(variables VARIABLES)
set(keys)
foreach(var IN LISTS variables)
  if(var MATCHES "^input_(.+)$")
    list(APPEND keys "${CMAKE_MATCH_1}")
  endif()
endforeach()

function(write_preset output)
  file(WRITE "${output}" "# Independent pure-midi strict audit fixture.\n")
  foreach(key IN LISTS keys)
    if(NOT key STREQUAL omit)
      file(APPEND "${output}" "set(${key} [==[${input_${key}}]==] CACHE STRING \"Explicit audit input\" FORCE)\n")
    endif()
  endforeach()
  file(APPEND "${output}" "set(CMAKE_BUILD_TYPE Release CACHE STRING \"\" FORCE)\nset(BUILD_TESTING ON CACHE BOOL \"\" FORCE)\n")
endfunction()
if(WRITE_PRESET_ONLY)
  write_preset("${PRESET_OUTPUT}")
  return()
endif()

execute_process(COMMAND "${RUNNER}" --owned-create RESULT_VARIABLE rc OUTPUT_VARIABLE reservation)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot reserve owned contract leaf")
endif()
string(REPLACE "\r" "" reservation "${reservation}")
string(REGEX MATCH "leaf=([^\n]+)\nnonce=([0-9a-f]+)" match "${reservation}")
if(NOT match)
  message(FATAL_ERROR "Malformed owned reservation")
endif()
file(TO_CMAKE_PATH "${CMAKE_MATCH_1}" work)
set(owner "${CMAKE_MATCH_2}")
message(STATUS "CONTRACT_WORK=${work}")
set(negative 0)
set(positive 0)
set(failures)
function(configure_case name accept)
  if(DEFINED CASE_FILTER AND NOT name MATCHES "${CASE_FILTER}")
    return()
  endif()
  write_preset("${work}/${name}.cmake")
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SOURCE_DIR}"
    -B "${work}/${name}" -G Ninja -C "${work}/${name}.cmake"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 60)
  file(WRITE "${work}/${name}.log" "${out}\n${err}")
  if(accept)
    if(NOT rc EQUAL 0)
      message(FATAL_ERROR "${name}: pristine configure failed (${rc}): ${out}\n${err}")
    endif()
    math(EXPR count "${positive}+1")
    set(positive "${count}" PARENT_SCOPE)
  else()
    if(NOT DEFINED expected_rejection)
      set(expected_rejection "midi audit:")
    endif()
    if(rc EQUAL 0 OR NOT "${out}${err}" MATCHES "${expected_rejection}")
      message(STATUS "${name}: rejected=${rc}; expected an audit rejection")
      list(APPEND failures "${name}")
      set(failures "${failures}" PARENT_SCOPE)
    endif()
    math(EXPR count "${negative}+1")
    set(negative "${count}" PARENT_SCOPE)
  endif()
endfunction()

# Missing explicit inputs must fail even when ambient discovery can rescue them.
set(omit PURE_HEADER)
configure_case(missing-header FALSE)
unset(omit)
if(RED_ONLY)
  if(failures)
    message(FATAL_ERROR "RED: strict configure accepted undeclared Pure header")
  endif()
  return()
endif()

foreach(key IN LISTS keys)
  if((key STREQUAL "PURE_MIDI_STRICT_WINDOWS_AUDIT" OR key STREQUAL "CMAKE_BUILD_TYPE"))
    continue()
  endif()
  set(omit "${key}")
  configure_case("missing-${key}" FALSE)
  unset(omit)
endforeach()
foreach(key CMAKE_C_COMPILER CMAKE_MAKE_PROGRAM PKG_CONFIG_EXECUTABLE
    LLVM_READOBJ PURE_EXECUTABLE PURE_HEADER PURE_IMPORT_LIBRARY
    PORTMIDI_HEADER PORTMIDI_IMPORT_LIBRARY PURE_RUNTIME_DLL)
  set(saved "${input_${key}}")
  set(input_${key} "${work}/absent")
  configure_case("nonexistent-${key}" FALSE)
  set(input_${key} "${work}")
  configure_case("directory-${key}" FALSE)
  get_filename_component(filename "${saved}" NAME)
  file(COPY_FILE "${saved}" "${work}/${filename}")
  set(input_${key} "${work}/${filename}")
  configure_case("wrong-origin-${key}" FALSE)
  set(input_${key} "${saved}")
endforeach()
set(saved "${input_PURE_MIDI_RUNTIME_SOURCES}")
foreach(mutation malformed duplicate missing wrong-name)
  if(mutation STREQUAL "malformed")
    list(APPEND input_PURE_MIDI_RUNTIME_SOURCES "invalid|extra|field")
  elseif(mutation STREQUAL "duplicate")
    list(APPEND input_PURE_MIDI_RUNTIME_SOURCES "LIBPURE.DLL|${PURE_PREFIX}/bin/libpure.dll")
  elseif(mutation STREQUAL "missing")
    list(REMOVE_AT input_PURE_MIDI_RUNTIME_SOURCES 2)
  else()
    list(APPEND input_PURE_MIDI_RUNTIME_SOURCES "unknown.dll|${PURE_PREFIX}/bin/libpure.dll")
  endif()
  configure_case("runtime-${mutation}" FALSE)
  set(input_PURE_MIDI_RUNTIME_SOURCES "${saved}")
endforeach()

# An isolated, copied toolchain lets each tool/architecture failure reach its
# intended check at the correct origin. Never change the actual CLANG64 files.
set(private_prefix "${work}/toolchain/clang64")
foreach(key IN LISTS keys)
  set(original_${key} "${input_${key}}")
  if(NOT key STREQUAL "PURE_MIDI_RUNTIME_SOURCES" AND
      input_${key} MATCHES "^${CLANG64_PREFIX}/" AND NOT IS_DIRECTORY "${input_${key}}")
    string(REPLACE "${CLANG64_PREFIX}" "${private_prefix}" copied "${input_${key}}")
    get_filename_component(parent "${copied}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    file(COPY_FILE "${input_${key}}" "${copied}")
  endif()
  string(REPLACE "${CLANG64_PREFIX}" "${private_prefix}" input_${key} "${input_${key}}")
endforeach()
file(MAKE_DIRECTORY "${work}/toolchain/usr/bin")
file(COPY_FILE "${original_PURE_MIDI_SH_EXECUTABLE}" "${work}/toolchain/usr/bin/sh.exe")
foreach(tool_runtime libpkgconf-8.dll libLLVM-22.dll libffi-8.dll libxml2-16.dll)
  file(COPY_FILE "${CLANG64_PREFIX}/bin/${tool_runtime}" "${private_prefix}/bin/${tool_runtime}")
endforeach()
set(input_PURE_MIDI_SH_EXECUTABLE "${work}/toolchain/usr/bin/sh.exe")
foreach(row IN LISTS original_PURE_MIDI_RUNTIME_SOURCES)
  string(REPLACE "|" ";" fields "${row}")
  list(GET fields 1 source)
  if(source MATCHES "^${CLANG64_PREFIX}/")
    string(REPLACE "${CLANG64_PREFIX}" "${private_prefix}" copied "${source}")
    file(COPY_FILE "${source}" "${copied}")
  endif()
endforeach()
file(WRITE "${work}/compiler-fixture.c" [=[
#include <stdio.h>
#include <string.h>
int main(int argc, char **argv) {
  char path[4096], mode[32] = {0};
  if (argc != 3 || strcmp(argv[1], "--no-default-config") ||
      snprintf(path, sizeof(path), "%s.mode", argv[0]) >= (int)sizeof(path)) return 64;
  FILE *f = fopen(path, "rb"); if (!f) return 65;
  if (!fgets(mode, sizeof(mode), f)) return 66; fclose(f);
  if (!strcmp(argv[2], "--version")) puts(!strcmp(mode,"major") ? "clang version 21.0.0" : "clang version 22.1.8");
  else if (!strcmp(argv[2], "-dumpmachine")) puts(!strcmp(mode,"target") ? "i686-w64-windows-gnu" : "x86_64-w64-windows-gnu");
  else return 67;
  return 0;
}
]=])
execute_process(COMMAND "${CLANG64_PREFIX}/bin/clang.exe" -std=c11 -Wall -Wextra -Werror
  "${work}/compiler-fixture.c" -o "${private_prefix}/bin/clang.exe" RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot compile independent compiler version fixture")
endif()
file(WRITE "${private_prefix}/bin/clang.exe.mode" "major")
set(expected_rejection "midi audit: Clang major 22 required")
configure_case(wrong-clang-major FALSE)
file(WRITE "${private_prefix}/bin/clang.exe.mode" "target")
set(expected_rejection "midi audit: Clang target must be")
configure_case(wrong-clang-target FALSE)
file(WRITE "${private_prefix}/bin/clang.exe.mode" "valid")
file(WRITE "${work}/wrong-machine.c" "int midi_wrong_machine(void) { return 1; }\n")
execute_process(COMMAND "${CLANG64_PREFIX}/bin/clang.exe" --target=i686-w64-windows-gnu
  -c "${work}/wrong-machine.c" -o "${work}/wrong-machine.obj" RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot compile I386 COFF mutation")
endif()
execute_process(COMMAND "${CLANG64_PREFIX}/bin/llvm-ar.exe" qc
  "${work}/wrong-machine.a" "${work}/wrong-machine.obj" RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot archive I386 COFF mutation")
endif()
file(COPY_FILE "${work}/wrong-machine.a" "${input_PORTMIDI_IMPORT_LIBRARY}")
set(expected_rejection "midi audit: non-AMD64 import library")
configure_case(non-amd64-import-library FALSE)
file(COPY_FILE "${original_PORTMIDI_IMPORT_LIBRARY}" "${input_PORTMIDI_IMPORT_LIBRARY}")

execute_process(COMMAND "${CLANG64_PREFIX}/bin/clang.exe" --target=x86_64-w64-windows-gnu
  -c "${work}/wrong-machine.c" -o "${work}/plain-amd64.obj" RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot compile plain AMD64 archive mutation")
endif()
execute_process(COMMAND "${CLANG64_PREFIX}/bin/llvm-ar.exe" qc
  "${work}/plain-amd64.a" "${work}/plain-amd64.obj" RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot archive plain AMD64 object mutation")
endif()
file(COPY_FILE "${work}/plain-amd64.a" "${input_PORTMIDI_IMPORT_LIBRARY}")
set(expected_rejection "midi audit: import-library members required")
configure_case(non-import-amd64-archive FALSE)
file(COPY_FILE "${original_PORTMIDI_IMPORT_LIBRARY}" "${input_PORTMIDI_IMPORT_LIBRARY}")

# Wrong PE architecture at its exact declared source, with a fresh declared
# hash: this must reach the PE header check, not merely a hash mismatch.
execute_process(COMMAND "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command
  "$p='${private_prefix}/bin/libportmidi.dll'; $b=[IO.File]::ReadAllBytes($p); $o=[BitConverter]::ToInt32($b,60); $b[$o+4]=0x4c; $b[$o+5]=0x01; [IO.File]::WriteAllBytes($p,$b)"
  RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot establish wrong-machine runtime fixture")
endif()
set(expected_rejection "midi audit: (AMD64 PE32|cannot inspect|PortMidi package mismatch)")
configure_case(non-amd64-runtime FALSE)
file(COPY_FILE "${CLANG64_PREFIX}/bin/libportmidi.dll" "${private_prefix}/bin/libportmidi.dll")


foreach(key PORTMIDI_HEADER PORTTIME_HEADER PORTMIDI_IMPORT_LIBRARY PORTMIDI_RUNTIME_DLL)
  set(saved_path "${input_${key}}")
  if(key STREQUAL "PORTMIDI_IMPORT_LIBRARY")
    # A valid AMD64 import library for another DLL, not a malformed archive.
    file(COPY_FILE "${PURE_PREFIX}/lib/libpure.dll.a" "${saved_path}")
  elseif(key STREQUAL "PORTMIDI_RUNTIME_DLL")
    file(COPY_FILE "${PURE_PREFIX}/bin/libgmp-10.dll" "${saved_path}")
  else()
    file(APPEND "${saved_path}" "mismatched-portmidi-package")
  endif()
  set(expected_rejection "midi audit: PortMidi package mismatch")
  configure_case("mismatched-${key}" FALSE)
  file(COPY_FILE "${original_${key}}" "${saved_path}")
endforeach()

# Endpoint symbolic links and directory junction ancestors are separate inputs.
file(RENAME "${private_prefix}/bin/clang.exe" "${private_prefix}/bin/clang.fixture")
execute_process(COMMAND "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command
  "Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public static class AudioLink { [DllImport(\"kernel32\", CharSet=CharSet.Unicode, SetLastError=true)] [return: MarshalAs(UnmanagedType.I1)] public static extern bool CreateSymbolicLink(string l, string t, int f); }'; if(-not [AudioLink]::CreateSymbolicLink('${private_prefix}/bin/clang.exe','${private_prefix}/bin/clang.fixture',2)) { $code=[Runtime.InteropServices.Marshal]::GetLastWin32Error(); if($code -eq 1314) { 'SYMLINK_UNAVAILABLE Win32=1314'; exit 77 }; throw ('symbolic link creation failed: '+$code) }; if(-not ((Get-Item -LiteralPath '${private_prefix}/bin/clang.exe' -Force -ErrorAction Stop).Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw 'symbolic link fixture is not an actual reparse point' }"
  RESULT_VARIABLE rc OUTPUT_VARIABLE link_output ERROR_VARIABLE link_error)
set(skipped_symlink 0)
if(rc EQUAL 77 AND link_output MATCHES "SYMLINK_UNAVAILABLE Win32=1314")
  set(skipped_symlink 1)
  message(STATUS "CONFIGURE_SYMLINK_SKIP privilege-unavailable Win32=1314; not counted as a negative case")
elseif(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot establish endpoint symbolic-link fixture")
else()
  set(expected_rejection "midi audit: (missing or reparse|redirected path)")
  configure_case(symlink-compiler FALSE)
endif()
set(expected_rejection "midi audit: (missing or reparse|redirected path)")
file(REMOVE "${private_prefix}/bin/clang.exe")
file(RENAME "${private_prefix}/bin/clang.fixture" "${private_prefix}/bin/clang.exe")
file(RENAME "${private_prefix}/include" "${private_prefix}/include-real")
execute_process(COMMAND "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command
  "New-Item -ItemType Junction -Path '${private_prefix}/include' -Target '${private_prefix}/include-real' | Out-Null"
  RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot establish include junction fixture")
endif()
configure_case(junction-header-ancestor FALSE)
execute_process(COMMAND "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command "[IO.Directory]::Delete('${private_prefix}/include')"
  RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot unlink exact owned junction")
endif()
file(RENAME "${private_prefix}/include-real" "${private_prefix}/include")
unset(expected_rejection)
foreach(key IN LISTS keys)
  set(input_${key} "${original_${key}}")
endforeach()

set(overrides CMAKE_TOOLCHAIN_FILE PURE_MIDI_CONFIGURED_INPUT_PIN CMAKE_SUPPRESS_REGENERATION
  CMAKE_SYSROOT CMAKE_SYSROOT_COMPILE CMAKE_SYSROOT_LINK CMAKE_SYSROOT_RELEASE
  CMAKE_C_COMPILER_ARG1 CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN CMAKE_C_STANDARD_INCLUDE_DIRECTORIES
  CMAKE_C_STANDARD_LIBRARIES CMAKE_C_FLAGS_CUSTOM CMAKE_C_FLAGS_RELEASE_INIT
  CMAKE_EXE_LINKER_FLAGS_CUSTOM CMAKE_MODULE_LINKER_FLAGS_RELEASE_INIT)
foreach(base CMAKE_C_FLAGS CMAKE_EXE_LINKER_FLAGS CMAKE_SHARED_LINKER_FLAGS
    CMAKE_MODULE_LINKER_FLAGS CMAKE_STATIC_LINKER_FLAGS
    CMAKE_C_COMPILER_LAUNCHER CMAKE_C_LINKER_LAUNCHER)
  list(APPEND overrides "${base}")
  foreach(config DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
    list(APPEND overrides "${base}_${config}")
  endforeach()
endforeach()
foreach(override IN LISTS overrides)
  list(APPEND keys "${override}")
  if(override STREQUAL "CMAKE_C_COMPILER_TARGET")
    set(input_${override} "i686-w64-windows-gnu")
  elseif(override STREQUAL "CMAKE_SUPPRESS_REGENERATION")
    set(input_${override} ON)
  elseif(override STREQUAL "CMAKE_C_FLAGS")
    set(input_${override} "-m32")
  elseif(override STREQUAL "CMAKE_TOOLCHAIN_FILE")
    file(WRITE "${work}/override.cmake" "message(FATAL_ERROR \"override executed\")\n")
    set(input_${override} "${work}/override.cmake")
  elseif(override STREQUAL "PURE_MIDI_CONFIGURED_INPUT_PIN")
    set(input_${override} "changed-pin")
  elseif(override MATCHES "CMAKE_C_FLAGS_")
    file(WRITE "${work}/injected.h" "#error MIDI_UNDECLARED_FLAG_HEADER\n")
    set(input_${override} "-include ${work}/injected.h")
  elseif(override MATCHES "LINKER_FLAGS")
    set(input_${override} "-L${work}/undeclared-libraries")
  else()
    set(input_${override} "${work}/undeclared-toolchain")
  endif()
  configure_case("override-${override}" FALSE)
  list(REMOVE_ITEM keys "${override}")
  unset(input_${override})
endforeach()

set(ENV{MSYSTEM_PREFIX} "${work}/poison")
set(ENV{MSYSTEM} "MINGW32")
set(ENV{PKG_CONFIG_PATH} "${work}/poison")
set(ENV{PURELIB} "${work}/poison")
set(ENV{PURE_INCLUDE} "${work}/poison")
set(ENV{PURE_LIBRARY} "${work}/poison")
configure_case(pristine-explicit-poisoned TRUE)

# A source changed after configure must not silently become a new build input.
# Copy only the explicit Pure payload into an owned prefix; never edit the host.
if(NOT DEFINED CASE_FILTER OR "frozen-input-build" MATCHES "${CASE_FILTER}")
  set(private_pure "${work}/pure-copy")
  foreach(key IN LISTS keys)
    set(frozen_original_${key} "${input_${key}}")
    if(NOT key STREQUAL "PURE_MIDI_RUNTIME_SOURCES" AND
        input_${key} MATCHES "^${PURE_PREFIX}/" AND NOT IS_DIRECTORY "${input_${key}}")
      string(REPLACE "${PURE_PREFIX}" "${private_pure}" dest "${input_${key}}")
      get_filename_component(parent "${dest}" DIRECTORY)
      file(MAKE_DIRECTORY "${parent}")
      file(COPY_FILE "${input_${key}}" "${dest}")
    endif()
    string(REPLACE "${PURE_PREFIX}" "${private_pure}" input_${key} "${input_${key}}")
  endforeach()
  foreach(name pure.exe libpure.dll libc++.dll libgmp-10.dll libiconv-2.dll
      libmpfr-6.dll libpcre-1.dll libpcreposix-0.dll libreadline8.dll
      libtermcap-0.dll libwinpthread-1.dll libzstd.dll zlib1.dll)
    file(COPY_FILE "${PURE_PREFIX}/bin/${name}" "${private_pure}/bin/${name}")
  endforeach()
  write_preset("${work}/frozen-input.cmake")
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SOURCE_DIR}" -B "${work}/frozen-input"
    -G Ninja -C "${work}/frozen-input.cmake"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 60)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Independent frozen-input configure failed: ${out}${err}")
  endif()
  math(EXPR positive "${positive}+1")
  file(APPEND "${private_pure}/include/pure/runtime.h" "\n/* changed after configure */\n")
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${work}/frozen-input"
    --target pmlib --parallel 4 RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 60)
  file(WRITE "${work}/frozen-input-build.log" "${out}\n${err}")
  if(rc EQUAL 0 OR NOT "${out}${err}" MATCHES "configured inputs changed")
    list(APPEND failures frozen-input-build)
    message(STATUS "frozen-input-build: rejected=${rc}; expected frozen input rejection")
  endif()
  math(EXPR negative "${negative}+1")
  foreach(key IN LISTS keys)
    set(input_${key} "${frozen_original_${key}}")
  endforeach()
endif()

# Check actual compiler dependencies, not only the hashes of unused input paths.
# The alternate headers are valid but byte-different copies in an accepted Pure
# prefix. They must never replace the explicit CLANG64 inputs for either module.
if(NOT DEFINED CASE_FILTER OR "header-shadow" MATCHES "${CASE_FILTER}")
  set(shadow_pure "${work}/shadow-pure")
  foreach(key IN LISTS keys)
    set(shadow_original_${key} "${input_${key}}")
    if(NOT key STREQUAL "PURE_MIDI_RUNTIME_SOURCES" AND
        input_${key} MATCHES "^${PURE_PREFIX}/" AND NOT IS_DIRECTORY "${input_${key}}")
      string(REPLACE "${PURE_PREFIX}" "${shadow_pure}" dest "${input_${key}}")
      get_filename_component(parent "${dest}" DIRECTORY)
      file(MAKE_DIRECTORY "${parent}")
      file(COPY_FILE "${input_${key}}" "${dest}")
    endif()
    string(REPLACE "${PURE_PREFIX}" "${shadow_pure}" input_${key} "${input_${key}}")
  endforeach()
  foreach(name pure.exe libpure.dll libc++.dll libgmp-10.dll libiconv-2.dll
      libmpfr-6.dll libpcre-1.dll libpcreposix-0.dll libreadline8.dll
      libtermcap-0.dll libwinpthread-1.dll libzstd.dll zlib1.dll)
    file(COPY_FILE "${PURE_PREFIX}/bin/${name}" "${shadow_pure}/bin/${name}")
  endforeach()
  foreach(header portmidi.h porttime.h gmp.h mpfr.h windows.h)
    file(COPY_FILE "${CLANG64_PREFIX}/include/${header}" "${shadow_pure}/include/${header}")
    file(APPEND "${shadow_pure}/include/${header}" "\n/* stale owned shadow of ${header} */\n")
    file(SHA256 "${CLANG64_PREFIX}/include/${header}" pristine_hash)
    file(SHA256 "${shadow_pure}/include/${header}" shadow_hash)
    if(pristine_hash STREQUAL shadow_hash)
      message(FATAL_ERROR "Shadow header fixture did not change ${header}")
    endif()
  endforeach()
  write_preset("${work}/header-shadow.cmake")
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SOURCE_DIR}" -B "${work}/header-shadow"
    -G Ninja -C "${work}/header-shadow.cmake"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 60)
  file(WRITE "${work}/header-shadow-configure.log" "${out}\n${err}")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Independent shadow-prefix configure failed: ${out}${err}")
  endif()
  math(EXPR positive "${positive}+1")
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${work}/header-shadow"
    --target pmlib midifile --parallel 4
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 60)
  file(WRITE "${work}/header-shadow-build.log" "${out}\n${err}")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Valid shadow-header fixture build failed: ${out}${err}")
  endif()
  math(EXPR positive "${positive}+1")
  foreach(row "pmlib.dir/pmdev.c.obj|portmidi.h,gmp.h,mpfr.h"
      "pmlib.dir/midi_stream.c.obj|porttime.h,windows.h"
      "midifile.dir/midifile/mf.c.obj|gmp.h,mpfr.h")
    string(REPLACE "|" ";" fields "${row}")
    list(GET fields 0 object)
    list(GET fields 1 headers)
    string(REPLACE "," ";" headers "${headers}")
    execute_process(COMMAND "${CLANG64_PREFIX}/bin/ninja.exe" -C "${work}/header-shadow"
      -t deps "CMakeFiles/${object}" RESULT_VARIABLE rc OUTPUT_VARIABLE deps ERROR_VARIABLE err)
    file(APPEND "${work}/header-shadow-dependencies.log" "${deps}\n${err}")
    if(NOT rc EQUAL 0)
      message(FATAL_ERROR "Cannot inspect actual compiler dependencies: ${err}")
    endif()
    string(REPLACE "\r" "" deps "${deps}")
    string(REPLACE "\n" ";" deps "${deps}")
    list(TRANSFORM deps STRIP)
    list(TRANSFORM deps TOLOWER)
    foreach(header IN LISTS headers)
      string(TOLOWER "${CLANG64_PREFIX}/include/${header}" required)
      string(TOLOWER "${shadow_pure}/include/${header}" forbidden)
      if(NOT required IN_LIST deps OR forbidden IN_LIST deps)
        list(APPEND failures "header-shadow-${object}-${header}")
        message(STATUS "header-shadow: ${object} consumed alternate ${header}")
      endif()
      math(EXPR negative "${negative}+1")
    endforeach()
    if(NOT object STREQUAL "pmlib.dir/midi_stream.c.obj")
      foreach(header pure/runtime.h glob.h)
        string(TOLOWER "${shadow_pure}/include/${header}" required)
        if(NOT required IN_LIST deps)
          message(FATAL_ERROR "Declared Pure ${header} was not used by ${object}")
        endif()
      endforeach()
    endif()
  endforeach()
  foreach(key IN LISTS keys)
    set(input_${key} "${shadow_original_${key}}")
  endforeach()
endif()

if(NOT DEFINED CASE_FILTER OR "build-ambient" MATCHES "${CASE_FILTER}")
  # Keep these paths distinct: Clang deduplicates CPATH against C_INCLUDE_PATH
  # as a system path, which can otherwise hide the intended shadow-header RED.
  file(MAKE_DIRECTORY "${work}/build-poison/CPATH/pure")
  file(WRITE "${work}/build-poison/CPATH/pure/runtime.h" "#error MIDI_UNDECLARED_BUILD_HEADER\n")
  set(poison_variables CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH OBJC_INCLUDE_PATH
    LIBRARY_PATH COMPILER_PATH GCC_EXEC_PREFIX INCLUDE LIB LIBPATH CL _CL_ LINK _LINK_
    CFLAGS CPPFLAGS LDFLAGS CCC_OVERRIDE_OPTIONS CCC_ADD_ARGS SDKROOT DEVELOPER_DIR
    CLANG_CONFIG_FILE_SYSTEM_DIR CLANG_CONFIG_FILE_USER_DIR)
  foreach(var IN LISTS poison_variables)
    set(saved_environment_${var} "$ENV{${var}}")
    file(MAKE_DIRECTORY "${work}/build-poison/${var}")
    set(ENV{${var}} "${work}/build-poison/${var}")
  endforeach()
  set(ENV{CCC_OVERRIDE_OPTIONS} "+--midi-audit-invalid-ambient-option")
  execute_process(COMMAND "${CMAKE_COMMAND}" --build "${work}/pristine-explicit-poisoned"
    --parallel 4 --verbose RESULT_VARIABLE build_rc OUTPUT_VARIABLE build_out ERROR_VARIABLE build_err TIMEOUT 90)
  file(WRITE "${work}/build-ambient.log" "${build_out}\n${build_err}")
  foreach(var IN LISTS poison_variables)
    if(saved_environment_${var} STREQUAL "")
      unset(ENV{${var}})
    else()
      set(ENV{${var}} "${saved_environment_${var}}")
    endif()
  endforeach()
  if(NOT build_rc EQUAL 0)
    message(STATUS "build-ambient: ${build_out}\n${build_err}")
    list(APPEND failures build-ambient)
  endif()
  math(EXPR positive "${positive}+1")
  # The compiler/linker launcher is deliberately not a user cache override.
  # Reconfigure must accept our fixed defaults without weakening the gate.
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${SOURCE_DIR}"
    -B "${work}/pristine-explicit-poisoned" -G Ninja
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 60)
  file(WRITE "${work}/reconfigure-pristine.log" "${out}\n${err}")
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Fixed strict reconfigure failed: ${out}\n${err}")
  endif()
  math(EXPR positive "${positive}+1")
endif()

# Non-strict mode must still accept ordinary upstream discovery.
set(input_PURE_MIDI_STRICT_WINDOWS_AUDIT OFF)
unset(input_CMAKE_C_COMPILER_TARGET)
set(ENV{MSYSTEM_PREFIX} "${CLANG64_PREFIX}")
set(ENV{PKG_CONFIG_PATH} "${PURE_PREFIX}/lib/pkgconfig;${CLANG64_PREFIX}/lib/pkgconfig")
configure_case(normal-upstream TRUE)
if(failures)
  message(FATAL_ERROR "Configure contract failures (${work}): ${failures}")
endif()
execute_process(COMMAND "${RUNNER}" --owned-clean --cwd "${work}" --token "${owner}"
  RESULT_VARIABLE cleanup_rc)
if(NOT cleanup_rc EQUAL 0)
  message(FATAL_ERROR "Owned contract cleanup failed")
endif()
message(STATUS "CONFIGURE_CONTRACT_OK negative=${negative} positive=${positive} skipped_symlink=${skipped_symlink}")
