cmake_minimum_required(VERSION 3.25)

# This producer has no dependency on the verifier's expected-import table.
# Capture real llvm-readobj records independently and alter one contract at a
# time. Only an included test driver may replace the record reader; all origin,
# hash, stage and tool-identity tests exercise the real standalone entry point.
foreach(required SOURCE_DIR MODULE_DIR CLANG64_PREFIX PURE_PREFIX RUNNER)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()
execute_process(COMMAND "${RUNNER}" --owned-create RESULT_VARIABLE rc OUTPUT_VARIABLE reservation)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot reserve owned contract leaf")
endif()
string(REPLACE "\r" "" reservation "${reservation}")
string(REGEX MATCH "leaf=([^\n]+)\nnonce=([0-9a-f]+)" match "${reservation}")
if(NOT match)
  message(FATAL_ERROR "Malformed owned reservation")
endif()
file(TO_CMAKE_PATH "${CMAKE_MATCH_1}" work)
set(owner "${CMAKE_MATCH_2}")
message(STATUS "CONTRACT_WORK=${work}")
file(MAKE_DIRECTORY "${work}/stage/bin" "${work}/stage/lib/pure")
set(names pmlib.dll midifile.dll pure.exe libpure.dll libc++.dll libgmp-10.dll libiconv-2.dll libmpfr-6.dll
  libpcre-1.dll libpcreposix-0.dll libreadline8.dll libtermcap-0.dll
  libwinpthread-1.dll libzstd.dll zlib1.dll libportmidi.dll)
set(rows)
foreach(name IN LISTS names)
  if(name MATCHES "^(pmlib|midifile)\\.dll$")
    set(source "${MODULE_DIR}/${name}")
    set(dest "${work}/stage/lib/pure/${name}")
  elseif(EXISTS "${PURE_PREFIX}/bin/${name}")
    set(source "${PURE_PREFIX}/bin/${name}")
    set(dest "${work}/stage/bin/${name}")
  else()
    set(source "${CLANG64_PREFIX}/bin/${name}")
    set(dest "${work}/stage/bin/${name}")
  endif()
  file(COPY_FILE "${source}" "${dest}")
  execute_process(COMMAND "${CLANG64_PREFIX}/bin/llvm-readobj.exe"
    --file-headers --coff-imports "${dest}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE records ERROR_VARIABLE err)
  if(NOT rc EQUAL 0 OR NOT err STREQUAL "")
    message(FATAL_ERROR "Cannot capture independent ${name}: ${err}")
  endif()
  string(REPLACE "\r\n" "\n" records "${records}")
  file(WRITE "${dest}.records" "${records}")
  if(name STREQUAL "pmlib.dll")
    set(midi_records "${records}")
  endif()
  if(NOT name MATCHES "^(pmlib|midifile)\\.dll$")
    file(SHA256 "${source}" hash)
    string(APPEND rows "${name}|${source}|${hash}\n")
  endif()
endforeach()
file(WRITE "${work}/runtime-sources.txt" "${rows}")
file(WRITE "${work}/recorded-driver.cmake" [=[
cmake_minimum_required(VERSION 3.25)
set(PURE_MIDI_VERIFIER_HELPERS_ONLY ON)
include("${SOURCE_DIR}/cmake/VerifyWindowsDependencies.cmake")
function(midi_read_pe_records path output)
  file(READ "${path}.records" records)
  set(${output} "${records}" PARENT_SCOPE)
endfunction()
midi_verify_closure()
]=])
file(WRITE "${work}/old-readobj.c" "#include <stdio.h>\nint main(void) { puts(\"LLVM version 21.0.0\"); return 0; }\n")
file(MAKE_DIRECTORY "${work}/old-llvm/bin")
execute_process(COMMAND "${CLANG64_PREFIX}/bin/clang.exe" -std=c11 -Wall -Wextra -Werror
  "${work}/old-readobj.c" -o "${work}/old-llvm/bin/llvm-readobj.exe" RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot compile independent readobj version fixture")
endif()
set(negative 0)
set(positive 0)
set(failures)
set(system_directory "C:/Windows/System32")
set(inspection_tool "${CLANG64_PREFIX}/bin/llvm-readobj.exe")
set(inspection_prefix "${CLANG64_PREFIX}")
file(SHA256 "${inspection_tool}" inspection_hash)
set(real_inspection_hash "${inspection_hash}")
function(verify_case name accept)
  if(DEFINED CASE_FILTER AND NOT name MATCHES "${CASE_FILTER}")
    return()
  endif()
  set(driver "${SOURCE_DIR}/cmake/VerifyWindowsDependencies.cmake")
  if(name MATCHES "^parser-|^libpure-extra-transitive-import$|^recorded-")
    set(driver "${work}/recorded-driver.cmake")
  endif()
  set(extra_arguments)
  if(NOT omit_inspection_hash)
    list(APPEND extra_arguments "-DPURE_MIDI_LLVM_READOBJ_SHA256=${inspection_hash}")
  endif()
  if(name STREQUAL "production-cli-cannot-enable-helper")
    list(APPEND extra_arguments -DPURE_MIDI_VERIFIER_HELPERS_ONLY=ON)
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" ${extra_arguments}
    "-DSOURCE_DIR=${SOURCE_DIR}"
    "-DLLVM_READOBJ=${inspection_tool}" "-DRUNTIME_DIR=${CLANG64_PREFIX}/bin"
    "-DPMLIB_MODULE=${MODULE_DIR}/pmlib.dll" "-DMIDIFILE_MODULE=${MODULE_DIR}/midifile.dll"
    "-DPORTMIDI_DLL=${CLANG64_PREFIX}/bin/libportmidi.dll"
    "-DMIDI_MODULE_DIR=${MODULE_DIR}" "-DPURE_MIDI_CLANG64_PREFIX=${inspection_prefix}"
    "-DPURE_MIDI_PURE_PREFIX=${PURE_PREFIX}"
    "-DPURE_MIDI_WINDOWS_SYSTEM_DIRECTORY=${system_directory}"
    "-DPURE_MIDI_RUNTIME_MANIFEST=${work}/runtime-sources.txt"
    "-DSTAGE_PREFIX=${work}/stage"
    -P "${driver}"
    RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 45)
  file(WRITE "${work}/${name}.log" "${out}\n${err}")
  if(accept)
    if(NOT rc EQUAL 0 OR NOT out MATCHES "PE_CLOSURE_OK count=16")
      message(FATAL_ERROR "${name}: independent pristine failed (${rc}): ${out}\n${err}")
    endif()
    math(EXPR count "${positive}+1")
    set(positive "${count}" PARENT_SCOPE)
  else()
    if(NOT DEFINED expected_rejection)
      set(expected_rejection "midi audit:")
    endif()
    if(rc EQUAL 0 OR NOT "${out}${err}" MATCHES "${expected_rejection}")
      list(APPEND failures "${name}")
      set(failures "${failures}" PARENT_SCOPE)
    endif()
    math(EXPR count "${negative}+1")
    set(negative "${count}" PARENT_SCOPE)
  endif()
endfunction()

# The RED control uses the real legacy CLI and a missing staged dependency.
if(RED_ONLY)
  # The old contract has no staged boundary: a missing stage DLL is rescued
  # from its host runtime argument. This is a behavioral RED against real PEs.
  file(REMOVE "${work}/stage/bin/libgmp-10.dll")
  # Pass both legacy and strict inputs so this same probe becomes GREEN for
  # missing stage rejection, never merely because a new argument was omitted.
  set(expected_rejection "midi audit: missing or reparse file")
  verify_case(missing-transitive-host-fallback FALSE)
  if(failures)
    message(FATAL_ERROR "RED: verifier accepted missing staged transitive libgmp-10.dll")
  endif()
  execute_process(COMMAND "${RUNNER}" --owned-clean --cwd "${work}" --token "${owner}"
    RESULT_VARIABLE rc)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR "Owned RED/GREEN probe cleanup failed")
  endif()
  message(STATUS "MISSING_TRANSITIVE_CONTRACT_OK negative=1")
  return()
endif()

file(COPY_FILE "${inspection_tool}" "${work}/llvm-readobj.exe")
set(inspection_tool "${work}/llvm-readobj.exe")
set(expected_rejection "midi audit: wrong origin")
verify_case(tool-foreign-origin FALSE)
set(inspection_tool "${CLANG64_PREFIX}/bin/llvm-readobj.exe")
set(inspection_hash "0000000000000000000000000000000000000000000000000000000000000000")
set(expected_rejection "midi audit: llvm-readobj configured hash mismatch")
verify_case(tool-wrong-hash FALSE)
set(inspection_hash "${real_inspection_hash}")
file(MAKE_DIRECTORY "${work}/altered-llvm/bin")
file(COPY_FILE "${inspection_tool}" "${work}/altered-llvm/bin/llvm-readobj.exe")
file(APPEND "${work}/altered-llvm/bin/llvm-readobj.exe" "changed-after-configure")
set(inspection_prefix "${work}/altered-llvm")
set(inspection_tool "${inspection_prefix}/bin/llvm-readobj.exe")
verify_case(tool-altered-after-pin FALSE)
set(inspection_prefix "${CLANG64_PREFIX}")
set(inspection_tool "${CLANG64_PREFIX}/bin/llvm-readobj.exe")
set(omit_inspection_hash ON)
set(expected_rejection "midi audit: PURE_MIDI_LLVM_READOBJ_SHA256 is required")
verify_case(tool-missing-hash FALSE)
unset(omit_inspection_hash)
set(inspection_prefix "${work}/old-llvm")
set(inspection_tool "${inspection_prefix}/bin/llvm-readobj.exe")
file(SHA256 "${inspection_tool}" inspection_hash)
set(expected_rejection "midi audit: standalone llvm-readobj major 22 required")
verify_case(tool-wrong-major FALSE)
set(inspection_prefix "${CLANG64_PREFIX}")
set(inspection_tool "${CLANG64_PREFIX}/bin/llvm-readobj.exe")
set(inspection_hash "${real_inspection_hash}")
set(expected_rejection "midi audit: helpers-only mode requires inclusion by a driver")
verify_case(production-cli-cannot-enable-helper FALSE)
unset(expected_rejection)
verify_case(pristine TRUE)
verify_case(recorded-pristine TRUE)
string(REPLACE "Name: libpure.dll" "Name: LiBpUrE.DlL" records "${midi_records}")
string(REPLACE "Name: KERNEL32.dll" "Name: KeRnEl32.DlL" records "${records}")
file(WRITE "${work}/stage/lib/pure/pmlib.dll.records" "${records}")
verify_case(recorded-mixed-case-pristine TRUE)
file(WRITE "${work}/stage/lib/pure/pmlib.dll.records" "${midi_records}")
# Characteristics are structured flag records, not arbitrary numeric fields.
# Mutate complete real records while keeping every import and other header intact.
foreach(mutation file-scalar optional-scalar file-duplicate optional-duplicate
    file-unknown optional-unknown file-bit-mismatch optional-bit-mismatch
    file-mask-mismatch optional-mask-mismatch no-executable no-large-address
    invalid-32bit missing-dll no-dynamic-base no-high-entropy no-nx)
  set(records "${midi_records}")
  if(mutation STREQUAL "file-scalar")
    string(REGEX REPLACE "  Characteristics \\[ \\(0x2022\\)[^]]*\\]" "  Characteristics: 0x2022" records "${records}")
  elseif(mutation STREQUAL "optional-scalar")
    string(REGEX REPLACE "  Characteristics \\[ \\(0x160\\)[^]]*\\]" "  Characteristics: 0x160" records "${records}")
  elseif(mutation STREQUAL "file-duplicate")
    string(REPLACE "    IMAGE_FILE_DLL (0x2000)" "    IMAGE_FILE_DLL (0x2000)\n    IMAGE_FILE_DLL (0x2000)" records "${records}")
  elseif(mutation STREQUAL "optional-duplicate")
    string(REPLACE "    IMAGE_DLL_CHARACTERISTICS_NX_COMPAT (0x100)" "    IMAGE_DLL_CHARACTERISTICS_NX_COMPAT (0x100)\n    IMAGE_DLL_CHARACTERISTICS_NX_COMPAT (0x100)" records "${records}")
  elseif(mutation STREQUAL "file-unknown")
    string(REPLACE "    IMAGE_FILE_DLL (0x2000)" "    IMAGE_FILE_BOGUS (0x2000)" records "${records}")
  elseif(mutation STREQUAL "optional-unknown")
    string(REPLACE "    IMAGE_DLL_CHARACTERISTICS_NX_COMPAT (0x100)" "    IMAGE_DLL_CHARACTERISTICS_BOGUS (0x100)" records "${records}")
  elseif(mutation STREQUAL "file-bit-mismatch")
    string(REPLACE "IMAGE_FILE_DLL (0x2000)" "IMAGE_FILE_DLL (0x200)" records "${records}")
  elseif(mutation STREQUAL "optional-bit-mismatch")
    string(REPLACE "IMAGE_DLL_CHARACTERISTICS_NX_COMPAT (0x100)" "IMAGE_DLL_CHARACTERISTICS_NX_COMPAT (0x10)" records "${records}")
  elseif(mutation STREQUAL "file-mask-mismatch")
    string(REPLACE "Characteristics [ (0x2022)" "Characteristics [ (0x2023)" records "${records}")
  elseif(mutation STREQUAL "optional-mask-mismatch")
    string(REPLACE "Characteristics [ (0x160)" "Characteristics [ (0x161)" records "${records}")
  elseif(mutation STREQUAL "no-executable")
    string(REPLACE "    IMAGE_FILE_EXECUTABLE_IMAGE (0x2)\n" "" records "${records}")
    string(REPLACE "Characteristics [ (0x2022)" "Characteristics [ (0x2020)" records "${records}")
  elseif(mutation STREQUAL "no-large-address")
    string(REPLACE "    IMAGE_FILE_LARGE_ADDRESS_AWARE (0x20)\n" "" records "${records}")
    string(REPLACE "Characteristics [ (0x2022)" "Characteristics [ (0x2002)" records "${records}")
  elseif(mutation STREQUAL "invalid-32bit")
    string(REPLACE "Characteristics [ (0x2022)" "Characteristics [ (0x2122)\n    IMAGE_FILE_32BIT_MACHINE (0x100)" records "${records}")
  elseif(mutation STREQUAL "missing-dll")
    string(REPLACE "    IMAGE_FILE_DLL (0x2000)\n" "" records "${records}")
    string(REPLACE "Characteristics [ (0x2022)" "Characteristics [ (0x22)" records "${records}")
  elseif(mutation STREQUAL "no-dynamic-base")
    string(REPLACE "    IMAGE_DLL_CHARACTERISTICS_DYNAMIC_BASE (0x40)\n" "" records "${records}")
    string(REPLACE "Characteristics [ (0x160)" "Characteristics [ (0x120)" records "${records}")
  elseif(mutation STREQUAL "no-high-entropy")
    string(REPLACE "    IMAGE_DLL_CHARACTERISTICS_HIGH_ENTROPY_VA (0x20)\n" "" records "${records}")
    string(REPLACE "Characteristics [ (0x160)" "Characteristics [ (0x140)" records "${records}")
  else()
    string(REPLACE "    IMAGE_DLL_CHARACTERISTICS_NX_COMPAT (0x100)\n" "" records "${records}")
    string(REPLACE "Characteristics [ (0x160)" "Characteristics [ (0x60)" records "${records}")
  endif()
  if(records STREQUAL midi_records)
    message(FATAL_ERROR "Characteristics mutation did not change ${mutation}")
  endif()
  file(WRITE "${work}/stage/lib/pure/pmlib.dll.records" "${records}")
  verify_case("parser-characteristics-${mutation}" FALSE)
endforeach()
file(WRITE "${work}/stage/lib/pure/pmlib.dll.records" "${midi_records}")
foreach(mutation unknown missing duplicate forbidden-msys forbidden-gcc forbidden-cxx
    delay malformed no-name multiple-name wrong-machine wrong-format wrong-magic
    extra-header stray-name unknown-record trailing-garbage truncated-header
    missing-header-field unknown-header-field invalid-header-value
    missing-symbol duplicate-symbol nonzero-delay-directory unsupported-header-layout)
  set(records "${midi_records}")
  if(mutation STREQUAL "unknown")
    string(APPEND records "Import {\n  Name: unknown.dll\n  ImportLookupTableRVA: 0x1\n  ImportAddressTableRVA: 0x2\n  Symbol: audit_fixture_symbol (0)\n}\n")
  elseif(mutation STREQUAL "missing")
    string(REGEX REPLACE "Import \\{\n  Name: libpure.dll[^}]*}\n" "" records "${records}")
  elseif(mutation STREQUAL "duplicate")
    string(APPEND records "Import {\n  Name: LIBPURE.DLL\n  ImportLookupTableRVA: 0x1\n  ImportAddressTableRVA: 0x2\n  Symbol: audit_fixture_symbol (0)\n}\n")
  elseif(mutation MATCHES "^forbidden-")
    if(mutation STREQUAL "forbidden-msys")
      set(bad "MsYs-2.0.DlL")
    elseif(mutation STREQUAL "forbidden-gcc")
      set(bad "LiBgCc_s_seh-1.DLL")
    else()
      set(bad "LiBsTdC++-6.DlL")
    endif()
    string(REPLACE "Name: libpure.dll" "Name: ${bad}" records "${records}")
  elseif(mutation STREQUAL "delay")
    string(REPLACE "Import {" "DelayImport {" records "${records}")
  elseif(mutation STREQUAL "malformed")
    string(APPEND records "Import {\n  Name: broken.dll\n")
  elseif(mutation STREQUAL "no-name")
    string(REPLACE "  Name: libpure.dll\n" "" records "${records}")
  elseif(mutation STREQUAL "multiple-name")
    string(REPLACE "Name: libpure.dll" "Name: libpure.dll\n  Name: extra.dll" records "${records}")
  elseif(mutation STREQUAL "wrong-machine")
    string(REPLACE "IMAGE_FILE_MACHINE_AMD64 (0x8664)" "IMAGE_FILE_MACHINE_I386 (0x14C)" records "${records}")
  elseif(mutation STREQUAL "wrong-format")
    string(REPLACE "Format: COFF-x86-64" "Format: ELF64-x86-64" records "${records}")
  elseif(mutation STREQUAL "wrong-magic")
    string(REPLACE "Magic: 0x20B" "Magic: 0x10B" records "${records}")
  elseif(mutation STREQUAL "extra-header")
    string(APPEND records "ImageFileHeader {\n  Machine: IMAGE_FILE_MACHINE_AMD64 (0x8664)\n}\n")
  elseif(mutation STREQUAL "stray-name")
    string(APPEND records "  Name: orphan.dll\n")
  elseif(mutation STREQUAL "unknown-record")
    string(APPEND records "MysteryImport {\n  Name: hidden.dll\n}\n")
  elseif(mutation STREQUAL "trailing-garbage")
    string(APPEND records "not a readobj record\n")
  elseif(mutation STREQUAL "truncated-header")
    string(REPLACE "DOSHeader {" "DOSHeader" records "${records}")
  elseif(mutation STREQUAL "missing-header-field")
    string(REGEX REPLACE "  SectionCount: [0-9]+\n" "" records "${records}")
  elseif(mutation STREQUAL "unknown-header-field")
    string(REPLACE "ImageFileHeader {" "ImageFileHeader {\n  HiddenImport: malicious.dll" records "${records}")
  elseif(mutation STREQUAL "missing-symbol")
    string(REGEX REPLACE "  Symbol: [^\n]+\n" "" records "${records}")
  elseif(mutation STREQUAL "duplicate-symbol")
    string(REPLACE "  Symbol: pure_clear_sentry (0)" "  Symbol: pure_clear_sentry (0)\n  Symbol: pure_clear_sentry (0)" records "${records}")
  elseif(mutation STREQUAL "nonzero-delay-directory")
    string(REPLACE "DelayImportDescriptorRVA: 0x0" "DelayImportDescriptorRVA: 0x1000" records "${records}")
  elseif(mutation STREQUAL "unsupported-header-layout")
    string(REPLACE "OptionalHeaderSize: 240" "OptionalHeaderSize: 224" records "${records}")
  else()
    string(REGEX REPLACE "  SectionCount: [0-9]+" "  SectionCount: invalid" records "${records}")
  endif()
  if(records STREQUAL midi_records)
    message(FATAL_ERROR "Mutation ${mutation} did not alter the fixture")
  endif()
  file(WRITE "${work}/stage/lib/pure/pmlib.dll.records" "${records}")
  if(mutation STREQUAL "duplicate")
    set(expected_rejection "midi audit: duplicate import")
  elseif(mutation MATCHES "^(unknown|missing)$")
    set(expected_rejection "midi audit: exact imports differ")
  elseif(mutation MATCHES "^forbidden-")
    set(expected_rejection "midi audit: forbidden runtime import")
  endif()
  verify_case("parser-${mutation}" FALSE)
  unset(expected_rejection)
endforeach()
file(WRITE "${work}/stage/lib/pure/pmlib.dll.records" "${midi_records}")
file(RENAME "${work}/stage/bin/libgmp-10.dll" "${work}/stage/bin/libgmp-10.keep")
verify_case(missing-transitive-host-fallback FALSE)
file(RENAME "${work}/stage/bin/libgmp-10.keep" "${work}/stage/bin/libgmp-10.dll")
file(COPY_FILE "${work}/stage/bin/libgmp-10.dll" "${work}/stage/bin/extra.dll")
verify_case(extra-staged-pe FALSE)
file(REMOVE "${work}/stage/bin/extra.dll")
file(COPY_FILE "${work}/stage/bin/libgmp-10.dll" "${work}/stage/bin/extra.payload")
verify_case(extra-staged-renamed-pe FALSE)
file(REMOVE "${work}/stage/bin/extra.payload")
file(MAKE_DIRECTORY "${work}/stage/extra")
file(COPY_FILE "${work}/stage/bin/libgmp-10.dll" "${work}/stage/extra/libgmp-10.dll")
verify_case(ambiguous-origin FALSE)
file(REMOVE "${work}/stage/extra/libgmp-10.dll")
file(APPEND "${work}/runtime-sources.txt" "libpure.dll|${PURE_PREFIX}/bin/libpure.dll|bad\n")
verify_case(duplicate-declaration FALSE)
file(WRITE "${work}/runtime-sources.txt" "${rows}")
foreach(mutation malformed-row blank-row missing-declaration changed-source-hash wrong-source-origin)
  if(mutation STREQUAL "malformed-row")
    set(changed "${rows}broken|row|too|many\n")
  elseif(mutation STREQUAL "blank-row")
    set(changed "${rows}\n")
  elseif(mutation STREQUAL "missing-declaration")
    string(REGEX REPLACE "libpure.dll[^\n]+\n" "" changed "${rows}")
  elseif(mutation STREQUAL "changed-source-hash")
    string(REGEX REPLACE "(libpure.dll[^\n]+\\|)[0-9a-f]+" "\\1deadbeef" changed "${rows}")
  else()
    file(MAKE_DIRECTORY "${work}/host")
    file(COPY_FILE "${PURE_PREFIX}/bin/libgmp-10.dll" "${work}/host/libgmp-10.dll")
    string(REPLACE "${PURE_PREFIX}/bin/libgmp-10.dll" "${work}/host/libgmp-10.dll" changed "${rows}")
  endif()
  if(changed STREQUAL rows)
    message(FATAL_ERROR "Runtime manifest mutation ${mutation} did not change input")
  endif()
  file(WRITE "${work}/runtime-sources.txt" "${changed}")
  verify_case("manifest-${mutation}" FALSE)
endforeach()
file(WRITE "${work}/runtime-sources.txt" "${rows}")
file(READ "${work}/stage/bin/libpure.dll.records" pure_records)
file(APPEND "${work}/stage/bin/libpure.dll.records"
  "Import {\n  Name: unknown-transitive.dll\n  ImportLookupTableRVA: 0x1\n  ImportAddressTableRVA: 0x2\n  Symbol: audit_fixture_symbol (0)\n}\n")
set(expected_rejection "midi audit: exact imports differ for libpure.dll")
verify_case(libpure-extra-transitive-import FALSE)
unset(expected_rejection)
file(WRITE "${work}/stage/bin/libpure.dll.records" "${pure_records}")
file(MAKE_DIRECTORY "${work}/foreign-system")
set(system_directory "${work}/foreign-system")
verify_case(non-authoritative-system-directory FALSE)
set(system_directory "C:/Windows/System32")

file(RENAME "${work}/stage/bin/libgmp-10.dll" "${work}/stage/bin/libgmp-10.saved")
execute_process(COMMAND "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command
  "Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public static class MidiLink { [DllImport(\"kernel32\", CharSet=CharSet.Unicode, SetLastError=true)] [return: MarshalAs(UnmanagedType.I1)] public static extern bool CreateSymbolicLink(string l, string t, int f); }'; if(-not [MidiLink]::CreateSymbolicLink('${work}/stage/bin/libgmp-10.dll','${work}/stage/bin/libgmp-10.saved',2)) { $code=[Runtime.InteropServices.Marshal]::GetLastWin32Error(); if($code -eq 1314) { 'SYMLINK_UNAVAILABLE Win32=1314'; exit 77 }; throw ('symbolic link creation failed: '+$code) }; if(-not ((Get-Item -LiteralPath '${work}/stage/bin/libgmp-10.dll' -Force -ErrorAction Stop).Attributes -band [IO.FileAttributes]::ReparsePoint)) { throw 'symbolic link fixture is not an actual reparse point' }"
  RESULT_VARIABLE rc OUTPUT_VARIABLE link_output ERROR_VARIABLE link_error)
set(skipped_symlink 0)
if(rc EQUAL 77 AND link_output MATCHES "SYMLINK_UNAVAILABLE Win32=1314")
  set(skipped_symlink 1)
  message(STATUS "RUNTIME_SYMLINK_SKIP privilege-unavailable Win32=1314; not counted as a negative case")
elseif(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot establish runtime symbolic-link mutation")
else()
  verify_case(staged-runtime-symlink FALSE)
endif()
file(REMOVE "${work}/stage/bin/libgmp-10.dll")
file(RENAME "${work}/stage/bin/libgmp-10.saved" "${work}/stage/bin/libgmp-10.dll")
execute_process(COMMAND "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command
  "New-Item -ItemType Junction -Path '${work}/stage/junction' -Target '${work}/host' | Out-Null"
  RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot establish stage junction mutation")
endif()
verify_case(staged-junction-ancestor FALSE)
execute_process(COMMAND "C:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe"
  -NoProfile -NonInteractive -Command "[IO.Directory]::Delete('${work}/stage/junction')"
  RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "Cannot unlink exact owned stage junction")
endif()
file(APPEND "${work}/stage/bin/libgmp-10.dll" "altered")
verify_case(altered-staged-hash FALSE)
file(COPY_FILE "${PURE_PREFIX}/bin/libgmp-10.dll" "${work}/stage/bin/libgmp-10.dll")
verify_case(restored-pristine TRUE)
if(failures)
  message(FATAL_ERROR "Runtime verifier accepted mutations (${work}): ${failures}")
endif()
execute_process(COMMAND "${RUNNER}" --owned-clean --cwd "${work}" --token "${owner}"
  RESULT_VARIABLE cleanup_rc)
if(NOT cleanup_rc EQUAL 0)
  message(FATAL_ERROR "Owned contract cleanup failed")
endif()
message(STATUS "RUNTIME_VERIFIER_CONTRACT_OK negative=${negative} positive=${positive} pe_count=16 skipped_symlink=${skipped_symlink}")
